package com.news.linglian.dao;

import java.util.List;

import com.news.linglian.entity.Email;

public interface IEmailDao {
    public int update(Email email, Email keyEmail);
    public int updateOfEmailId(Email email, String emailId);
    public int updateOfFromUserId(Email email, String fromUserId);
    public int updateOfToUserId(Email email, String toUserId);
    public int updateOfNewsId(Email email, String newsId);
    public int updateOfBody(Email email, String body);
    public int updateOfTime(Email email, String time);
    public int updateOfParam(Email email, String param);
    public int updateOfStatus(Email email, String status);
    public int updateOfEmailIdAndFromUserId(Email email, String emailId, String fromUserId);
    public int updateOfEmailIdAndToUserId(Email email, String emailId, String toUserId);
    public int updateOfEmailIdAndNewsId(Email email, String emailId, String newsId);
    public int updateOfEmailIdAndBody(Email email, String emailId, String body);
    public int updateOfEmailIdAndTime(Email email, String emailId, String time);
    public int updateOfEmailIdAndParam(Email email, String emailId, String param);
    public int updateOfEmailIdAndStatus(Email email, String emailId, String status);
    public int updateOfFromUserIdAndToUserId(Email email, String fromUserId, String toUserId);
    public int updateOfFromUserIdAndNewsId(Email email, String fromUserId, String newsId);
    public int updateOfFromUserIdAndBody(Email email, String fromUserId, String body);
    public int updateOfFromUserIdAndTime(Email email, String fromUserId, String time);
    public int updateOfFromUserIdAndParam(Email email, String fromUserId, String param);
    public int updateOfFromUserIdAndStatus(Email email, String fromUserId, String status);
    public int updateOfToUserIdAndNewsId(Email email, String toUserId, String newsId);
    public int updateOfToUserIdAndBody(Email email, String toUserId, String body);
    public int updateOfToUserIdAndTime(Email email, String toUserId, String time);
    public int updateOfToUserIdAndParam(Email email, String toUserId, String param);
    public int updateOfToUserIdAndStatus(Email email, String toUserId, String status);
    public int updateOfNewsIdAndBody(Email email, String newsId, String body);
    public int updateOfNewsIdAndTime(Email email, String newsId, String time);
    public int updateOfNewsIdAndParam(Email email, String newsId, String param);
    public int updateOfNewsIdAndStatus(Email email, String newsId, String status);
    public int updateOfBodyAndTime(Email email, String body, String time);
    public int updateOfBodyAndParam(Email email, String body, String param);
    public int updateOfBodyAndStatus(Email email, String body, String status);
    public int updateOfTimeAndParam(Email email, String time, String param);
    public int updateOfTimeAndStatus(Email email, String time, String status);
    public int updateOfParamAndStatus(Email email, String param, String status);
    public int remove(Email email);
    public int removeOfEmailId(String emailId);
    public int removeOfFromUserId(String fromUserId);
    public int removeOfToUserId(String toUserId);
    public int removeOfNewsId(String newsId);
    public int removeOfBody(String body);
    public int removeOfTime(String time);
    public int removeOfParam(String param);
    public int removeOfStatus(String status);
    public int removeOfEmailIdAndFromUserId(String emailId, String fromUserId);
    public int removeOfEmailIdAndToUserId(String emailId, String toUserId);
    public int removeOfEmailIdAndNewsId(String emailId, String newsId);
    public int removeOfEmailIdAndBody(String emailId, String body);
    public int removeOfEmailIdAndTime(String emailId, String time);
    public int removeOfEmailIdAndParam(String emailId, String param);
    public int removeOfEmailIdAndStatus(String emailId, String status);
    public int removeOfFromUserIdAndToUserId(String fromUserId, String toUserId);
    public int removeOfFromUserIdAndNewsId(String fromUserId, String newsId);
    public int removeOfFromUserIdAndBody(String fromUserId, String body);
    public int removeOfFromUserIdAndTime(String fromUserId, String time);
    public int removeOfFromUserIdAndParam(String fromUserId, String param);
    public int removeOfFromUserIdAndStatus(String fromUserId, String status);
    public int removeOfToUserIdAndNewsId(String toUserId, String newsId);
    public int removeOfToUserIdAndBody(String toUserId, String body);
    public int removeOfToUserIdAndTime(String toUserId, String time);
    public int removeOfToUserIdAndParam(String toUserId, String param);
    public int removeOfToUserIdAndStatus(String toUserId, String status);
    public int removeOfNewsIdAndBody(String newsId, String body);
    public int removeOfNewsIdAndTime(String newsId, String time);
    public int removeOfNewsIdAndParam(String newsId, String param);
    public int removeOfNewsIdAndStatus(String newsId, String status);
    public int removeOfBodyAndTime(String body, String time);
    public int removeOfBodyAndParam(String body, String param);
    public int removeOfBodyAndStatus(String body, String status);
    public int removeOfTimeAndParam(String time, String param);
    public int removeOfTimeAndStatus(String time, String status);
    public int removeOfParamAndStatus(String param, String status);
    public int insert(Email email);
    public int insertOfEmailId(String emailId);
    public int insertOfFromUserId(String fromUserId);
    public int insertOfToUserId(String toUserId);
    public int insertOfNewsId(String newsId);
    public int insertOfBody(String body);
    public int insertOfTime(String time);
    public int insertOfParam(String param);
    public int insertOfStatus(String status);
    public int insertOfEmailIdAndFromUserId(String emailId, String fromUserId);
    public int insertOfEmailIdAndToUserId(String emailId, String toUserId);
    public int insertOfEmailIdAndNewsId(String emailId, String newsId);
    public int insertOfEmailIdAndBody(String emailId, String body);
    public int insertOfEmailIdAndTime(String emailId, String time);
    public int insertOfEmailIdAndParam(String emailId, String param);
    public int insertOfEmailIdAndStatus(String emailId, String status);
    public int insertOfFromUserIdAndToUserId(String fromUserId, String toUserId);
    public int insertOfFromUserIdAndNewsId(String fromUserId, String newsId);
    public int insertOfFromUserIdAndBody(String fromUserId, String body);
    public int insertOfFromUserIdAndTime(String fromUserId, String time);
    public int insertOfFromUserIdAndParam(String fromUserId, String param);
    public int insertOfFromUserIdAndStatus(String fromUserId, String status);
    public int insertOfToUserIdAndNewsId(String toUserId, String newsId);
    public int insertOfToUserIdAndBody(String toUserId, String body);
    public int insertOfToUserIdAndTime(String toUserId, String time);
    public int insertOfToUserIdAndParam(String toUserId, String param);
    public int insertOfToUserIdAndStatus(String toUserId, String status);
    public int insertOfNewsIdAndBody(String newsId, String body);
    public int insertOfNewsIdAndTime(String newsId, String time);
    public int insertOfNewsIdAndParam(String newsId, String param);
    public int insertOfNewsIdAndStatus(String newsId, String status);
    public int insertOfBodyAndTime(String body, String time);
    public int insertOfBodyAndParam(String body, String param);
    public int insertOfBodyAndStatus(String body, String status);
    public int insertOfTimeAndParam(String time, String param);
    public int insertOfTimeAndStatus(String time, String status);
    public int insertOfParamAndStatus(String param, String status);
    public Email getEmail(Email email);
    public Email getEmailOfEmailId(String emailId);
    public Email getEmailOfFromUserId(String fromUserId);
    public Email getEmailOfToUserId(String toUserId);
    public Email getEmailOfNewsId(String newsId);
    public Email getEmailOfBody(String body);
    public Email getEmailOfTime(String time);
    public Email getEmailOfParam(String param);
    public Email getEmailOfStatus(String status);
    public Email getEmailOfEmailIdAndFromUserId(String emailId, String fromUserId);
    public Email getEmailOfEmailIdAndToUserId(String emailId, String toUserId);
    public Email getEmailOfEmailIdAndNewsId(String emailId, String newsId);
    public Email getEmailOfEmailIdAndBody(String emailId, String body);
    public Email getEmailOfEmailIdAndTime(String emailId, String time);
    public Email getEmailOfEmailIdAndParam(String emailId, String param);
    public Email getEmailOfEmailIdAndStatus(String emailId, String status);
    public Email getEmailOfFromUserIdAndToUserId(String fromUserId, String toUserId);
    public Email getEmailOfFromUserIdAndNewsId(String fromUserId, String newsId);
    public Email getEmailOfFromUserIdAndBody(String fromUserId, String body);
    public Email getEmailOfFromUserIdAndTime(String fromUserId, String time);
    public Email getEmailOfFromUserIdAndParam(String fromUserId, String param);
    public Email getEmailOfFromUserIdAndStatus(String fromUserId, String status);
    public Email getEmailOfToUserIdAndNewsId(String toUserId, String newsId);
    public Email getEmailOfToUserIdAndBody(String toUserId, String body);
    public Email getEmailOfToUserIdAndTime(String toUserId, String time);
    public Email getEmailOfToUserIdAndParam(String toUserId, String param);
    public Email getEmailOfToUserIdAndStatus(String toUserId, String status);
    public Email getEmailOfNewsIdAndBody(String newsId, String body);
    public Email getEmailOfNewsIdAndTime(String newsId, String time);
    public Email getEmailOfNewsIdAndParam(String newsId, String param);
    public Email getEmailOfNewsIdAndStatus(String newsId, String status);
    public Email getEmailOfBodyAndTime(String body, String time);
    public Email getEmailOfBodyAndParam(String body, String param);
    public Email getEmailOfBodyAndStatus(String body, String status);
    public Email getEmailOfTimeAndParam(String time, String param);
    public Email getEmailOfTimeAndStatus(String time, String status);
    public Email getEmailOfParamAndStatus(String param, String status);
    public List<Email> getEmails(Email email);
    public List<Email> getEmailsOfEmailId(String emailId);
    public List<Email> getEmailsOfFromUserId(String fromUserId);
    public List<Email> getEmailsOfToUserId(String toUserId);
    public List<Email> getEmailsOfNewsId(String newsId);
    public List<Email> getEmailsOfBody(String body);
    public List<Email> getEmailsOfTime(String time);
    public List<Email> getEmailsOfParam(String param);
    public List<Email> getEmailsOfStatus(String status);
    public List<Email> getEmailsOfEmailIdAndFromUserId(String emailId, String fromUserId);
    public List<Email> getEmailsOfEmailIdAndToUserId(String emailId, String toUserId);
    public List<Email> getEmailsOfEmailIdAndNewsId(String emailId, String newsId);
    public List<Email> getEmailsOfEmailIdAndBody(String emailId, String body);
    public List<Email> getEmailsOfEmailIdAndTime(String emailId, String time);
    public List<Email> getEmailsOfEmailIdAndParam(String emailId, String param);
    public List<Email> getEmailsOfEmailIdAndStatus(String emailId, String status);
    public List<Email> getEmailsOfFromUserIdAndToUserId(String fromUserId, String toUserId);
    public List<Email> getEmailsOfFromUserIdAndNewsId(String fromUserId, String newsId);
    public List<Email> getEmailsOfFromUserIdAndBody(String fromUserId, String body);
    public List<Email> getEmailsOfFromUserIdAndTime(String fromUserId, String time);
    public List<Email> getEmailsOfFromUserIdAndParam(String fromUserId, String param);
    public List<Email> getEmailsOfFromUserIdAndStatus(String fromUserId, String status);
    public List<Email> getEmailsOfToUserIdAndNewsId(String toUserId, String newsId);
    public List<Email> getEmailsOfToUserIdAndBody(String toUserId, String body);
    public List<Email> getEmailsOfToUserIdAndTime(String toUserId, String time);
    public List<Email> getEmailsOfToUserIdAndParam(String toUserId, String param);
    public List<Email> getEmailsOfToUserIdAndStatus(String toUserId, String status);
    public List<Email> getEmailsOfNewsIdAndBody(String newsId, String body);
    public List<Email> getEmailsOfNewsIdAndTime(String newsId, String time);
    public List<Email> getEmailsOfNewsIdAndParam(String newsId, String param);
    public List<Email> getEmailsOfNewsIdAndStatus(String newsId, String status);
    public List<Email> getEmailsOfBodyAndTime(String body, String time);
    public List<Email> getEmailsOfBodyAndParam(String body, String param);
    public List<Email> getEmailsOfBodyAndStatus(String body, String status);
    public List<Email> getEmailsOfTimeAndParam(String time, String param);
    public List<Email> getEmailsOfTimeAndStatus(String time, String status);
    public List<Email> getEmailsOfParamAndStatus(String param, String status);
}
