package com.news.linglian.dao;

import java.util.List;

import com.news.linglian.entity.News;

public interface INewsDao {
    public int update(News news, News keyNews);
    public int updateOfNewsId(News news, String newsId);
    public int updateOfTitle(News news, String title);
    public int updateOfBody(News news, String body);
    public int updateOfUserId(News news, String userId);
    public int updateOfUserNewsTypeId(News news, String userNewsTypeId);
    public int updateOfStatus(News news, String status);
    public int updateOfBuff(News news, String buff);
    public int updateOfParam(News news, String param);
    public int updateOfNewsTypeId(News news, String newsTypeId);
    public int updateOfPath(News news, String path);
    public int updateOfGood(News news, String good);
    public int updateOfBad(News news, String bad);
    public int updateOfTime(News news, String time);
    public int updateOfSearch(News news, String search);
    public int updateOfBUserIds(News news, String bUserIds);
    public int updateOfMoney(News news, String money);
    public int updateOfNewsIdAndTitle(News news, String newsId, String title);
    public int updateOfNewsIdAndBody(News news, String newsId, String body);
    public int updateOfNewsIdAndUserId(News news, String newsId, String userId);
    public int updateOfNewsIdAndUserNewsTypeId(News news, String newsId, String userNewsTypeId);
    public int updateOfNewsIdAndStatus(News news, String newsId, String status);
    public int updateOfNewsIdAndBuff(News news, String newsId, String buff);
    public int updateOfNewsIdAndParam(News news, String newsId, String param);
    public int updateOfNewsIdAndNewsTypeId(News news, String newsId, String newsTypeId);
    public int updateOfNewsIdAndPath(News news, String newsId, String path);
    public int updateOfNewsIdAndGood(News news, String newsId, String good);
    public int updateOfNewsIdAndBad(News news, String newsId, String bad);
    public int updateOfNewsIdAndTime(News news, String newsId, String time);
    public int updateOfNewsIdAndSearch(News news, String newsId, String search);
    public int updateOfNewsIdAndBUserIds(News news, String newsId, String bUserIds);
    public int updateOfNewsIdAndMoney(News news, String newsId, String money);
    public int updateOfTitleAndBody(News news, String title, String body);
    public int updateOfTitleAndUserId(News news, String title, String userId);
    public int updateOfTitleAndUserNewsTypeId(News news, String title, String userNewsTypeId);
    public int updateOfTitleAndStatus(News news, String title, String status);
    public int updateOfTitleAndBuff(News news, String title, String buff);
    public int updateOfTitleAndParam(News news, String title, String param);
    public int updateOfTitleAndNewsTypeId(News news, String title, String newsTypeId);
    public int updateOfTitleAndPath(News news, String title, String path);
    public int updateOfTitleAndGood(News news, String title, String good);
    public int updateOfTitleAndBad(News news, String title, String bad);
    public int updateOfTitleAndTime(News news, String title, String time);
    public int updateOfTitleAndSearch(News news, String title, String search);
    public int updateOfTitleAndBUserIds(News news, String title, String bUserIds);
    public int updateOfTitleAndMoney(News news, String title, String money);
    public int updateOfBodyAndUserId(News news, String body, String userId);
    public int updateOfBodyAndUserNewsTypeId(News news, String body, String userNewsTypeId);
    public int updateOfBodyAndStatus(News news, String body, String status);
    public int updateOfBodyAndBuff(News news, String body, String buff);
    public int updateOfBodyAndParam(News news, String body, String param);
    public int updateOfBodyAndNewsTypeId(News news, String body, String newsTypeId);
    public int updateOfBodyAndPath(News news, String body, String path);
    public int updateOfBodyAndGood(News news, String body, String good);
    public int updateOfBodyAndBad(News news, String body, String bad);
    public int updateOfBodyAndTime(News news, String body, String time);
    public int updateOfBodyAndSearch(News news, String body, String search);
    public int updateOfBodyAndBUserIds(News news, String body, String bUserIds);
    public int updateOfBodyAndMoney(News news, String body, String money);
    public int updateOfUserIdAndUserNewsTypeId(News news, String userId, String userNewsTypeId);
    public int updateOfUserIdAndStatus(News news, String userId, String status);
    public int updateOfUserIdAndBuff(News news, String userId, String buff);
    public int updateOfUserIdAndParam(News news, String userId, String param);
    public int updateOfUserIdAndNewsTypeId(News news, String userId, String newsTypeId);
    public int updateOfUserIdAndPath(News news, String userId, String path);
    public int updateOfUserIdAndGood(News news, String userId, String good);
    public int updateOfUserIdAndBad(News news, String userId, String bad);
    public int updateOfUserIdAndTime(News news, String userId, String time);
    public int updateOfUserIdAndSearch(News news, String userId, String search);
    public int updateOfUserIdAndBUserIds(News news, String userId, String bUserIds);
    public int updateOfUserIdAndMoney(News news, String userId, String money);
    public int updateOfUserNewsTypeIdAndStatus(News news, String userNewsTypeId, String status);
    public int updateOfUserNewsTypeIdAndBuff(News news, String userNewsTypeId, String buff);
    public int updateOfUserNewsTypeIdAndParam(News news, String userNewsTypeId, String param);
    public int updateOfUserNewsTypeIdAndNewsTypeId(News news, String userNewsTypeId, String newsTypeId);
    public int updateOfUserNewsTypeIdAndPath(News news, String userNewsTypeId, String path);
    public int updateOfUserNewsTypeIdAndGood(News news, String userNewsTypeId, String good);
    public int updateOfUserNewsTypeIdAndBad(News news, String userNewsTypeId, String bad);
    public int updateOfUserNewsTypeIdAndTime(News news, String userNewsTypeId, String time);
    public int updateOfUserNewsTypeIdAndSearch(News news, String userNewsTypeId, String search);
    public int updateOfUserNewsTypeIdAndBUserIds(News news, String userNewsTypeId, String bUserIds);
    public int updateOfUserNewsTypeIdAndMoney(News news, String userNewsTypeId, String money);
    public int updateOfStatusAndBuff(News news, String status, String buff);
    public int updateOfStatusAndParam(News news, String status, String param);
    public int updateOfStatusAndNewsTypeId(News news, String status, String newsTypeId);
    public int updateOfStatusAndPath(News news, String status, String path);
    public int updateOfStatusAndGood(News news, String status, String good);
    public int updateOfStatusAndBad(News news, String status, String bad);
    public int updateOfStatusAndTime(News news, String status, String time);
    public int updateOfStatusAndSearch(News news, String status, String search);
    public int updateOfStatusAndBUserIds(News news, String status, String bUserIds);
    public int updateOfStatusAndMoney(News news, String status, String money);
    public int updateOfBuffAndParam(News news, String buff, String param);
    public int updateOfBuffAndNewsTypeId(News news, String buff, String newsTypeId);
    public int updateOfBuffAndPath(News news, String buff, String path);
    public int updateOfBuffAndGood(News news, String buff, String good);
    public int updateOfBuffAndBad(News news, String buff, String bad);
    public int updateOfBuffAndTime(News news, String buff, String time);
    public int updateOfBuffAndSearch(News news, String buff, String search);
    public int updateOfBuffAndBUserIds(News news, String buff, String bUserIds);
    public int updateOfBuffAndMoney(News news, String buff, String money);
    public int updateOfParamAndNewsTypeId(News news, String param, String newsTypeId);
    public int updateOfParamAndPath(News news, String param, String path);
    public int updateOfParamAndGood(News news, String param, String good);
    public int updateOfParamAndBad(News news, String param, String bad);
    public int updateOfParamAndTime(News news, String param, String time);
    public int updateOfParamAndSearch(News news, String param, String search);
    public int updateOfParamAndBUserIds(News news, String param, String bUserIds);
    public int updateOfParamAndMoney(News news, String param, String money);
    public int updateOfNewsTypeIdAndPath(News news, String newsTypeId, String path);
    public int updateOfNewsTypeIdAndGood(News news, String newsTypeId, String good);
    public int updateOfNewsTypeIdAndBad(News news, String newsTypeId, String bad);
    public int updateOfNewsTypeIdAndTime(News news, String newsTypeId, String time);
    public int updateOfNewsTypeIdAndSearch(News news, String newsTypeId, String search);
    public int updateOfNewsTypeIdAndBUserIds(News news, String newsTypeId, String bUserIds);
    public int updateOfNewsTypeIdAndMoney(News news, String newsTypeId, String money);
    public int updateOfPathAndGood(News news, String path, String good);
    public int updateOfPathAndBad(News news, String path, String bad);
    public int updateOfPathAndTime(News news, String path, String time);
    public int updateOfPathAndSearch(News news, String path, String search);
    public int updateOfPathAndBUserIds(News news, String path, String bUserIds);
    public int updateOfPathAndMoney(News news, String path, String money);
    public int updateOfGoodAndBad(News news, String good, String bad);
    public int updateOfGoodAndTime(News news, String good, String time);
    public int updateOfGoodAndSearch(News news, String good, String search);
    public int updateOfGoodAndBUserIds(News news, String good, String bUserIds);
    public int updateOfGoodAndMoney(News news, String good, String money);
    public int updateOfBadAndTime(News news, String bad, String time);
    public int updateOfBadAndSearch(News news, String bad, String search);
    public int updateOfBadAndBUserIds(News news, String bad, String bUserIds);
    public int updateOfBadAndMoney(News news, String bad, String money);
    public int updateOfTimeAndSearch(News news, String time, String search);
    public int updateOfTimeAndBUserIds(News news, String time, String bUserIds);
    public int updateOfTimeAndMoney(News news, String time, String money);
    public int updateOfSearchAndBUserIds(News news, String search, String bUserIds);
    public int updateOfSearchAndMoney(News news, String search, String money);
    public int updateOfBUserIdsAndMoney(News news, String bUserIds, String money);
    public int remove(News news);
    public int removeOfNewsId(String newsId);
    public int removeOfTitle(String title);
    public int removeOfBody(String body);
    public int removeOfUserId(String userId);
    public int removeOfUserNewsTypeId(String userNewsTypeId);
    public int removeOfStatus(String status);
    public int removeOfBuff(String buff);
    public int removeOfParam(String param);
    public int removeOfNewsTypeId(String newsTypeId);
    public int removeOfPath(String path);
    public int removeOfGood(String good);
    public int removeOfBad(String bad);
    public int removeOfTime(String time);
    public int removeOfSearch(String search);
    public int removeOfBUserIds(String bUserIds);
    public int removeOfMoney(String money);
    public int removeOfNewsIdAndTitle(String newsId, String title);
    public int removeOfNewsIdAndBody(String newsId, String body);
    public int removeOfNewsIdAndUserId(String newsId, String userId);
    public int removeOfNewsIdAndUserNewsTypeId(String newsId, String userNewsTypeId);
    public int removeOfNewsIdAndStatus(String newsId, String status);
    public int removeOfNewsIdAndBuff(String newsId, String buff);
    public int removeOfNewsIdAndParam(String newsId, String param);
    public int removeOfNewsIdAndNewsTypeId(String newsId, String newsTypeId);
    public int removeOfNewsIdAndPath(String newsId, String path);
    public int removeOfNewsIdAndGood(String newsId, String good);
    public int removeOfNewsIdAndBad(String newsId, String bad);
    public int removeOfNewsIdAndTime(String newsId, String time);
    public int removeOfNewsIdAndSearch(String newsId, String search);
    public int removeOfNewsIdAndBUserIds(String newsId, String bUserIds);
    public int removeOfNewsIdAndMoney(String newsId, String money);
    public int removeOfTitleAndBody(String title, String body);
    public int removeOfTitleAndUserId(String title, String userId);
    public int removeOfTitleAndUserNewsTypeId(String title, String userNewsTypeId);
    public int removeOfTitleAndStatus(String title, String status);
    public int removeOfTitleAndBuff(String title, String buff);
    public int removeOfTitleAndParam(String title, String param);
    public int removeOfTitleAndNewsTypeId(String title, String newsTypeId);
    public int removeOfTitleAndPath(String title, String path);
    public int removeOfTitleAndGood(String title, String good);
    public int removeOfTitleAndBad(String title, String bad);
    public int removeOfTitleAndTime(String title, String time);
    public int removeOfTitleAndSearch(String title, String search);
    public int removeOfTitleAndBUserIds(String title, String bUserIds);
    public int removeOfTitleAndMoney(String title, String money);
    public int removeOfBodyAndUserId(String body, String userId);
    public int removeOfBodyAndUserNewsTypeId(String body, String userNewsTypeId);
    public int removeOfBodyAndStatus(String body, String status);
    public int removeOfBodyAndBuff(String body, String buff);
    public int removeOfBodyAndParam(String body, String param);
    public int removeOfBodyAndNewsTypeId(String body, String newsTypeId);
    public int removeOfBodyAndPath(String body, String path);
    public int removeOfBodyAndGood(String body, String good);
    public int removeOfBodyAndBad(String body, String bad);
    public int removeOfBodyAndTime(String body, String time);
    public int removeOfBodyAndSearch(String body, String search);
    public int removeOfBodyAndBUserIds(String body, String bUserIds);
    public int removeOfBodyAndMoney(String body, String money);
    public int removeOfUserIdAndUserNewsTypeId(String userId, String userNewsTypeId);
    public int removeOfUserIdAndStatus(String userId, String status);
    public int removeOfUserIdAndBuff(String userId, String buff);
    public int removeOfUserIdAndParam(String userId, String param);
    public int removeOfUserIdAndNewsTypeId(String userId, String newsTypeId);
    public int removeOfUserIdAndPath(String userId, String path);
    public int removeOfUserIdAndGood(String userId, String good);
    public int removeOfUserIdAndBad(String userId, String bad);
    public int removeOfUserIdAndTime(String userId, String time);
    public int removeOfUserIdAndSearch(String userId, String search);
    public int removeOfUserIdAndBUserIds(String userId, String bUserIds);
    public int removeOfUserIdAndMoney(String userId, String money);
    public int removeOfUserNewsTypeIdAndStatus(String userNewsTypeId, String status);
    public int removeOfUserNewsTypeIdAndBuff(String userNewsTypeId, String buff);
    public int removeOfUserNewsTypeIdAndParam(String userNewsTypeId, String param);
    public int removeOfUserNewsTypeIdAndNewsTypeId(String userNewsTypeId, String newsTypeId);
    public int removeOfUserNewsTypeIdAndPath(String userNewsTypeId, String path);
    public int removeOfUserNewsTypeIdAndGood(String userNewsTypeId, String good);
    public int removeOfUserNewsTypeIdAndBad(String userNewsTypeId, String bad);
    public int removeOfUserNewsTypeIdAndTime(String userNewsTypeId, String time);
    public int removeOfUserNewsTypeIdAndSearch(String userNewsTypeId, String search);
    public int removeOfUserNewsTypeIdAndBUserIds(String userNewsTypeId, String bUserIds);
    public int removeOfUserNewsTypeIdAndMoney(String userNewsTypeId, String money);
    public int removeOfStatusAndBuff(String status, String buff);
    public int removeOfStatusAndParam(String status, String param);
    public int removeOfStatusAndNewsTypeId(String status, String newsTypeId);
    public int removeOfStatusAndPath(String status, String path);
    public int removeOfStatusAndGood(String status, String good);
    public int removeOfStatusAndBad(String status, String bad);
    public int removeOfStatusAndTime(String status, String time);
    public int removeOfStatusAndSearch(String status, String search);
    public int removeOfStatusAndBUserIds(String status, String bUserIds);
    public int removeOfStatusAndMoney(String status, String money);
    public int removeOfBuffAndParam(String buff, String param);
    public int removeOfBuffAndNewsTypeId(String buff, String newsTypeId);
    public int removeOfBuffAndPath(String buff, String path);
    public int removeOfBuffAndGood(String buff, String good);
    public int removeOfBuffAndBad(String buff, String bad);
    public int removeOfBuffAndTime(String buff, String time);
    public int removeOfBuffAndSearch(String buff, String search);
    public int removeOfBuffAndBUserIds(String buff, String bUserIds);
    public int removeOfBuffAndMoney(String buff, String money);
    public int removeOfParamAndNewsTypeId(String param, String newsTypeId);
    public int removeOfParamAndPath(String param, String path);
    public int removeOfParamAndGood(String param, String good);
    public int removeOfParamAndBad(String param, String bad);
    public int removeOfParamAndTime(String param, String time);
    public int removeOfParamAndSearch(String param, String search);
    public int removeOfParamAndBUserIds(String param, String bUserIds);
    public int removeOfParamAndMoney(String param, String money);
    public int removeOfNewsTypeIdAndPath(String newsTypeId, String path);
    public int removeOfNewsTypeIdAndGood(String newsTypeId, String good);
    public int removeOfNewsTypeIdAndBad(String newsTypeId, String bad);
    public int removeOfNewsTypeIdAndTime(String newsTypeId, String time);
    public int removeOfNewsTypeIdAndSearch(String newsTypeId, String search);
    public int removeOfNewsTypeIdAndBUserIds(String newsTypeId, String bUserIds);
    public int removeOfNewsTypeIdAndMoney(String newsTypeId, String money);
    public int removeOfPathAndGood(String path, String good);
    public int removeOfPathAndBad(String path, String bad);
    public int removeOfPathAndTime(String path, String time);
    public int removeOfPathAndSearch(String path, String search);
    public int removeOfPathAndBUserIds(String path, String bUserIds);
    public int removeOfPathAndMoney(String path, String money);
    public int removeOfGoodAndBad(String good, String bad);
    public int removeOfGoodAndTime(String good, String time);
    public int removeOfGoodAndSearch(String good, String search);
    public int removeOfGoodAndBUserIds(String good, String bUserIds);
    public int removeOfGoodAndMoney(String good, String money);
    public int removeOfBadAndTime(String bad, String time);
    public int removeOfBadAndSearch(String bad, String search);
    public int removeOfBadAndBUserIds(String bad, String bUserIds);
    public int removeOfBadAndMoney(String bad, String money);
    public int removeOfTimeAndSearch(String time, String search);
    public int removeOfTimeAndBUserIds(String time, String bUserIds);
    public int removeOfTimeAndMoney(String time, String money);
    public int removeOfSearchAndBUserIds(String search, String bUserIds);
    public int removeOfSearchAndMoney(String search, String money);
    public int removeOfBUserIdsAndMoney(String bUserIds, String money);
    public int insert(News news);
    public int insertOfNewsId(String newsId);
    public int insertOfTitle(String title);
    public int insertOfBody(String body);
    public int insertOfUserId(String userId);
    public int insertOfUserNewsTypeId(String userNewsTypeId);
    public int insertOfStatus(String status);
    public int insertOfBuff(String buff);
    public int insertOfParam(String param);
    public int insertOfNewsTypeId(String newsTypeId);
    public int insertOfPath(String path);
    public int insertOfGood(String good);
    public int insertOfBad(String bad);
    public int insertOfTime(String time);
    public int insertOfSearch(String search);
    public int insertOfBUserIds(String bUserIds);
    public int insertOfMoney(String money);
    public int insertOfNewsIdAndTitle(String newsId, String title);
    public int insertOfNewsIdAndBody(String newsId, String body);
    public int insertOfNewsIdAndUserId(String newsId, String userId);
    public int insertOfNewsIdAndUserNewsTypeId(String newsId, String userNewsTypeId);
    public int insertOfNewsIdAndStatus(String newsId, String status);
    public int insertOfNewsIdAndBuff(String newsId, String buff);
    public int insertOfNewsIdAndParam(String newsId, String param);
    public int insertOfNewsIdAndNewsTypeId(String newsId, String newsTypeId);
    public int insertOfNewsIdAndPath(String newsId, String path);
    public int insertOfNewsIdAndGood(String newsId, String good);
    public int insertOfNewsIdAndBad(String newsId, String bad);
    public int insertOfNewsIdAndTime(String newsId, String time);
    public int insertOfNewsIdAndSearch(String newsId, String search);
    public int insertOfNewsIdAndBUserIds(String newsId, String bUserIds);
    public int insertOfNewsIdAndMoney(String newsId, String money);
    public int insertOfTitleAndBody(String title, String body);
    public int insertOfTitleAndUserId(String title, String userId);
    public int insertOfTitleAndUserNewsTypeId(String title, String userNewsTypeId);
    public int insertOfTitleAndStatus(String title, String status);
    public int insertOfTitleAndBuff(String title, String buff);
    public int insertOfTitleAndParam(String title, String param);
    public int insertOfTitleAndNewsTypeId(String title, String newsTypeId);
    public int insertOfTitleAndPath(String title, String path);
    public int insertOfTitleAndGood(String title, String good);
    public int insertOfTitleAndBad(String title, String bad);
    public int insertOfTitleAndTime(String title, String time);
    public int insertOfTitleAndSearch(String title, String search);
    public int insertOfTitleAndBUserIds(String title, String bUserIds);
    public int insertOfTitleAndMoney(String title, String money);
    public int insertOfBodyAndUserId(String body, String userId);
    public int insertOfBodyAndUserNewsTypeId(String body, String userNewsTypeId);
    public int insertOfBodyAndStatus(String body, String status);
    public int insertOfBodyAndBuff(String body, String buff);
    public int insertOfBodyAndParam(String body, String param);
    public int insertOfBodyAndNewsTypeId(String body, String newsTypeId);
    public int insertOfBodyAndPath(String body, String path);
    public int insertOfBodyAndGood(String body, String good);
    public int insertOfBodyAndBad(String body, String bad);
    public int insertOfBodyAndTime(String body, String time);
    public int insertOfBodyAndSearch(String body, String search);
    public int insertOfBodyAndBUserIds(String body, String bUserIds);
    public int insertOfBodyAndMoney(String body, String money);
    public int insertOfUserIdAndUserNewsTypeId(String userId, String userNewsTypeId);
    public int insertOfUserIdAndStatus(String userId, String status);
    public int insertOfUserIdAndBuff(String userId, String buff);
    public int insertOfUserIdAndParam(String userId, String param);
    public int insertOfUserIdAndNewsTypeId(String userId, String newsTypeId);
    public int insertOfUserIdAndPath(String userId, String path);
    public int insertOfUserIdAndGood(String userId, String good);
    public int insertOfUserIdAndBad(String userId, String bad);
    public int insertOfUserIdAndTime(String userId, String time);
    public int insertOfUserIdAndSearch(String userId, String search);
    public int insertOfUserIdAndBUserIds(String userId, String bUserIds);
    public int insertOfUserIdAndMoney(String userId, String money);
    public int insertOfUserNewsTypeIdAndStatus(String userNewsTypeId, String status);
    public int insertOfUserNewsTypeIdAndBuff(String userNewsTypeId, String buff);
    public int insertOfUserNewsTypeIdAndParam(String userNewsTypeId, String param);
    public int insertOfUserNewsTypeIdAndNewsTypeId(String userNewsTypeId, String newsTypeId);
    public int insertOfUserNewsTypeIdAndPath(String userNewsTypeId, String path);
    public int insertOfUserNewsTypeIdAndGood(String userNewsTypeId, String good);
    public int insertOfUserNewsTypeIdAndBad(String userNewsTypeId, String bad);
    public int insertOfUserNewsTypeIdAndTime(String userNewsTypeId, String time);
    public int insertOfUserNewsTypeIdAndSearch(String userNewsTypeId, String search);
    public int insertOfUserNewsTypeIdAndBUserIds(String userNewsTypeId, String bUserIds);
    public int insertOfUserNewsTypeIdAndMoney(String userNewsTypeId, String money);
    public int insertOfStatusAndBuff(String status, String buff);
    public int insertOfStatusAndParam(String status, String param);
    public int insertOfStatusAndNewsTypeId(String status, String newsTypeId);
    public int insertOfStatusAndPath(String status, String path);
    public int insertOfStatusAndGood(String status, String good);
    public int insertOfStatusAndBad(String status, String bad);
    public int insertOfStatusAndTime(String status, String time);
    public int insertOfStatusAndSearch(String status, String search);
    public int insertOfStatusAndBUserIds(String status, String bUserIds);
    public int insertOfStatusAndMoney(String status, String money);
    public int insertOfBuffAndParam(String buff, String param);
    public int insertOfBuffAndNewsTypeId(String buff, String newsTypeId);
    public int insertOfBuffAndPath(String buff, String path);
    public int insertOfBuffAndGood(String buff, String good);
    public int insertOfBuffAndBad(String buff, String bad);
    public int insertOfBuffAndTime(String buff, String time);
    public int insertOfBuffAndSearch(String buff, String search);
    public int insertOfBuffAndBUserIds(String buff, String bUserIds);
    public int insertOfBuffAndMoney(String buff, String money);
    public int insertOfParamAndNewsTypeId(String param, String newsTypeId);
    public int insertOfParamAndPath(String param, String path);
    public int insertOfParamAndGood(String param, String good);
    public int insertOfParamAndBad(String param, String bad);
    public int insertOfParamAndTime(String param, String time);
    public int insertOfParamAndSearch(String param, String search);
    public int insertOfParamAndBUserIds(String param, String bUserIds);
    public int insertOfParamAndMoney(String param, String money);
    public int insertOfNewsTypeIdAndPath(String newsTypeId, String path);
    public int insertOfNewsTypeIdAndGood(String newsTypeId, String good);
    public int insertOfNewsTypeIdAndBad(String newsTypeId, String bad);
    public int insertOfNewsTypeIdAndTime(String newsTypeId, String time);
    public int insertOfNewsTypeIdAndSearch(String newsTypeId, String search);
    public int insertOfNewsTypeIdAndBUserIds(String newsTypeId, String bUserIds);
    public int insertOfNewsTypeIdAndMoney(String newsTypeId, String money);
    public int insertOfPathAndGood(String path, String good);
    public int insertOfPathAndBad(String path, String bad);
    public int insertOfPathAndTime(String path, String time);
    public int insertOfPathAndSearch(String path, String search);
    public int insertOfPathAndBUserIds(String path, String bUserIds);
    public int insertOfPathAndMoney(String path, String money);
    public int insertOfGoodAndBad(String good, String bad);
    public int insertOfGoodAndTime(String good, String time);
    public int insertOfGoodAndSearch(String good, String search);
    public int insertOfGoodAndBUserIds(String good, String bUserIds);
    public int insertOfGoodAndMoney(String good, String money);
    public int insertOfBadAndTime(String bad, String time);
    public int insertOfBadAndSearch(String bad, String search);
    public int insertOfBadAndBUserIds(String bad, String bUserIds);
    public int insertOfBadAndMoney(String bad, String money);
    public int insertOfTimeAndSearch(String time, String search);
    public int insertOfTimeAndBUserIds(String time, String bUserIds);
    public int insertOfTimeAndMoney(String time, String money);
    public int insertOfSearchAndBUserIds(String search, String bUserIds);
    public int insertOfSearchAndMoney(String search, String money);
    public int insertOfBUserIdsAndMoney(String bUserIds, String money);
    public News getNews(News news);
    public News getNewsOfNewsId(String newsId);
    public News getNewsOfTitle(String title);
    public News getNewsOfBody(String body);
    public News getNewsOfUserId(String userId);
    public News getNewsOfUserNewsTypeId(String userNewsTypeId);
    public News getNewsOfStatus(String status);
    public News getNewsOfBuff(String buff);
    public News getNewsOfParam(String param);
    public News getNewsOfNewsTypeId(String newsTypeId);
    public News getNewsOfPath(String path);
    public News getNewsOfGood(String good);
    public News getNewsOfBad(String bad);
    public News getNewsOfTime(String time);
    public News getNewsOfSearch(String search);
    public News getNewsOfBUserIds(String bUserIds);
    public News getNewsOfMoney(String money);
    public News getNewsOfNewsIdAndTitle(String newsId, String title);
    public News getNewsOfNewsIdAndBody(String newsId, String body);
    public News getNewsOfNewsIdAndUserId(String newsId, String userId);
    public News getNewsOfNewsIdAndUserNewsTypeId(String newsId, String userNewsTypeId);
    public News getNewsOfNewsIdAndStatus(String newsId, String status);
    public News getNewsOfNewsIdAndBuff(String newsId, String buff);
    public News getNewsOfNewsIdAndParam(String newsId, String param);
    public News getNewsOfNewsIdAndNewsTypeId(String newsId, String newsTypeId);
    public News getNewsOfNewsIdAndPath(String newsId, String path);
    public News getNewsOfNewsIdAndGood(String newsId, String good);
    public News getNewsOfNewsIdAndBad(String newsId, String bad);
    public News getNewsOfNewsIdAndTime(String newsId, String time);
    public News getNewsOfNewsIdAndSearch(String newsId, String search);
    public News getNewsOfNewsIdAndBUserIds(String newsId, String bUserIds);
    public News getNewsOfNewsIdAndMoney(String newsId, String money);
    public News getNewsOfTitleAndBody(String title, String body);
    public News getNewsOfTitleAndUserId(String title, String userId);
    public News getNewsOfTitleAndUserNewsTypeId(String title, String userNewsTypeId);
    public News getNewsOfTitleAndStatus(String title, String status);
    public News getNewsOfTitleAndBuff(String title, String buff);
    public News getNewsOfTitleAndParam(String title, String param);
    public News getNewsOfTitleAndNewsTypeId(String title, String newsTypeId);
    public News getNewsOfTitleAndPath(String title, String path);
    public News getNewsOfTitleAndGood(String title, String good);
    public News getNewsOfTitleAndBad(String title, String bad);
    public News getNewsOfTitleAndTime(String title, String time);
    public News getNewsOfTitleAndSearch(String title, String search);
    public News getNewsOfTitleAndBUserIds(String title, String bUserIds);
    public News getNewsOfTitleAndMoney(String title, String money);
    public News getNewsOfBodyAndUserId(String body, String userId);
    public News getNewsOfBodyAndUserNewsTypeId(String body, String userNewsTypeId);
    public News getNewsOfBodyAndStatus(String body, String status);
    public News getNewsOfBodyAndBuff(String body, String buff);
    public News getNewsOfBodyAndParam(String body, String param);
    public News getNewsOfBodyAndNewsTypeId(String body, String newsTypeId);
    public News getNewsOfBodyAndPath(String body, String path);
    public News getNewsOfBodyAndGood(String body, String good);
    public News getNewsOfBodyAndBad(String body, String bad);
    public News getNewsOfBodyAndTime(String body, String time);
    public News getNewsOfBodyAndSearch(String body, String search);
    public News getNewsOfBodyAndBUserIds(String body, String bUserIds);
    public News getNewsOfBodyAndMoney(String body, String money);
    public News getNewsOfUserIdAndUserNewsTypeId(String userId, String userNewsTypeId);
    public News getNewsOfUserIdAndStatus(String userId, String status);
    public News getNewsOfUserIdAndBuff(String userId, String buff);
    public News getNewsOfUserIdAndParam(String userId, String param);
    public News getNewsOfUserIdAndNewsTypeId(String userId, String newsTypeId);
    public News getNewsOfUserIdAndPath(String userId, String path);
    public News getNewsOfUserIdAndGood(String userId, String good);
    public News getNewsOfUserIdAndBad(String userId, String bad);
    public News getNewsOfUserIdAndTime(String userId, String time);
    public News getNewsOfUserIdAndSearch(String userId, String search);
    public News getNewsOfUserIdAndBUserIds(String userId, String bUserIds);
    public News getNewsOfUserIdAndMoney(String userId, String money);
    public News getNewsOfUserNewsTypeIdAndStatus(String userNewsTypeId, String status);
    public News getNewsOfUserNewsTypeIdAndBuff(String userNewsTypeId, String buff);
    public News getNewsOfUserNewsTypeIdAndParam(String userNewsTypeId, String param);
    public News getNewsOfUserNewsTypeIdAndNewsTypeId(String userNewsTypeId, String newsTypeId);
    public News getNewsOfUserNewsTypeIdAndPath(String userNewsTypeId, String path);
    public News getNewsOfUserNewsTypeIdAndGood(String userNewsTypeId, String good);
    public News getNewsOfUserNewsTypeIdAndBad(String userNewsTypeId, String bad);
    public News getNewsOfUserNewsTypeIdAndTime(String userNewsTypeId, String time);
    public News getNewsOfUserNewsTypeIdAndSearch(String userNewsTypeId, String search);
    public News getNewsOfUserNewsTypeIdAndBUserIds(String userNewsTypeId, String bUserIds);
    public News getNewsOfUserNewsTypeIdAndMoney(String userNewsTypeId, String money);
    public News getNewsOfStatusAndBuff(String status, String buff);
    public News getNewsOfStatusAndParam(String status, String param);
    public News getNewsOfStatusAndNewsTypeId(String status, String newsTypeId);
    public News getNewsOfStatusAndPath(String status, String path);
    public News getNewsOfStatusAndGood(String status, String good);
    public News getNewsOfStatusAndBad(String status, String bad);
    public News getNewsOfStatusAndTime(String status, String time);
    public News getNewsOfStatusAndSearch(String status, String search);
    public News getNewsOfStatusAndBUserIds(String status, String bUserIds);
    public News getNewsOfStatusAndMoney(String status, String money);
    public News getNewsOfBuffAndParam(String buff, String param);
    public News getNewsOfBuffAndNewsTypeId(String buff, String newsTypeId);
    public News getNewsOfBuffAndPath(String buff, String path);
    public News getNewsOfBuffAndGood(String buff, String good);
    public News getNewsOfBuffAndBad(String buff, String bad);
    public News getNewsOfBuffAndTime(String buff, String time);
    public News getNewsOfBuffAndSearch(String buff, String search);
    public News getNewsOfBuffAndBUserIds(String buff, String bUserIds);
    public News getNewsOfBuffAndMoney(String buff, String money);
    public News getNewsOfParamAndNewsTypeId(String param, String newsTypeId);
    public News getNewsOfParamAndPath(String param, String path);
    public News getNewsOfParamAndGood(String param, String good);
    public News getNewsOfParamAndBad(String param, String bad);
    public News getNewsOfParamAndTime(String param, String time);
    public News getNewsOfParamAndSearch(String param, String search);
    public News getNewsOfParamAndBUserIds(String param, String bUserIds);
    public News getNewsOfParamAndMoney(String param, String money);
    public News getNewsOfNewsTypeIdAndPath(String newsTypeId, String path);
    public News getNewsOfNewsTypeIdAndGood(String newsTypeId, String good);
    public News getNewsOfNewsTypeIdAndBad(String newsTypeId, String bad);
    public News getNewsOfNewsTypeIdAndTime(String newsTypeId, String time);
    public News getNewsOfNewsTypeIdAndSearch(String newsTypeId, String search);
    public News getNewsOfNewsTypeIdAndBUserIds(String newsTypeId, String bUserIds);
    public News getNewsOfNewsTypeIdAndMoney(String newsTypeId, String money);
    public News getNewsOfPathAndGood(String path, String good);
    public News getNewsOfPathAndBad(String path, String bad);
    public News getNewsOfPathAndTime(String path, String time);
    public News getNewsOfPathAndSearch(String path, String search);
    public News getNewsOfPathAndBUserIds(String path, String bUserIds);
    public News getNewsOfPathAndMoney(String path, String money);
    public News getNewsOfGoodAndBad(String good, String bad);
    public News getNewsOfGoodAndTime(String good, String time);
    public News getNewsOfGoodAndSearch(String good, String search);
    public News getNewsOfGoodAndBUserIds(String good, String bUserIds);
    public News getNewsOfGoodAndMoney(String good, String money);
    public News getNewsOfBadAndTime(String bad, String time);
    public News getNewsOfBadAndSearch(String bad, String search);
    public News getNewsOfBadAndBUserIds(String bad, String bUserIds);
    public News getNewsOfBadAndMoney(String bad, String money);
    public News getNewsOfTimeAndSearch(String time, String search);
    public News getNewsOfTimeAndBUserIds(String time, String bUserIds);
    public News getNewsOfTimeAndMoney(String time, String money);
    public News getNewsOfSearchAndBUserIds(String search, String bUserIds);
    public News getNewsOfSearchAndMoney(String search, String money);
    public News getNewsOfBUserIdsAndMoney(String bUserIds, String money);
    public List<News> getNewss(News news);
    public List<News> getNewssOfNewsId(String newsId);
    public List<News> getNewssOfTitle(String title);
    public List<News> getNewssOfBody(String body);
    public List<News> getNewssOfUserId(String userId);
    public List<News> getNewssOfUserNewsTypeId(String userNewsTypeId);
    public List<News> getNewssOfStatus(String status);
    public List<News> getNewssOfBuff(String buff);
    public List<News> getNewssOfParam(String param);
    public List<News> getNewssOfNewsTypeId(String newsTypeId);
    public List<News> getNewssOfPath(String path);
    public List<News> getNewssOfGood(String good);
    public List<News> getNewssOfBad(String bad);
    public List<News> getNewssOfTime(String time);
    public List<News> getNewssOfSearch(String search);
    public List<News> getNewssOfBUserIds(String bUserIds);
    public List<News> getNewssOfMoney(String money);
    public List<News> getNewssOfNewsIdAndTitle(String newsId, String title);
    public List<News> getNewssOfNewsIdAndBody(String newsId, String body);
    public List<News> getNewssOfNewsIdAndUserId(String newsId, String userId);
    public List<News> getNewssOfNewsIdAndUserNewsTypeId(String newsId, String userNewsTypeId);
    public List<News> getNewssOfNewsIdAndStatus(String newsId, String status);
    public List<News> getNewssOfNewsIdAndBuff(String newsId, String buff);
    public List<News> getNewssOfNewsIdAndParam(String newsId, String param);
    public List<News> getNewssOfNewsIdAndNewsTypeId(String newsId, String newsTypeId);
    public List<News> getNewssOfNewsIdAndPath(String newsId, String path);
    public List<News> getNewssOfNewsIdAndGood(String newsId, String good);
    public List<News> getNewssOfNewsIdAndBad(String newsId, String bad);
    public List<News> getNewssOfNewsIdAndTime(String newsId, String time);
    public List<News> getNewssOfNewsIdAndSearch(String newsId, String search);
    public List<News> getNewssOfNewsIdAndBUserIds(String newsId, String bUserIds);
    public List<News> getNewssOfNewsIdAndMoney(String newsId, String money);
    public List<News> getNewssOfTitleAndBody(String title, String body);
    public List<News> getNewssOfTitleAndUserId(String title, String userId);
    public List<News> getNewssOfTitleAndUserNewsTypeId(String title, String userNewsTypeId);
    public List<News> getNewssOfTitleAndStatus(String title, String status);
    public List<News> getNewssOfTitleAndBuff(String title, String buff);
    public List<News> getNewssOfTitleAndParam(String title, String param);
    public List<News> getNewssOfTitleAndNewsTypeId(String title, String newsTypeId);
    public List<News> getNewssOfTitleAndPath(String title, String path);
    public List<News> getNewssOfTitleAndGood(String title, String good);
    public List<News> getNewssOfTitleAndBad(String title, String bad);
    public List<News> getNewssOfTitleAndTime(String title, String time);
    public List<News> getNewssOfTitleAndSearch(String title, String search);
    public List<News> getNewssOfTitleAndBUserIds(String title, String bUserIds);
    public List<News> getNewssOfTitleAndMoney(String title, String money);
    public List<News> getNewssOfBodyAndUserId(String body, String userId);
    public List<News> getNewssOfBodyAndUserNewsTypeId(String body, String userNewsTypeId);
    public List<News> getNewssOfBodyAndStatus(String body, String status);
    public List<News> getNewssOfBodyAndBuff(String body, String buff);
    public List<News> getNewssOfBodyAndParam(String body, String param);
    public List<News> getNewssOfBodyAndNewsTypeId(String body, String newsTypeId);
    public List<News> getNewssOfBodyAndPath(String body, String path);
    public List<News> getNewssOfBodyAndGood(String body, String good);
    public List<News> getNewssOfBodyAndBad(String body, String bad);
    public List<News> getNewssOfBodyAndTime(String body, String time);
    public List<News> getNewssOfBodyAndSearch(String body, String search);
    public List<News> getNewssOfBodyAndBUserIds(String body, String bUserIds);
    public List<News> getNewssOfBodyAndMoney(String body, String money);
    public List<News> getNewssOfUserIdAndUserNewsTypeId(String userId, String userNewsTypeId);
    public List<News> getNewssOfUserIdAndStatus(String userId, String status);
    public List<News> getNewssOfUserIdAndBuff(String userId, String buff);
    public List<News> getNewssOfUserIdAndParam(String userId, String param);
    public List<News> getNewssOfUserIdAndNewsTypeId(String userId, String newsTypeId);
    public List<News> getNewssOfUserIdAndPath(String userId, String path);
    public List<News> getNewssOfUserIdAndGood(String userId, String good);
    public List<News> getNewssOfUserIdAndBad(String userId, String bad);
    public List<News> getNewssOfUserIdAndTime(String userId, String time);
    public List<News> getNewssOfUserIdAndSearch(String userId, String search);
    public List<News> getNewssOfUserIdAndBUserIds(String userId, String bUserIds);
    public List<News> getNewssOfUserIdAndMoney(String userId, String money);
    public List<News> getNewssOfUserNewsTypeIdAndStatus(String userNewsTypeId, String status);
    public List<News> getNewssOfUserNewsTypeIdAndBuff(String userNewsTypeId, String buff);
    public List<News> getNewssOfUserNewsTypeIdAndParam(String userNewsTypeId, String param);
    public List<News> getNewssOfUserNewsTypeIdAndNewsTypeId(String userNewsTypeId, String newsTypeId);
    public List<News> getNewssOfUserNewsTypeIdAndPath(String userNewsTypeId, String path);
    public List<News> getNewssOfUserNewsTypeIdAndGood(String userNewsTypeId, String good);
    public List<News> getNewssOfUserNewsTypeIdAndBad(String userNewsTypeId, String bad);
    public List<News> getNewssOfUserNewsTypeIdAndTime(String userNewsTypeId, String time);
    public List<News> getNewssOfUserNewsTypeIdAndSearch(String userNewsTypeId, String search);
    public List<News> getNewssOfUserNewsTypeIdAndBUserIds(String userNewsTypeId, String bUserIds);
    public List<News> getNewssOfUserNewsTypeIdAndMoney(String userNewsTypeId, String money);
    public List<News> getNewssOfStatusAndBuff(String status, String buff);
    public List<News> getNewssOfStatusAndParam(String status, String param);
    public List<News> getNewssOfStatusAndNewsTypeId(String status, String newsTypeId);
    public List<News> getNewssOfStatusAndPath(String status, String path);
    public List<News> getNewssOfStatusAndGood(String status, String good);
    public List<News> getNewssOfStatusAndBad(String status, String bad);
    public List<News> getNewssOfStatusAndTime(String status, String time);
    public List<News> getNewssOfStatusAndSearch(String status, String search);
    public List<News> getNewssOfStatusAndBUserIds(String status, String bUserIds);
    public List<News> getNewssOfStatusAndMoney(String status, String money);
    public List<News> getNewssOfBuffAndParam(String buff, String param);
    public List<News> getNewssOfBuffAndNewsTypeId(String buff, String newsTypeId);
    public List<News> getNewssOfBuffAndPath(String buff, String path);
    public List<News> getNewssOfBuffAndGood(String buff, String good);
    public List<News> getNewssOfBuffAndBad(String buff, String bad);
    public List<News> getNewssOfBuffAndTime(String buff, String time);
    public List<News> getNewssOfBuffAndSearch(String buff, String search);
    public List<News> getNewssOfBuffAndBUserIds(String buff, String bUserIds);
    public List<News> getNewssOfBuffAndMoney(String buff, String money);
    public List<News> getNewssOfParamAndNewsTypeId(String param, String newsTypeId);
    public List<News> getNewssOfParamAndPath(String param, String path);
    public List<News> getNewssOfParamAndGood(String param, String good);
    public List<News> getNewssOfParamAndBad(String param, String bad);
    public List<News> getNewssOfParamAndTime(String param, String time);
    public List<News> getNewssOfParamAndSearch(String param, String search);
    public List<News> getNewssOfParamAndBUserIds(String param, String bUserIds);
    public List<News> getNewssOfParamAndMoney(String param, String money);
    public List<News> getNewssOfNewsTypeIdAndPath(String newsTypeId, String path);
    public List<News> getNewssOfNewsTypeIdAndGood(String newsTypeId, String good);
    public List<News> getNewssOfNewsTypeIdAndBad(String newsTypeId, String bad);
    public List<News> getNewssOfNewsTypeIdAndTime(String newsTypeId, String time);
    public List<News> getNewssOfNewsTypeIdAndSearch(String newsTypeId, String search);
    public List<News> getNewssOfNewsTypeIdAndBUserIds(String newsTypeId, String bUserIds);
    public List<News> getNewssOfNewsTypeIdAndMoney(String newsTypeId, String money);
    public List<News> getNewssOfPathAndGood(String path, String good);
    public List<News> getNewssOfPathAndBad(String path, String bad);
    public List<News> getNewssOfPathAndTime(String path, String time);
    public List<News> getNewssOfPathAndSearch(String path, String search);
    public List<News> getNewssOfPathAndBUserIds(String path, String bUserIds);
    public List<News> getNewssOfPathAndMoney(String path, String money);
    public List<News> getNewssOfGoodAndBad(String good, String bad);
    public List<News> getNewssOfGoodAndTime(String good, String time);
    public List<News> getNewssOfGoodAndSearch(String good, String search);
    public List<News> getNewssOfGoodAndBUserIds(String good, String bUserIds);
    public List<News> getNewssOfGoodAndMoney(String good, String money);
    public List<News> getNewssOfBadAndTime(String bad, String time);
    public List<News> getNewssOfBadAndSearch(String bad, String search);
    public List<News> getNewssOfBadAndBUserIds(String bad, String bUserIds);
    public List<News> getNewssOfBadAndMoney(String bad, String money);
    public List<News> getNewssOfTimeAndSearch(String time, String search);
    public List<News> getNewssOfTimeAndBUserIds(String time, String bUserIds);
    public List<News> getNewssOfTimeAndMoney(String time, String money);
    public List<News> getNewssOfSearchAndBUserIds(String search, String bUserIds);
    public List<News> getNewssOfSearchAndMoney(String search, String money);
    public List<News> getNewssOfBUserIdsAndMoney(String bUserIds, String money);
}
