package com.news.linglian.dao;

import java.util.List;

import com.news.linglian.entity.News;

public interface INewsDao {
    public int update(News news, News keyNews);
    public int updateOfNewsid(News news, String newsid);
    public int updateOfTitle(News news, String title);
    public int updateOfBody(News news, String body);
    public int updateOfTypeid(News news, String typeid);
    public int updateOfNewsdate(News news, String newsdate);
    public int updateOfUserid(News news, String userid);
    public int updateOfStatus(News news, String status);
    public int updateOfNewsidAndTitle(News news, String newsid, String title);
    public int updateOfNewsidAndBody(News news, String newsid, String body);
    public int updateOfNewsidAndTypeid(News news, String newsid, String typeid);
    public int updateOfNewsidAndNewsdate(News news, String newsid, String newsdate);
    public int updateOfNewsidAndUserid(News news, String newsid, String userid);
    public int updateOfNewsidAndStatus(News news, String newsid, String status);
    public int updateOfTitleAndBody(News news, String title, String body);
    public int updateOfTitleAndTypeid(News news, String title, String typeid);
    public int updateOfTitleAndNewsdate(News news, String title, String newsdate);
    public int updateOfTitleAndUserid(News news, String title, String userid);
    public int updateOfTitleAndStatus(News news, String title, String status);
    public int updateOfBodyAndTypeid(News news, String body, String typeid);
    public int updateOfBodyAndNewsdate(News news, String body, String newsdate);
    public int updateOfBodyAndUserid(News news, String body, String userid);
    public int updateOfBodyAndStatus(News news, String body, String status);
    public int updateOfTypeidAndNewsdate(News news, String typeid, String newsdate);
    public int updateOfTypeidAndUserid(News news, String typeid, String userid);
    public int updateOfTypeidAndStatus(News news, String typeid, String status);
    public int updateOfNewsdateAndUserid(News news, String newsdate, String userid);
    public int updateOfNewsdateAndStatus(News news, String newsdate, String status);
    public int updateOfUseridAndStatus(News news, String userid, String status);
    public int updateOfNewsidAndTitleAndBody(News news, String newsid, String title, String body);
    public int updateOfNewsidAndTitleAndTypeid(News news, String newsid, String title, String typeid);
    public int updateOfNewsidAndTitleAndNewsdate(News news, String newsid, String title, String newsdate);
    public int updateOfNewsidAndTitleAndUserid(News news, String newsid, String title, String userid);
    public int updateOfNewsidAndTitleAndStatus(News news, String newsid, String title, String status);
    public int updateOfNewsidAndBodyAndTypeid(News news, String newsid, String body, String typeid);
    public int updateOfNewsidAndBodyAndNewsdate(News news, String newsid, String body, String newsdate);
    public int updateOfNewsidAndBodyAndUserid(News news, String newsid, String body, String userid);
    public int updateOfNewsidAndBodyAndStatus(News news, String newsid, String body, String status);
    public int updateOfNewsidAndTypeidAndNewsdate(News news, String newsid, String typeid, String newsdate);
    public int updateOfNewsidAndTypeidAndUserid(News news, String newsid, String typeid, String userid);
    public int updateOfNewsidAndTypeidAndStatus(News news, String newsid, String typeid, String status);
    public int updateOfNewsidAndNewsdateAndUserid(News news, String newsid, String newsdate, String userid);
    public int updateOfNewsidAndNewsdateAndStatus(News news, String newsid, String newsdate, String status);
    public int updateOfNewsidAndUseridAndStatus(News news, String newsid, String userid, String status);
    public int updateOfTitleAndBodyAndTypeid(News news, String title, String body, String typeid);
    public int updateOfTitleAndBodyAndNewsdate(News news, String title, String body, String newsdate);
    public int updateOfTitleAndBodyAndUserid(News news, String title, String body, String userid);
    public int updateOfTitleAndBodyAndStatus(News news, String title, String body, String status);
    public int updateOfTitleAndTypeidAndNewsdate(News news, String title, String typeid, String newsdate);
    public int updateOfTitleAndTypeidAndUserid(News news, String title, String typeid, String userid);
    public int updateOfTitleAndTypeidAndStatus(News news, String title, String typeid, String status);
    public int updateOfTitleAndNewsdateAndUserid(News news, String title, String newsdate, String userid);
    public int updateOfTitleAndNewsdateAndStatus(News news, String title, String newsdate, String status);
    public int updateOfTitleAndUseridAndStatus(News news, String title, String userid, String status);
    public int updateOfBodyAndTypeidAndNewsdate(News news, String body, String typeid, String newsdate);
    public int updateOfBodyAndTypeidAndUserid(News news, String body, String typeid, String userid);
    public int updateOfBodyAndTypeidAndStatus(News news, String body, String typeid, String status);
    public int updateOfBodyAndNewsdateAndUserid(News news, String body, String newsdate, String userid);
    public int updateOfBodyAndNewsdateAndStatus(News news, String body, String newsdate, String status);
    public int updateOfBodyAndUseridAndStatus(News news, String body, String userid, String status);
    public int updateOfTypeidAndNewsdateAndUserid(News news, String typeid, String newsdate, String userid);
    public int updateOfTypeidAndNewsdateAndStatus(News news, String typeid, String newsdate, String status);
    public int updateOfTypeidAndUseridAndStatus(News news, String typeid, String userid, String status);
    public int updateOfNewsdateAndUseridAndStatus(News news, String newsdate, String userid, String status);
    public int updateOfNewsidAndTitleAndBodyAndTypeid(News news, String newsid, String title, String body, String typeid);
    public int updateOfNewsidAndTitleAndBodyAndNewsdate(News news, String newsid, String title, String body, String newsdate);
    public int updateOfNewsidAndTitleAndBodyAndUserid(News news, String newsid, String title, String body, String userid);
    public int updateOfNewsidAndTitleAndBodyAndStatus(News news, String newsid, String title, String body, String status);
    public int updateOfNewsidAndTitleAndTypeidAndNewsdate(News news, String newsid, String title, String typeid, String newsdate);
    public int updateOfNewsidAndTitleAndTypeidAndUserid(News news, String newsid, String title, String typeid, String userid);
    public int updateOfNewsidAndTitleAndTypeidAndStatus(News news, String newsid, String title, String typeid, String status);
    public int updateOfNewsidAndTitleAndNewsdateAndUserid(News news, String newsid, String title, String newsdate, String userid);
    public int updateOfNewsidAndTitleAndNewsdateAndStatus(News news, String newsid, String title, String newsdate, String status);
    public int updateOfNewsidAndTitleAndUseridAndStatus(News news, String newsid, String title, String userid, String status);
    public int updateOfNewsidAndBodyAndTypeidAndNewsdate(News news, String newsid, String body, String typeid, String newsdate);
    public int updateOfNewsidAndBodyAndTypeidAndUserid(News news, String newsid, String body, String typeid, String userid);
    public int updateOfNewsidAndBodyAndTypeidAndStatus(News news, String newsid, String body, String typeid, String status);
    public int updateOfNewsidAndBodyAndNewsdateAndUserid(News news, String newsid, String body, String newsdate, String userid);
    public int updateOfNewsidAndBodyAndNewsdateAndStatus(News news, String newsid, String body, String newsdate, String status);
    public int updateOfNewsidAndBodyAndUseridAndStatus(News news, String newsid, String body, String userid, String status);
    public int updateOfNewsidAndTypeidAndNewsdateAndUserid(News news, String newsid, String typeid, String newsdate, String userid);
    public int updateOfNewsidAndTypeidAndNewsdateAndStatus(News news, String newsid, String typeid, String newsdate, String status);
    public int updateOfNewsidAndTypeidAndUseridAndStatus(News news, String newsid, String typeid, String userid, String status);
    public int updateOfNewsidAndNewsdateAndUseridAndStatus(News news, String newsid, String newsdate, String userid, String status);
    public int updateOfTitleAndBodyAndTypeidAndNewsdate(News news, String title, String body, String typeid, String newsdate);
    public int updateOfTitleAndBodyAndTypeidAndUserid(News news, String title, String body, String typeid, String userid);
    public int updateOfTitleAndBodyAndTypeidAndStatus(News news, String title, String body, String typeid, String status);
    public int updateOfTitleAndBodyAndNewsdateAndUserid(News news, String title, String body, String newsdate, String userid);
    public int updateOfTitleAndBodyAndNewsdateAndStatus(News news, String title, String body, String newsdate, String status);
    public int updateOfTitleAndBodyAndUseridAndStatus(News news, String title, String body, String userid, String status);
    public int updateOfTitleAndTypeidAndNewsdateAndUserid(News news, String title, String typeid, String newsdate, String userid);
    public int updateOfTitleAndTypeidAndNewsdateAndStatus(News news, String title, String typeid, String newsdate, String status);
    public int updateOfTitleAndTypeidAndUseridAndStatus(News news, String title, String typeid, String userid, String status);
    public int updateOfTitleAndNewsdateAndUseridAndStatus(News news, String title, String newsdate, String userid, String status);
    public int updateOfBodyAndTypeidAndNewsdateAndUserid(News news, String body, String typeid, String newsdate, String userid);
    public int updateOfBodyAndTypeidAndNewsdateAndStatus(News news, String body, String typeid, String newsdate, String status);
    public int updateOfBodyAndTypeidAndUseridAndStatus(News news, String body, String typeid, String userid, String status);
    public int updateOfBodyAndNewsdateAndUseridAndStatus(News news, String body, String newsdate, String userid, String status);
    public int updateOfTypeidAndNewsdateAndUseridAndStatus(News news, String typeid, String newsdate, String userid, String status);
    public int updateOfNewsidAndTitleAndBodyAndTypeidAndNewsdate(News news, String newsid, String title, String body, String typeid, String newsdate);
    public int updateOfNewsidAndTitleAndBodyAndTypeidAndUserid(News news, String newsid, String title, String body, String typeid, String userid);
    public int updateOfNewsidAndTitleAndBodyAndTypeidAndStatus(News news, String newsid, String title, String body, String typeid, String status);
    public int updateOfNewsidAndTitleAndBodyAndNewsdateAndUserid(News news, String newsid, String title, String body, String newsdate, String userid);
    public int updateOfNewsidAndTitleAndBodyAndNewsdateAndStatus(News news, String newsid, String title, String body, String newsdate, String status);
    public int updateOfNewsidAndTitleAndBodyAndUseridAndStatus(News news, String newsid, String title, String body, String userid, String status);
    public int updateOfNewsidAndTitleAndTypeidAndNewsdateAndUserid(News news, String newsid, String title, String typeid, String newsdate, String userid);
    public int updateOfNewsidAndTitleAndTypeidAndNewsdateAndStatus(News news, String newsid, String title, String typeid, String newsdate, String status);
    public int updateOfNewsidAndTitleAndTypeidAndUseridAndStatus(News news, String newsid, String title, String typeid, String userid, String status);
    public int updateOfNewsidAndTitleAndNewsdateAndUseridAndStatus(News news, String newsid, String title, String newsdate, String userid, String status);
    public int updateOfNewsidAndBodyAndTypeidAndNewsdateAndUserid(News news, String newsid, String body, String typeid, String newsdate, String userid);
    public int updateOfNewsidAndBodyAndTypeidAndNewsdateAndStatus(News news, String newsid, String body, String typeid, String newsdate, String status);
    public int updateOfNewsidAndBodyAndTypeidAndUseridAndStatus(News news, String newsid, String body, String typeid, String userid, String status);
    public int updateOfNewsidAndBodyAndNewsdateAndUseridAndStatus(News news, String newsid, String body, String newsdate, String userid, String status);
    public int updateOfNewsidAndTypeidAndNewsdateAndUseridAndStatus(News news, String newsid, String typeid, String newsdate, String userid, String status);
    public int updateOfTitleAndBodyAndTypeidAndNewsdateAndUserid(News news, String title, String body, String typeid, String newsdate, String userid);
    public int updateOfTitleAndBodyAndTypeidAndNewsdateAndStatus(News news, String title, String body, String typeid, String newsdate, String status);
    public int updateOfTitleAndBodyAndTypeidAndUseridAndStatus(News news, String title, String body, String typeid, String userid, String status);
    public int updateOfTitleAndBodyAndNewsdateAndUseridAndStatus(News news, String title, String body, String newsdate, String userid, String status);
    public int updateOfTitleAndTypeidAndNewsdateAndUseridAndStatus(News news, String title, String typeid, String newsdate, String userid, String status);
    public int updateOfBodyAndTypeidAndNewsdateAndUseridAndStatus(News news, String body, String typeid, String newsdate, String userid, String status);
    public int updateOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndUserid(News news, String newsid, String title, String body, String typeid, String newsdate, String userid);
    public int updateOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndStatus(News news, String newsid, String title, String body, String typeid, String newsdate, String status);
    public int updateOfNewsidAndTitleAndBodyAndTypeidAndUseridAndStatus(News news, String newsid, String title, String body, String typeid, String userid, String status);
    public int updateOfNewsidAndTitleAndBodyAndNewsdateAndUseridAndStatus(News news, String newsid, String title, String body, String newsdate, String userid, String status);
    public int updateOfNewsidAndTitleAndTypeidAndNewsdateAndUseridAndStatus(News news, String newsid, String title, String typeid, String newsdate, String userid, String status);
    public int updateOfNewsidAndBodyAndTypeidAndNewsdateAndUseridAndStatus(News news, String newsid, String body, String typeid, String newsdate, String userid, String status);
    public int updateOfTitleAndBodyAndTypeidAndNewsdateAndUseridAndStatus(News news, String title, String body, String typeid, String newsdate, String userid, String status);
    public int updateOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndUseridAndStatus(News news, String newsid, String title, String body, String typeid, String newsdate, String userid, String status);
    public int remove(News news);
    public int removeOfNewsid(String newsid);
    public int removeOfTitle(String title);
    public int removeOfBody(String body);
    public int removeOfTypeid(String typeid);
    public int removeOfNewsdate(String newsdate);
    public int removeOfUserid(String userid);
    public int removeOfStatus(String status);
    public int removeOfNewsidAndTitle(String newsid, String title);
    public int removeOfNewsidAndBody(String newsid, String body);
    public int removeOfNewsidAndTypeid(String newsid, String typeid);
    public int removeOfNewsidAndNewsdate(String newsid, String newsdate);
    public int removeOfNewsidAndUserid(String newsid, String userid);
    public int removeOfNewsidAndStatus(String newsid, String status);
    public int removeOfTitleAndBody(String title, String body);
    public int removeOfTitleAndTypeid(String title, String typeid);
    public int removeOfTitleAndNewsdate(String title, String newsdate);
    public int removeOfTitleAndUserid(String title, String userid);
    public int removeOfTitleAndStatus(String title, String status);
    public int removeOfBodyAndTypeid(String body, String typeid);
    public int removeOfBodyAndNewsdate(String body, String newsdate);
    public int removeOfBodyAndUserid(String body, String userid);
    public int removeOfBodyAndStatus(String body, String status);
    public int removeOfTypeidAndNewsdate(String typeid, String newsdate);
    public int removeOfTypeidAndUserid(String typeid, String userid);
    public int removeOfTypeidAndStatus(String typeid, String status);
    public int removeOfNewsdateAndUserid(String newsdate, String userid);
    public int removeOfNewsdateAndStatus(String newsdate, String status);
    public int removeOfUseridAndStatus(String userid, String status);
    public int removeOfNewsidAndTitleAndBody(String newsid, String title, String body);
    public int removeOfNewsidAndTitleAndTypeid(String newsid, String title, String typeid);
    public int removeOfNewsidAndTitleAndNewsdate(String newsid, String title, String newsdate);
    public int removeOfNewsidAndTitleAndUserid(String newsid, String title, String userid);
    public int removeOfNewsidAndTitleAndStatus(String newsid, String title, String status);
    public int removeOfNewsidAndBodyAndTypeid(String newsid, String body, String typeid);
    public int removeOfNewsidAndBodyAndNewsdate(String newsid, String body, String newsdate);
    public int removeOfNewsidAndBodyAndUserid(String newsid, String body, String userid);
    public int removeOfNewsidAndBodyAndStatus(String newsid, String body, String status);
    public int removeOfNewsidAndTypeidAndNewsdate(String newsid, String typeid, String newsdate);
    public int removeOfNewsidAndTypeidAndUserid(String newsid, String typeid, String userid);
    public int removeOfNewsidAndTypeidAndStatus(String newsid, String typeid, String status);
    public int removeOfNewsidAndNewsdateAndUserid(String newsid, String newsdate, String userid);
    public int removeOfNewsidAndNewsdateAndStatus(String newsid, String newsdate, String status);
    public int removeOfNewsidAndUseridAndStatus(String newsid, String userid, String status);
    public int removeOfTitleAndBodyAndTypeid(String title, String body, String typeid);
    public int removeOfTitleAndBodyAndNewsdate(String title, String body, String newsdate);
    public int removeOfTitleAndBodyAndUserid(String title, String body, String userid);
    public int removeOfTitleAndBodyAndStatus(String title, String body, String status);
    public int removeOfTitleAndTypeidAndNewsdate(String title, String typeid, String newsdate);
    public int removeOfTitleAndTypeidAndUserid(String title, String typeid, String userid);
    public int removeOfTitleAndTypeidAndStatus(String title, String typeid, String status);
    public int removeOfTitleAndNewsdateAndUserid(String title, String newsdate, String userid);
    public int removeOfTitleAndNewsdateAndStatus(String title, String newsdate, String status);
    public int removeOfTitleAndUseridAndStatus(String title, String userid, String status);
    public int removeOfBodyAndTypeidAndNewsdate(String body, String typeid, String newsdate);
    public int removeOfBodyAndTypeidAndUserid(String body, String typeid, String userid);
    public int removeOfBodyAndTypeidAndStatus(String body, String typeid, String status);
    public int removeOfBodyAndNewsdateAndUserid(String body, String newsdate, String userid);
    public int removeOfBodyAndNewsdateAndStatus(String body, String newsdate, String status);
    public int removeOfBodyAndUseridAndStatus(String body, String userid, String status);
    public int removeOfTypeidAndNewsdateAndUserid(String typeid, String newsdate, String userid);
    public int removeOfTypeidAndNewsdateAndStatus(String typeid, String newsdate, String status);
    public int removeOfTypeidAndUseridAndStatus(String typeid, String userid, String status);
    public int removeOfNewsdateAndUseridAndStatus(String newsdate, String userid, String status);
    public int removeOfNewsidAndTitleAndBodyAndTypeid(String newsid, String title, String body, String typeid);
    public int removeOfNewsidAndTitleAndBodyAndNewsdate(String newsid, String title, String body, String newsdate);
    public int removeOfNewsidAndTitleAndBodyAndUserid(String newsid, String title, String body, String userid);
    public int removeOfNewsidAndTitleAndBodyAndStatus(String newsid, String title, String body, String status);
    public int removeOfNewsidAndTitleAndTypeidAndNewsdate(String newsid, String title, String typeid, String newsdate);
    public int removeOfNewsidAndTitleAndTypeidAndUserid(String newsid, String title, String typeid, String userid);
    public int removeOfNewsidAndTitleAndTypeidAndStatus(String newsid, String title, String typeid, String status);
    public int removeOfNewsidAndTitleAndNewsdateAndUserid(String newsid, String title, String newsdate, String userid);
    public int removeOfNewsidAndTitleAndNewsdateAndStatus(String newsid, String title, String newsdate, String status);
    public int removeOfNewsidAndTitleAndUseridAndStatus(String newsid, String title, String userid, String status);
    public int removeOfNewsidAndBodyAndTypeidAndNewsdate(String newsid, String body, String typeid, String newsdate);
    public int removeOfNewsidAndBodyAndTypeidAndUserid(String newsid, String body, String typeid, String userid);
    public int removeOfNewsidAndBodyAndTypeidAndStatus(String newsid, String body, String typeid, String status);
    public int removeOfNewsidAndBodyAndNewsdateAndUserid(String newsid, String body, String newsdate, String userid);
    public int removeOfNewsidAndBodyAndNewsdateAndStatus(String newsid, String body, String newsdate, String status);
    public int removeOfNewsidAndBodyAndUseridAndStatus(String newsid, String body, String userid, String status);
    public int removeOfNewsidAndTypeidAndNewsdateAndUserid(String newsid, String typeid, String newsdate, String userid);
    public int removeOfNewsidAndTypeidAndNewsdateAndStatus(String newsid, String typeid, String newsdate, String status);
    public int removeOfNewsidAndTypeidAndUseridAndStatus(String newsid, String typeid, String userid, String status);
    public int removeOfNewsidAndNewsdateAndUseridAndStatus(String newsid, String newsdate, String userid, String status);
    public int removeOfTitleAndBodyAndTypeidAndNewsdate(String title, String body, String typeid, String newsdate);
    public int removeOfTitleAndBodyAndTypeidAndUserid(String title, String body, String typeid, String userid);
    public int removeOfTitleAndBodyAndTypeidAndStatus(String title, String body, String typeid, String status);
    public int removeOfTitleAndBodyAndNewsdateAndUserid(String title, String body, String newsdate, String userid);
    public int removeOfTitleAndBodyAndNewsdateAndStatus(String title, String body, String newsdate, String status);
    public int removeOfTitleAndBodyAndUseridAndStatus(String title, String body, String userid, String status);
    public int removeOfTitleAndTypeidAndNewsdateAndUserid(String title, String typeid, String newsdate, String userid);
    public int removeOfTitleAndTypeidAndNewsdateAndStatus(String title, String typeid, String newsdate, String status);
    public int removeOfTitleAndTypeidAndUseridAndStatus(String title, String typeid, String userid, String status);
    public int removeOfTitleAndNewsdateAndUseridAndStatus(String title, String newsdate, String userid, String status);
    public int removeOfBodyAndTypeidAndNewsdateAndUserid(String body, String typeid, String newsdate, String userid);
    public int removeOfBodyAndTypeidAndNewsdateAndStatus(String body, String typeid, String newsdate, String status);
    public int removeOfBodyAndTypeidAndUseridAndStatus(String body, String typeid, String userid, String status);
    public int removeOfBodyAndNewsdateAndUseridAndStatus(String body, String newsdate, String userid, String status);
    public int removeOfTypeidAndNewsdateAndUseridAndStatus(String typeid, String newsdate, String userid, String status);
    public int removeOfNewsidAndTitleAndBodyAndTypeidAndNewsdate(String newsid, String title, String body, String typeid, String newsdate);
    public int removeOfNewsidAndTitleAndBodyAndTypeidAndUserid(String newsid, String title, String body, String typeid, String userid);
    public int removeOfNewsidAndTitleAndBodyAndTypeidAndStatus(String newsid, String title, String body, String typeid, String status);
    public int removeOfNewsidAndTitleAndBodyAndNewsdateAndUserid(String newsid, String title, String body, String newsdate, String userid);
    public int removeOfNewsidAndTitleAndBodyAndNewsdateAndStatus(String newsid, String title, String body, String newsdate, String status);
    public int removeOfNewsidAndTitleAndBodyAndUseridAndStatus(String newsid, String title, String body, String userid, String status);
    public int removeOfNewsidAndTitleAndTypeidAndNewsdateAndUserid(String newsid, String title, String typeid, String newsdate, String userid);
    public int removeOfNewsidAndTitleAndTypeidAndNewsdateAndStatus(String newsid, String title, String typeid, String newsdate, String status);
    public int removeOfNewsidAndTitleAndTypeidAndUseridAndStatus(String newsid, String title, String typeid, String userid, String status);
    public int removeOfNewsidAndTitleAndNewsdateAndUseridAndStatus(String newsid, String title, String newsdate, String userid, String status);
    public int removeOfNewsidAndBodyAndTypeidAndNewsdateAndUserid(String newsid, String body, String typeid, String newsdate, String userid);
    public int removeOfNewsidAndBodyAndTypeidAndNewsdateAndStatus(String newsid, String body, String typeid, String newsdate, String status);
    public int removeOfNewsidAndBodyAndTypeidAndUseridAndStatus(String newsid, String body, String typeid, String userid, String status);
    public int removeOfNewsidAndBodyAndNewsdateAndUseridAndStatus(String newsid, String body, String newsdate, String userid, String status);
    public int removeOfNewsidAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String typeid, String newsdate, String userid, String status);
    public int removeOfTitleAndBodyAndTypeidAndNewsdateAndUserid(String title, String body, String typeid, String newsdate, String userid);
    public int removeOfTitleAndBodyAndTypeidAndNewsdateAndStatus(String title, String body, String typeid, String newsdate, String status);
    public int removeOfTitleAndBodyAndTypeidAndUseridAndStatus(String title, String body, String typeid, String userid, String status);
    public int removeOfTitleAndBodyAndNewsdateAndUseridAndStatus(String title, String body, String newsdate, String userid, String status);
    public int removeOfTitleAndTypeidAndNewsdateAndUseridAndStatus(String title, String typeid, String newsdate, String userid, String status);
    public int removeOfBodyAndTypeidAndNewsdateAndUseridAndStatus(String body, String typeid, String newsdate, String userid, String status);
    public int removeOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndUserid(String newsid, String title, String body, String typeid, String newsdate, String userid);
    public int removeOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndStatus(String newsid, String title, String body, String typeid, String newsdate, String status);
    public int removeOfNewsidAndTitleAndBodyAndTypeidAndUseridAndStatus(String newsid, String title, String body, String typeid, String userid, String status);
    public int removeOfNewsidAndTitleAndBodyAndNewsdateAndUseridAndStatus(String newsid, String title, String body, String newsdate, String userid, String status);
    public int removeOfNewsidAndTitleAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String title, String typeid, String newsdate, String userid, String status);
    public int removeOfNewsidAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String body, String typeid, String newsdate, String userid, String status);
    public int removeOfTitleAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String title, String body, String typeid, String newsdate, String userid, String status);
    public int removeOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String title, String body, String typeid, String newsdate, String userid, String status);
    public int insert(News news);
    public int insertOfNewsid(String newsid);
    public int insertOfTitle(String title);
    public int insertOfBody(String body);
    public int insertOfTypeid(String typeid);
    public int insertOfNewsdate(String newsdate);
    public int insertOfUserid(String userid);
    public int insertOfStatus(String status);
    public int insertOfNewsidAndTitle(String newsid, String title);
    public int insertOfNewsidAndBody(String newsid, String body);
    public int insertOfNewsidAndTypeid(String newsid, String typeid);
    public int insertOfNewsidAndNewsdate(String newsid, String newsdate);
    public int insertOfNewsidAndUserid(String newsid, String userid);
    public int insertOfNewsidAndStatus(String newsid, String status);
    public int insertOfTitleAndBody(String title, String body);
    public int insertOfTitleAndTypeid(String title, String typeid);
    public int insertOfTitleAndNewsdate(String title, String newsdate);
    public int insertOfTitleAndUserid(String title, String userid);
    public int insertOfTitleAndStatus(String title, String status);
    public int insertOfBodyAndTypeid(String body, String typeid);
    public int insertOfBodyAndNewsdate(String body, String newsdate);
    public int insertOfBodyAndUserid(String body, String userid);
    public int insertOfBodyAndStatus(String body, String status);
    public int insertOfTypeidAndNewsdate(String typeid, String newsdate);
    public int insertOfTypeidAndUserid(String typeid, String userid);
    public int insertOfTypeidAndStatus(String typeid, String status);
    public int insertOfNewsdateAndUserid(String newsdate, String userid);
    public int insertOfNewsdateAndStatus(String newsdate, String status);
    public int insertOfUseridAndStatus(String userid, String status);
    public int insertOfNewsidAndTitleAndBody(String newsid, String title, String body);
    public int insertOfNewsidAndTitleAndTypeid(String newsid, String title, String typeid);
    public int insertOfNewsidAndTitleAndNewsdate(String newsid, String title, String newsdate);
    public int insertOfNewsidAndTitleAndUserid(String newsid, String title, String userid);
    public int insertOfNewsidAndTitleAndStatus(String newsid, String title, String status);
    public int insertOfNewsidAndBodyAndTypeid(String newsid, String body, String typeid);
    public int insertOfNewsidAndBodyAndNewsdate(String newsid, String body, String newsdate);
    public int insertOfNewsidAndBodyAndUserid(String newsid, String body, String userid);
    public int insertOfNewsidAndBodyAndStatus(String newsid, String body, String status);
    public int insertOfNewsidAndTypeidAndNewsdate(String newsid, String typeid, String newsdate);
    public int insertOfNewsidAndTypeidAndUserid(String newsid, String typeid, String userid);
    public int insertOfNewsidAndTypeidAndStatus(String newsid, String typeid, String status);
    public int insertOfNewsidAndNewsdateAndUserid(String newsid, String newsdate, String userid);
    public int insertOfNewsidAndNewsdateAndStatus(String newsid, String newsdate, String status);
    public int insertOfNewsidAndUseridAndStatus(String newsid, String userid, String status);
    public int insertOfTitleAndBodyAndTypeid(String title, String body, String typeid);
    public int insertOfTitleAndBodyAndNewsdate(String title, String body, String newsdate);
    public int insertOfTitleAndBodyAndUserid(String title, String body, String userid);
    public int insertOfTitleAndBodyAndStatus(String title, String body, String status);
    public int insertOfTitleAndTypeidAndNewsdate(String title, String typeid, String newsdate);
    public int insertOfTitleAndTypeidAndUserid(String title, String typeid, String userid);
    public int insertOfTitleAndTypeidAndStatus(String title, String typeid, String status);
    public int insertOfTitleAndNewsdateAndUserid(String title, String newsdate, String userid);
    public int insertOfTitleAndNewsdateAndStatus(String title, String newsdate, String status);
    public int insertOfTitleAndUseridAndStatus(String title, String userid, String status);
    public int insertOfBodyAndTypeidAndNewsdate(String body, String typeid, String newsdate);
    public int insertOfBodyAndTypeidAndUserid(String body, String typeid, String userid);
    public int insertOfBodyAndTypeidAndStatus(String body, String typeid, String status);
    public int insertOfBodyAndNewsdateAndUserid(String body, String newsdate, String userid);
    public int insertOfBodyAndNewsdateAndStatus(String body, String newsdate, String status);
    public int insertOfBodyAndUseridAndStatus(String body, String userid, String status);
    public int insertOfTypeidAndNewsdateAndUserid(String typeid, String newsdate, String userid);
    public int insertOfTypeidAndNewsdateAndStatus(String typeid, String newsdate, String status);
    public int insertOfTypeidAndUseridAndStatus(String typeid, String userid, String status);
    public int insertOfNewsdateAndUseridAndStatus(String newsdate, String userid, String status);
    public int insertOfNewsidAndTitleAndBodyAndTypeid(String newsid, String title, String body, String typeid);
    public int insertOfNewsidAndTitleAndBodyAndNewsdate(String newsid, String title, String body, String newsdate);
    public int insertOfNewsidAndTitleAndBodyAndUserid(String newsid, String title, String body, String userid);
    public int insertOfNewsidAndTitleAndBodyAndStatus(String newsid, String title, String body, String status);
    public int insertOfNewsidAndTitleAndTypeidAndNewsdate(String newsid, String title, String typeid, String newsdate);
    public int insertOfNewsidAndTitleAndTypeidAndUserid(String newsid, String title, String typeid, String userid);
    public int insertOfNewsidAndTitleAndTypeidAndStatus(String newsid, String title, String typeid, String status);
    public int insertOfNewsidAndTitleAndNewsdateAndUserid(String newsid, String title, String newsdate, String userid);
    public int insertOfNewsidAndTitleAndNewsdateAndStatus(String newsid, String title, String newsdate, String status);
    public int insertOfNewsidAndTitleAndUseridAndStatus(String newsid, String title, String userid, String status);
    public int insertOfNewsidAndBodyAndTypeidAndNewsdate(String newsid, String body, String typeid, String newsdate);
    public int insertOfNewsidAndBodyAndTypeidAndUserid(String newsid, String body, String typeid, String userid);
    public int insertOfNewsidAndBodyAndTypeidAndStatus(String newsid, String body, String typeid, String status);
    public int insertOfNewsidAndBodyAndNewsdateAndUserid(String newsid, String body, String newsdate, String userid);
    public int insertOfNewsidAndBodyAndNewsdateAndStatus(String newsid, String body, String newsdate, String status);
    public int insertOfNewsidAndBodyAndUseridAndStatus(String newsid, String body, String userid, String status);
    public int insertOfNewsidAndTypeidAndNewsdateAndUserid(String newsid, String typeid, String newsdate, String userid);
    public int insertOfNewsidAndTypeidAndNewsdateAndStatus(String newsid, String typeid, String newsdate, String status);
    public int insertOfNewsidAndTypeidAndUseridAndStatus(String newsid, String typeid, String userid, String status);
    public int insertOfNewsidAndNewsdateAndUseridAndStatus(String newsid, String newsdate, String userid, String status);
    public int insertOfTitleAndBodyAndTypeidAndNewsdate(String title, String body, String typeid, String newsdate);
    public int insertOfTitleAndBodyAndTypeidAndUserid(String title, String body, String typeid, String userid);
    public int insertOfTitleAndBodyAndTypeidAndStatus(String title, String body, String typeid, String status);
    public int insertOfTitleAndBodyAndNewsdateAndUserid(String title, String body, String newsdate, String userid);
    public int insertOfTitleAndBodyAndNewsdateAndStatus(String title, String body, String newsdate, String status);
    public int insertOfTitleAndBodyAndUseridAndStatus(String title, String body, String userid, String status);
    public int insertOfTitleAndTypeidAndNewsdateAndUserid(String title, String typeid, String newsdate, String userid);
    public int insertOfTitleAndTypeidAndNewsdateAndStatus(String title, String typeid, String newsdate, String status);
    public int insertOfTitleAndTypeidAndUseridAndStatus(String title, String typeid, String userid, String status);
    public int insertOfTitleAndNewsdateAndUseridAndStatus(String title, String newsdate, String userid, String status);
    public int insertOfBodyAndTypeidAndNewsdateAndUserid(String body, String typeid, String newsdate, String userid);
    public int insertOfBodyAndTypeidAndNewsdateAndStatus(String body, String typeid, String newsdate, String status);
    public int insertOfBodyAndTypeidAndUseridAndStatus(String body, String typeid, String userid, String status);
    public int insertOfBodyAndNewsdateAndUseridAndStatus(String body, String newsdate, String userid, String status);
    public int insertOfTypeidAndNewsdateAndUseridAndStatus(String typeid, String newsdate, String userid, String status);
    public int insertOfNewsidAndTitleAndBodyAndTypeidAndNewsdate(String newsid, String title, String body, String typeid, String newsdate);
    public int insertOfNewsidAndTitleAndBodyAndTypeidAndUserid(String newsid, String title, String body, String typeid, String userid);
    public int insertOfNewsidAndTitleAndBodyAndTypeidAndStatus(String newsid, String title, String body, String typeid, String status);
    public int insertOfNewsidAndTitleAndBodyAndNewsdateAndUserid(String newsid, String title, String body, String newsdate, String userid);
    public int insertOfNewsidAndTitleAndBodyAndNewsdateAndStatus(String newsid, String title, String body, String newsdate, String status);
    public int insertOfNewsidAndTitleAndBodyAndUseridAndStatus(String newsid, String title, String body, String userid, String status);
    public int insertOfNewsidAndTitleAndTypeidAndNewsdateAndUserid(String newsid, String title, String typeid, String newsdate, String userid);
    public int insertOfNewsidAndTitleAndTypeidAndNewsdateAndStatus(String newsid, String title, String typeid, String newsdate, String status);
    public int insertOfNewsidAndTitleAndTypeidAndUseridAndStatus(String newsid, String title, String typeid, String userid, String status);
    public int insertOfNewsidAndTitleAndNewsdateAndUseridAndStatus(String newsid, String title, String newsdate, String userid, String status);
    public int insertOfNewsidAndBodyAndTypeidAndNewsdateAndUserid(String newsid, String body, String typeid, String newsdate, String userid);
    public int insertOfNewsidAndBodyAndTypeidAndNewsdateAndStatus(String newsid, String body, String typeid, String newsdate, String status);
    public int insertOfNewsidAndBodyAndTypeidAndUseridAndStatus(String newsid, String body, String typeid, String userid, String status);
    public int insertOfNewsidAndBodyAndNewsdateAndUseridAndStatus(String newsid, String body, String newsdate, String userid, String status);
    public int insertOfNewsidAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String typeid, String newsdate, String userid, String status);
    public int insertOfTitleAndBodyAndTypeidAndNewsdateAndUserid(String title, String body, String typeid, String newsdate, String userid);
    public int insertOfTitleAndBodyAndTypeidAndNewsdateAndStatus(String title, String body, String typeid, String newsdate, String status);
    public int insertOfTitleAndBodyAndTypeidAndUseridAndStatus(String title, String body, String typeid, String userid, String status);
    public int insertOfTitleAndBodyAndNewsdateAndUseridAndStatus(String title, String body, String newsdate, String userid, String status);
    public int insertOfTitleAndTypeidAndNewsdateAndUseridAndStatus(String title, String typeid, String newsdate, String userid, String status);
    public int insertOfBodyAndTypeidAndNewsdateAndUseridAndStatus(String body, String typeid, String newsdate, String userid, String status);
    public int insertOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndUserid(String newsid, String title, String body, String typeid, String newsdate, String userid);
    public int insertOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndStatus(String newsid, String title, String body, String typeid, String newsdate, String status);
    public int insertOfNewsidAndTitleAndBodyAndTypeidAndUseridAndStatus(String newsid, String title, String body, String typeid, String userid, String status);
    public int insertOfNewsidAndTitleAndBodyAndNewsdateAndUseridAndStatus(String newsid, String title, String body, String newsdate, String userid, String status);
    public int insertOfNewsidAndTitleAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String title, String typeid, String newsdate, String userid, String status);
    public int insertOfNewsidAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String body, String typeid, String newsdate, String userid, String status);
    public int insertOfTitleAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String title, String body, String typeid, String newsdate, String userid, String status);
    public int insertOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String title, String body, String typeid, String newsdate, String userid, String status);
    public News getNews(News news);
    public News getNewsOfNewsid(String newsid);
    public News getNewsOfTitle(String title);
    public News getNewsOfBody(String body);
    public News getNewsOfTypeid(String typeid);
    public News getNewsOfNewsdate(String newsdate);
    public News getNewsOfUserid(String userid);
    public News getNewsOfStatus(String status);
    public News getNewsOfNewsidAndTitle(String newsid, String title);
    public News getNewsOfNewsidAndBody(String newsid, String body);
    public News getNewsOfNewsidAndTypeid(String newsid, String typeid);
    public News getNewsOfNewsidAndNewsdate(String newsid, String newsdate);
    public News getNewsOfNewsidAndUserid(String newsid, String userid);
    public News getNewsOfNewsidAndStatus(String newsid, String status);
    public News getNewsOfTitleAndBody(String title, String body);
    public News getNewsOfTitleAndTypeid(String title, String typeid);
    public News getNewsOfTitleAndNewsdate(String title, String newsdate);
    public News getNewsOfTitleAndUserid(String title, String userid);
    public News getNewsOfTitleAndStatus(String title, String status);
    public News getNewsOfBodyAndTypeid(String body, String typeid);
    public News getNewsOfBodyAndNewsdate(String body, String newsdate);
    public News getNewsOfBodyAndUserid(String body, String userid);
    public News getNewsOfBodyAndStatus(String body, String status);
    public News getNewsOfTypeidAndNewsdate(String typeid, String newsdate);
    public News getNewsOfTypeidAndUserid(String typeid, String userid);
    public News getNewsOfTypeidAndStatus(String typeid, String status);
    public News getNewsOfNewsdateAndUserid(String newsdate, String userid);
    public News getNewsOfNewsdateAndStatus(String newsdate, String status);
    public News getNewsOfUseridAndStatus(String userid, String status);
    public News getNewsOfNewsidAndTitleAndBody(String newsid, String title, String body);
    public News getNewsOfNewsidAndTitleAndTypeid(String newsid, String title, String typeid);
    public News getNewsOfNewsidAndTitleAndNewsdate(String newsid, String title, String newsdate);
    public News getNewsOfNewsidAndTitleAndUserid(String newsid, String title, String userid);
    public News getNewsOfNewsidAndTitleAndStatus(String newsid, String title, String status);
    public News getNewsOfNewsidAndBodyAndTypeid(String newsid, String body, String typeid);
    public News getNewsOfNewsidAndBodyAndNewsdate(String newsid, String body, String newsdate);
    public News getNewsOfNewsidAndBodyAndUserid(String newsid, String body, String userid);
    public News getNewsOfNewsidAndBodyAndStatus(String newsid, String body, String status);
    public News getNewsOfNewsidAndTypeidAndNewsdate(String newsid, String typeid, String newsdate);
    public News getNewsOfNewsidAndTypeidAndUserid(String newsid, String typeid, String userid);
    public News getNewsOfNewsidAndTypeidAndStatus(String newsid, String typeid, String status);
    public News getNewsOfNewsidAndNewsdateAndUserid(String newsid, String newsdate, String userid);
    public News getNewsOfNewsidAndNewsdateAndStatus(String newsid, String newsdate, String status);
    public News getNewsOfNewsidAndUseridAndStatus(String newsid, String userid, String status);
    public News getNewsOfTitleAndBodyAndTypeid(String title, String body, String typeid);
    public News getNewsOfTitleAndBodyAndNewsdate(String title, String body, String newsdate);
    public News getNewsOfTitleAndBodyAndUserid(String title, String body, String userid);
    public News getNewsOfTitleAndBodyAndStatus(String title, String body, String status);
    public News getNewsOfTitleAndTypeidAndNewsdate(String title, String typeid, String newsdate);
    public News getNewsOfTitleAndTypeidAndUserid(String title, String typeid, String userid);
    public News getNewsOfTitleAndTypeidAndStatus(String title, String typeid, String status);
    public News getNewsOfTitleAndNewsdateAndUserid(String title, String newsdate, String userid);
    public News getNewsOfTitleAndNewsdateAndStatus(String title, String newsdate, String status);
    public News getNewsOfTitleAndUseridAndStatus(String title, String userid, String status);
    public News getNewsOfBodyAndTypeidAndNewsdate(String body, String typeid, String newsdate);
    public News getNewsOfBodyAndTypeidAndUserid(String body, String typeid, String userid);
    public News getNewsOfBodyAndTypeidAndStatus(String body, String typeid, String status);
    public News getNewsOfBodyAndNewsdateAndUserid(String body, String newsdate, String userid);
    public News getNewsOfBodyAndNewsdateAndStatus(String body, String newsdate, String status);
    public News getNewsOfBodyAndUseridAndStatus(String body, String userid, String status);
    public News getNewsOfTypeidAndNewsdateAndUserid(String typeid, String newsdate, String userid);
    public News getNewsOfTypeidAndNewsdateAndStatus(String typeid, String newsdate, String status);
    public News getNewsOfTypeidAndUseridAndStatus(String typeid, String userid, String status);
    public News getNewsOfNewsdateAndUseridAndStatus(String newsdate, String userid, String status);
    public News getNewsOfNewsidAndTitleAndBodyAndTypeid(String newsid, String title, String body, String typeid);
    public News getNewsOfNewsidAndTitleAndBodyAndNewsdate(String newsid, String title, String body, String newsdate);
    public News getNewsOfNewsidAndTitleAndBodyAndUserid(String newsid, String title, String body, String userid);
    public News getNewsOfNewsidAndTitleAndBodyAndStatus(String newsid, String title, String body, String status);
    public News getNewsOfNewsidAndTitleAndTypeidAndNewsdate(String newsid, String title, String typeid, String newsdate);
    public News getNewsOfNewsidAndTitleAndTypeidAndUserid(String newsid, String title, String typeid, String userid);
    public News getNewsOfNewsidAndTitleAndTypeidAndStatus(String newsid, String title, String typeid, String status);
    public News getNewsOfNewsidAndTitleAndNewsdateAndUserid(String newsid, String title, String newsdate, String userid);
    public News getNewsOfNewsidAndTitleAndNewsdateAndStatus(String newsid, String title, String newsdate, String status);
    public News getNewsOfNewsidAndTitleAndUseridAndStatus(String newsid, String title, String userid, String status);
    public News getNewsOfNewsidAndBodyAndTypeidAndNewsdate(String newsid, String body, String typeid, String newsdate);
    public News getNewsOfNewsidAndBodyAndTypeidAndUserid(String newsid, String body, String typeid, String userid);
    public News getNewsOfNewsidAndBodyAndTypeidAndStatus(String newsid, String body, String typeid, String status);
    public News getNewsOfNewsidAndBodyAndNewsdateAndUserid(String newsid, String body, String newsdate, String userid);
    public News getNewsOfNewsidAndBodyAndNewsdateAndStatus(String newsid, String body, String newsdate, String status);
    public News getNewsOfNewsidAndBodyAndUseridAndStatus(String newsid, String body, String userid, String status);
    public News getNewsOfNewsidAndTypeidAndNewsdateAndUserid(String newsid, String typeid, String newsdate, String userid);
    public News getNewsOfNewsidAndTypeidAndNewsdateAndStatus(String newsid, String typeid, String newsdate, String status);
    public News getNewsOfNewsidAndTypeidAndUseridAndStatus(String newsid, String typeid, String userid, String status);
    public News getNewsOfNewsidAndNewsdateAndUseridAndStatus(String newsid, String newsdate, String userid, String status);
    public News getNewsOfTitleAndBodyAndTypeidAndNewsdate(String title, String body, String typeid, String newsdate);
    public News getNewsOfTitleAndBodyAndTypeidAndUserid(String title, String body, String typeid, String userid);
    public News getNewsOfTitleAndBodyAndTypeidAndStatus(String title, String body, String typeid, String status);
    public News getNewsOfTitleAndBodyAndNewsdateAndUserid(String title, String body, String newsdate, String userid);
    public News getNewsOfTitleAndBodyAndNewsdateAndStatus(String title, String body, String newsdate, String status);
    public News getNewsOfTitleAndBodyAndUseridAndStatus(String title, String body, String userid, String status);
    public News getNewsOfTitleAndTypeidAndNewsdateAndUserid(String title, String typeid, String newsdate, String userid);
    public News getNewsOfTitleAndTypeidAndNewsdateAndStatus(String title, String typeid, String newsdate, String status);
    public News getNewsOfTitleAndTypeidAndUseridAndStatus(String title, String typeid, String userid, String status);
    public News getNewsOfTitleAndNewsdateAndUseridAndStatus(String title, String newsdate, String userid, String status);
    public News getNewsOfBodyAndTypeidAndNewsdateAndUserid(String body, String typeid, String newsdate, String userid);
    public News getNewsOfBodyAndTypeidAndNewsdateAndStatus(String body, String typeid, String newsdate, String status);
    public News getNewsOfBodyAndTypeidAndUseridAndStatus(String body, String typeid, String userid, String status);
    public News getNewsOfBodyAndNewsdateAndUseridAndStatus(String body, String newsdate, String userid, String status);
    public News getNewsOfTypeidAndNewsdateAndUseridAndStatus(String typeid, String newsdate, String userid, String status);
    public News getNewsOfNewsidAndTitleAndBodyAndTypeidAndNewsdate(String newsid, String title, String body, String typeid, String newsdate);
    public News getNewsOfNewsidAndTitleAndBodyAndTypeidAndUserid(String newsid, String title, String body, String typeid, String userid);
    public News getNewsOfNewsidAndTitleAndBodyAndTypeidAndStatus(String newsid, String title, String body, String typeid, String status);
    public News getNewsOfNewsidAndTitleAndBodyAndNewsdateAndUserid(String newsid, String title, String body, String newsdate, String userid);
    public News getNewsOfNewsidAndTitleAndBodyAndNewsdateAndStatus(String newsid, String title, String body, String newsdate, String status);
    public News getNewsOfNewsidAndTitleAndBodyAndUseridAndStatus(String newsid, String title, String body, String userid, String status);
    public News getNewsOfNewsidAndTitleAndTypeidAndNewsdateAndUserid(String newsid, String title, String typeid, String newsdate, String userid);
    public News getNewsOfNewsidAndTitleAndTypeidAndNewsdateAndStatus(String newsid, String title, String typeid, String newsdate, String status);
    public News getNewsOfNewsidAndTitleAndTypeidAndUseridAndStatus(String newsid, String title, String typeid, String userid, String status);
    public News getNewsOfNewsidAndTitleAndNewsdateAndUseridAndStatus(String newsid, String title, String newsdate, String userid, String status);
    public News getNewsOfNewsidAndBodyAndTypeidAndNewsdateAndUserid(String newsid, String body, String typeid, String newsdate, String userid);
    public News getNewsOfNewsidAndBodyAndTypeidAndNewsdateAndStatus(String newsid, String body, String typeid, String newsdate, String status);
    public News getNewsOfNewsidAndBodyAndTypeidAndUseridAndStatus(String newsid, String body, String typeid, String userid, String status);
    public News getNewsOfNewsidAndBodyAndNewsdateAndUseridAndStatus(String newsid, String body, String newsdate, String userid, String status);
    public News getNewsOfNewsidAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String typeid, String newsdate, String userid, String status);
    public News getNewsOfTitleAndBodyAndTypeidAndNewsdateAndUserid(String title, String body, String typeid, String newsdate, String userid);
    public News getNewsOfTitleAndBodyAndTypeidAndNewsdateAndStatus(String title, String body, String typeid, String newsdate, String status);
    public News getNewsOfTitleAndBodyAndTypeidAndUseridAndStatus(String title, String body, String typeid, String userid, String status);
    public News getNewsOfTitleAndBodyAndNewsdateAndUseridAndStatus(String title, String body, String newsdate, String userid, String status);
    public News getNewsOfTitleAndTypeidAndNewsdateAndUseridAndStatus(String title, String typeid, String newsdate, String userid, String status);
    public News getNewsOfBodyAndTypeidAndNewsdateAndUseridAndStatus(String body, String typeid, String newsdate, String userid, String status);
    public News getNewsOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndUserid(String newsid, String title, String body, String typeid, String newsdate, String userid);
    public News getNewsOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndStatus(String newsid, String title, String body, String typeid, String newsdate, String status);
    public News getNewsOfNewsidAndTitleAndBodyAndTypeidAndUseridAndStatus(String newsid, String title, String body, String typeid, String userid, String status);
    public News getNewsOfNewsidAndTitleAndBodyAndNewsdateAndUseridAndStatus(String newsid, String title, String body, String newsdate, String userid, String status);
    public News getNewsOfNewsidAndTitleAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String title, String typeid, String newsdate, String userid, String status);
    public News getNewsOfNewsidAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String body, String typeid, String newsdate, String userid, String status);
    public News getNewsOfTitleAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String title, String body, String typeid, String newsdate, String userid, String status);
    public News getNewsOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String title, String body, String typeid, String newsdate, String userid, String status);
    public List<News> getNewss(News news);
    public List<News> getNewssOfNewsid(String newsid);
    public List<News> getNewssOfTitle(String title);
    public List<News> getNewssOfBody(String body);
    public List<News> getNewssOfTypeid(String typeid);
    public List<News> getNewssOfNewsdate(String newsdate);
    public List<News> getNewssOfUserid(String userid);
    public List<News> getNewssOfStatus(String status);
    public List<News> getNewssOfNewsidAndTitle(String newsid, String title);
    public List<News> getNewssOfNewsidAndBody(String newsid, String body);
    public List<News> getNewssOfNewsidAndTypeid(String newsid, String typeid);
    public List<News> getNewssOfNewsidAndNewsdate(String newsid, String newsdate);
    public List<News> getNewssOfNewsidAndUserid(String newsid, String userid);
    public List<News> getNewssOfNewsidAndStatus(String newsid, String status);
    public List<News> getNewssOfTitleAndBody(String title, String body);
    public List<News> getNewssOfTitleAndTypeid(String title, String typeid);
    public List<News> getNewssOfTitleAndNewsdate(String title, String newsdate);
    public List<News> getNewssOfTitleAndUserid(String title, String userid);
    public List<News> getNewssOfTitleAndStatus(String title, String status);
    public List<News> getNewssOfBodyAndTypeid(String body, String typeid);
    public List<News> getNewssOfBodyAndNewsdate(String body, String newsdate);
    public List<News> getNewssOfBodyAndUserid(String body, String userid);
    public List<News> getNewssOfBodyAndStatus(String body, String status);
    public List<News> getNewssOfTypeidAndNewsdate(String typeid, String newsdate);
    public List<News> getNewssOfTypeidAndUserid(String typeid, String userid);
    public List<News> getNewssOfTypeidAndStatus(String typeid, String status);
    public List<News> getNewssOfNewsdateAndUserid(String newsdate, String userid);
    public List<News> getNewssOfNewsdateAndStatus(String newsdate, String status);
    public List<News> getNewssOfUseridAndStatus(String userid, String status);
    public List<News> getNewssOfNewsidAndTitleAndBody(String newsid, String title, String body);
    public List<News> getNewssOfNewsidAndTitleAndTypeid(String newsid, String title, String typeid);
    public List<News> getNewssOfNewsidAndTitleAndNewsdate(String newsid, String title, String newsdate);
    public List<News> getNewssOfNewsidAndTitleAndUserid(String newsid, String title, String userid);
    public List<News> getNewssOfNewsidAndTitleAndStatus(String newsid, String title, String status);
    public List<News> getNewssOfNewsidAndBodyAndTypeid(String newsid, String body, String typeid);
    public List<News> getNewssOfNewsidAndBodyAndNewsdate(String newsid, String body, String newsdate);
    public List<News> getNewssOfNewsidAndBodyAndUserid(String newsid, String body, String userid);
    public List<News> getNewssOfNewsidAndBodyAndStatus(String newsid, String body, String status);
    public List<News> getNewssOfNewsidAndTypeidAndNewsdate(String newsid, String typeid, String newsdate);
    public List<News> getNewssOfNewsidAndTypeidAndUserid(String newsid, String typeid, String userid);
    public List<News> getNewssOfNewsidAndTypeidAndStatus(String newsid, String typeid, String status);
    public List<News> getNewssOfNewsidAndNewsdateAndUserid(String newsid, String newsdate, String userid);
    public List<News> getNewssOfNewsidAndNewsdateAndStatus(String newsid, String newsdate, String status);
    public List<News> getNewssOfNewsidAndUseridAndStatus(String newsid, String userid, String status);
    public List<News> getNewssOfTitleAndBodyAndTypeid(String title, String body, String typeid);
    public List<News> getNewssOfTitleAndBodyAndNewsdate(String title, String body, String newsdate);
    public List<News> getNewssOfTitleAndBodyAndUserid(String title, String body, String userid);
    public List<News> getNewssOfTitleAndBodyAndStatus(String title, String body, String status);
    public List<News> getNewssOfTitleAndTypeidAndNewsdate(String title, String typeid, String newsdate);
    public List<News> getNewssOfTitleAndTypeidAndUserid(String title, String typeid, String userid);
    public List<News> getNewssOfTitleAndTypeidAndStatus(String title, String typeid, String status);
    public List<News> getNewssOfTitleAndNewsdateAndUserid(String title, String newsdate, String userid);
    public List<News> getNewssOfTitleAndNewsdateAndStatus(String title, String newsdate, String status);
    public List<News> getNewssOfTitleAndUseridAndStatus(String title, String userid, String status);
    public List<News> getNewssOfBodyAndTypeidAndNewsdate(String body, String typeid, String newsdate);
    public List<News> getNewssOfBodyAndTypeidAndUserid(String body, String typeid, String userid);
    public List<News> getNewssOfBodyAndTypeidAndStatus(String body, String typeid, String status);
    public List<News> getNewssOfBodyAndNewsdateAndUserid(String body, String newsdate, String userid);
    public List<News> getNewssOfBodyAndNewsdateAndStatus(String body, String newsdate, String status);
    public List<News> getNewssOfBodyAndUseridAndStatus(String body, String userid, String status);
    public List<News> getNewssOfTypeidAndNewsdateAndUserid(String typeid, String newsdate, String userid);
    public List<News> getNewssOfTypeidAndNewsdateAndStatus(String typeid, String newsdate, String status);
    public List<News> getNewssOfTypeidAndUseridAndStatus(String typeid, String userid, String status);
    public List<News> getNewssOfNewsdateAndUseridAndStatus(String newsdate, String userid, String status);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndTypeid(String newsid, String title, String body, String typeid);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndNewsdate(String newsid, String title, String body, String newsdate);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndUserid(String newsid, String title, String body, String userid);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndStatus(String newsid, String title, String body, String status);
    public List<News> getNewssOfNewsidAndTitleAndTypeidAndNewsdate(String newsid, String title, String typeid, String newsdate);
    public List<News> getNewssOfNewsidAndTitleAndTypeidAndUserid(String newsid, String title, String typeid, String userid);
    public List<News> getNewssOfNewsidAndTitleAndTypeidAndStatus(String newsid, String title, String typeid, String status);
    public List<News> getNewssOfNewsidAndTitleAndNewsdateAndUserid(String newsid, String title, String newsdate, String userid);
    public List<News> getNewssOfNewsidAndTitleAndNewsdateAndStatus(String newsid, String title, String newsdate, String status);
    public List<News> getNewssOfNewsidAndTitleAndUseridAndStatus(String newsid, String title, String userid, String status);
    public List<News> getNewssOfNewsidAndBodyAndTypeidAndNewsdate(String newsid, String body, String typeid, String newsdate);
    public List<News> getNewssOfNewsidAndBodyAndTypeidAndUserid(String newsid, String body, String typeid, String userid);
    public List<News> getNewssOfNewsidAndBodyAndTypeidAndStatus(String newsid, String body, String typeid, String status);
    public List<News> getNewssOfNewsidAndBodyAndNewsdateAndUserid(String newsid, String body, String newsdate, String userid);
    public List<News> getNewssOfNewsidAndBodyAndNewsdateAndStatus(String newsid, String body, String newsdate, String status);
    public List<News> getNewssOfNewsidAndBodyAndUseridAndStatus(String newsid, String body, String userid, String status);
    public List<News> getNewssOfNewsidAndTypeidAndNewsdateAndUserid(String newsid, String typeid, String newsdate, String userid);
    public List<News> getNewssOfNewsidAndTypeidAndNewsdateAndStatus(String newsid, String typeid, String newsdate, String status);
    public List<News> getNewssOfNewsidAndTypeidAndUseridAndStatus(String newsid, String typeid, String userid, String status);
    public List<News> getNewssOfNewsidAndNewsdateAndUseridAndStatus(String newsid, String newsdate, String userid, String status);
    public List<News> getNewssOfTitleAndBodyAndTypeidAndNewsdate(String title, String body, String typeid, String newsdate);
    public List<News> getNewssOfTitleAndBodyAndTypeidAndUserid(String title, String body, String typeid, String userid);
    public List<News> getNewssOfTitleAndBodyAndTypeidAndStatus(String title, String body, String typeid, String status);
    public List<News> getNewssOfTitleAndBodyAndNewsdateAndUserid(String title, String body, String newsdate, String userid);
    public List<News> getNewssOfTitleAndBodyAndNewsdateAndStatus(String title, String body, String newsdate, String status);
    public List<News> getNewssOfTitleAndBodyAndUseridAndStatus(String title, String body, String userid, String status);
    public List<News> getNewssOfTitleAndTypeidAndNewsdateAndUserid(String title, String typeid, String newsdate, String userid);
    public List<News> getNewssOfTitleAndTypeidAndNewsdateAndStatus(String title, String typeid, String newsdate, String status);
    public List<News> getNewssOfTitleAndTypeidAndUseridAndStatus(String title, String typeid, String userid, String status);
    public List<News> getNewssOfTitleAndNewsdateAndUseridAndStatus(String title, String newsdate, String userid, String status);
    public List<News> getNewssOfBodyAndTypeidAndNewsdateAndUserid(String body, String typeid, String newsdate, String userid);
    public List<News> getNewssOfBodyAndTypeidAndNewsdateAndStatus(String body, String typeid, String newsdate, String status);
    public List<News> getNewssOfBodyAndTypeidAndUseridAndStatus(String body, String typeid, String userid, String status);
    public List<News> getNewssOfBodyAndNewsdateAndUseridAndStatus(String body, String newsdate, String userid, String status);
    public List<News> getNewssOfTypeidAndNewsdateAndUseridAndStatus(String typeid, String newsdate, String userid, String status);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndTypeidAndNewsdate(String newsid, String title, String body, String typeid, String newsdate);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndTypeidAndUserid(String newsid, String title, String body, String typeid, String userid);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndTypeidAndStatus(String newsid, String title, String body, String typeid, String status);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndNewsdateAndUserid(String newsid, String title, String body, String newsdate, String userid);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndNewsdateAndStatus(String newsid, String title, String body, String newsdate, String status);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndUseridAndStatus(String newsid, String title, String body, String userid, String status);
    public List<News> getNewssOfNewsidAndTitleAndTypeidAndNewsdateAndUserid(String newsid, String title, String typeid, String newsdate, String userid);
    public List<News> getNewssOfNewsidAndTitleAndTypeidAndNewsdateAndStatus(String newsid, String title, String typeid, String newsdate, String status);
    public List<News> getNewssOfNewsidAndTitleAndTypeidAndUseridAndStatus(String newsid, String title, String typeid, String userid, String status);
    public List<News> getNewssOfNewsidAndTitleAndNewsdateAndUseridAndStatus(String newsid, String title, String newsdate, String userid, String status);
    public List<News> getNewssOfNewsidAndBodyAndTypeidAndNewsdateAndUserid(String newsid, String body, String typeid, String newsdate, String userid);
    public List<News> getNewssOfNewsidAndBodyAndTypeidAndNewsdateAndStatus(String newsid, String body, String typeid, String newsdate, String status);
    public List<News> getNewssOfNewsidAndBodyAndTypeidAndUseridAndStatus(String newsid, String body, String typeid, String userid, String status);
    public List<News> getNewssOfNewsidAndBodyAndNewsdateAndUseridAndStatus(String newsid, String body, String newsdate, String userid, String status);
    public List<News> getNewssOfNewsidAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String typeid, String newsdate, String userid, String status);
    public List<News> getNewssOfTitleAndBodyAndTypeidAndNewsdateAndUserid(String title, String body, String typeid, String newsdate, String userid);
    public List<News> getNewssOfTitleAndBodyAndTypeidAndNewsdateAndStatus(String title, String body, String typeid, String newsdate, String status);
    public List<News> getNewssOfTitleAndBodyAndTypeidAndUseridAndStatus(String title, String body, String typeid, String userid, String status);
    public List<News> getNewssOfTitleAndBodyAndNewsdateAndUseridAndStatus(String title, String body, String newsdate, String userid, String status);
    public List<News> getNewssOfTitleAndTypeidAndNewsdateAndUseridAndStatus(String title, String typeid, String newsdate, String userid, String status);
    public List<News> getNewssOfBodyAndTypeidAndNewsdateAndUseridAndStatus(String body, String typeid, String newsdate, String userid, String status);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndUserid(String newsid, String title, String body, String typeid, String newsdate, String userid);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndStatus(String newsid, String title, String body, String typeid, String newsdate, String status);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndTypeidAndUseridAndStatus(String newsid, String title, String body, String typeid, String userid, String status);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndNewsdateAndUseridAndStatus(String newsid, String title, String body, String newsdate, String userid, String status);
    public List<News> getNewssOfNewsidAndTitleAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String title, String typeid, String newsdate, String userid, String status);
    public List<News> getNewssOfNewsidAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String body, String typeid, String newsdate, String userid, String status);
    public List<News> getNewssOfTitleAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String title, String body, String typeid, String newsdate, String userid, String status);
    public List<News> getNewssOfNewsidAndTitleAndBodyAndTypeidAndNewsdateAndUseridAndStatus(String newsid, String title, String body, String typeid, String newsdate, String userid, String status);
}
