package com.news.linglian.dao;

import java.util.List;

import com.news.linglian.entity.User;

public interface IUserDao {
    public int update(User user, User keyUser);
    public int updateOfUserId(User user, String userId);
    public int updateOfPassword(User user, String password);
    public int updateOfName(User user, String name);
    public int updateOfSex(User user, String sex);
    public int updateOfRegisterDate(User user, String registerDate);
    public int updateOfLoginDate(User user, String loginDate);
    public int updateOfPhone(User user, String phone);
    public int updateOfEmail(User user, String email);
    public int updateOfMoney(User user, String money);
    public int updateOfScore(User user, String score);
    public int updateOfPath(User user, String path);
    public int updateOfParam(User user, String param);
    public int updateOfLvl(User user, String lvl);
    public int updateOfNewIds(User user, String newIds);
    public int updateOfUserIds(User user, String userIds);
    public int updateOfDesc(User user, String desc);
    public int updateOfImage(User user, String image);
    public int updateOfFamous(User user, String famous);
    public int updateOfBUserIds(User user, String bUserIds);
    public int updateOfUserIdAndPassword(User user, String userId, String password);
    public int updateOfUserIdAndName(User user, String userId, String name);
    public int updateOfUserIdAndSex(User user, String userId, String sex);
    public int updateOfUserIdAndRegisterDate(User user, String userId, String registerDate);
    public int updateOfUserIdAndLoginDate(User user, String userId, String loginDate);
    public int updateOfUserIdAndPhone(User user, String userId, String phone);
    public int updateOfUserIdAndEmail(User user, String userId, String email);
    public int updateOfUserIdAndMoney(User user, String userId, String money);
    public int updateOfUserIdAndScore(User user, String userId, String score);
    public int updateOfUserIdAndPath(User user, String userId, String path);
    public int updateOfUserIdAndParam(User user, String userId, String param);
    public int updateOfUserIdAndLvl(User user, String userId, String lvl);
    public int updateOfUserIdAndNewIds(User user, String userId, String newIds);
    public int updateOfUserIdAndUserIds(User user, String userId, String userIds);
    public int updateOfUserIdAndDesc(User user, String userId, String desc);
    public int updateOfUserIdAndImage(User user, String userId, String image);
    public int updateOfUserIdAndFamous(User user, String userId, String famous);
    public int updateOfUserIdAndBUserIds(User user, String userId, String bUserIds);
    public int updateOfPasswordAndName(User user, String password, String name);
    public int updateOfPasswordAndSex(User user, String password, String sex);
    public int updateOfPasswordAndRegisterDate(User user, String password, String registerDate);
    public int updateOfPasswordAndLoginDate(User user, String password, String loginDate);
    public int updateOfPasswordAndPhone(User user, String password, String phone);
    public int updateOfPasswordAndEmail(User user, String password, String email);
    public int updateOfPasswordAndMoney(User user, String password, String money);
    public int updateOfPasswordAndScore(User user, String password, String score);
    public int updateOfPasswordAndPath(User user, String password, String path);
    public int updateOfPasswordAndParam(User user, String password, String param);
    public int updateOfPasswordAndLvl(User user, String password, String lvl);
    public int updateOfPasswordAndNewIds(User user, String password, String newIds);
    public int updateOfPasswordAndUserIds(User user, String password, String userIds);
    public int updateOfPasswordAndDesc(User user, String password, String desc);
    public int updateOfPasswordAndImage(User user, String password, String image);
    public int updateOfPasswordAndFamous(User user, String password, String famous);
    public int updateOfPasswordAndBUserIds(User user, String password, String bUserIds);
    public int updateOfNameAndSex(User user, String name, String sex);
    public int updateOfNameAndRegisterDate(User user, String name, String registerDate);
    public int updateOfNameAndLoginDate(User user, String name, String loginDate);
    public int updateOfNameAndPhone(User user, String name, String phone);
    public int updateOfNameAndEmail(User user, String name, String email);
    public int updateOfNameAndMoney(User user, String name, String money);
    public int updateOfNameAndScore(User user, String name, String score);
    public int updateOfNameAndPath(User user, String name, String path);
    public int updateOfNameAndParam(User user, String name, String param);
    public int updateOfNameAndLvl(User user, String name, String lvl);
    public int updateOfNameAndNewIds(User user, String name, String newIds);
    public int updateOfNameAndUserIds(User user, String name, String userIds);
    public int updateOfNameAndDesc(User user, String name, String desc);
    public int updateOfNameAndImage(User user, String name, String image);
    public int updateOfNameAndFamous(User user, String name, String famous);
    public int updateOfNameAndBUserIds(User user, String name, String bUserIds);
    public int updateOfSexAndRegisterDate(User user, String sex, String registerDate);
    public int updateOfSexAndLoginDate(User user, String sex, String loginDate);
    public int updateOfSexAndPhone(User user, String sex, String phone);
    public int updateOfSexAndEmail(User user, String sex, String email);
    public int updateOfSexAndMoney(User user, String sex, String money);
    public int updateOfSexAndScore(User user, String sex, String score);
    public int updateOfSexAndPath(User user, String sex, String path);
    public int updateOfSexAndParam(User user, String sex, String param);
    public int updateOfSexAndLvl(User user, String sex, String lvl);
    public int updateOfSexAndNewIds(User user, String sex, String newIds);
    public int updateOfSexAndUserIds(User user, String sex, String userIds);
    public int updateOfSexAndDesc(User user, String sex, String desc);
    public int updateOfSexAndImage(User user, String sex, String image);
    public int updateOfSexAndFamous(User user, String sex, String famous);
    public int updateOfSexAndBUserIds(User user, String sex, String bUserIds);
    public int updateOfRegisterDateAndLoginDate(User user, String registerDate, String loginDate);
    public int updateOfRegisterDateAndPhone(User user, String registerDate, String phone);
    public int updateOfRegisterDateAndEmail(User user, String registerDate, String email);
    public int updateOfRegisterDateAndMoney(User user, String registerDate, String money);
    public int updateOfRegisterDateAndScore(User user, String registerDate, String score);
    public int updateOfRegisterDateAndPath(User user, String registerDate, String path);
    public int updateOfRegisterDateAndParam(User user, String registerDate, String param);
    public int updateOfRegisterDateAndLvl(User user, String registerDate, String lvl);
    public int updateOfRegisterDateAndNewIds(User user, String registerDate, String newIds);
    public int updateOfRegisterDateAndUserIds(User user, String registerDate, String userIds);
    public int updateOfRegisterDateAndDesc(User user, String registerDate, String desc);
    public int updateOfRegisterDateAndImage(User user, String registerDate, String image);
    public int updateOfRegisterDateAndFamous(User user, String registerDate, String famous);
    public int updateOfRegisterDateAndBUserIds(User user, String registerDate, String bUserIds);
    public int updateOfLoginDateAndPhone(User user, String loginDate, String phone);
    public int updateOfLoginDateAndEmail(User user, String loginDate, String email);
    public int updateOfLoginDateAndMoney(User user, String loginDate, String money);
    public int updateOfLoginDateAndScore(User user, String loginDate, String score);
    public int updateOfLoginDateAndPath(User user, String loginDate, String path);
    public int updateOfLoginDateAndParam(User user, String loginDate, String param);
    public int updateOfLoginDateAndLvl(User user, String loginDate, String lvl);
    public int updateOfLoginDateAndNewIds(User user, String loginDate, String newIds);
    public int updateOfLoginDateAndUserIds(User user, String loginDate, String userIds);
    public int updateOfLoginDateAndDesc(User user, String loginDate, String desc);
    public int updateOfLoginDateAndImage(User user, String loginDate, String image);
    public int updateOfLoginDateAndFamous(User user, String loginDate, String famous);
    public int updateOfLoginDateAndBUserIds(User user, String loginDate, String bUserIds);
    public int updateOfPhoneAndEmail(User user, String phone, String email);
    public int updateOfPhoneAndMoney(User user, String phone, String money);
    public int updateOfPhoneAndScore(User user, String phone, String score);
    public int updateOfPhoneAndPath(User user, String phone, String path);
    public int updateOfPhoneAndParam(User user, String phone, String param);
    public int updateOfPhoneAndLvl(User user, String phone, String lvl);
    public int updateOfPhoneAndNewIds(User user, String phone, String newIds);
    public int updateOfPhoneAndUserIds(User user, String phone, String userIds);
    public int updateOfPhoneAndDesc(User user, String phone, String desc);
    public int updateOfPhoneAndImage(User user, String phone, String image);
    public int updateOfPhoneAndFamous(User user, String phone, String famous);
    public int updateOfPhoneAndBUserIds(User user, String phone, String bUserIds);
    public int updateOfEmailAndMoney(User user, String email, String money);
    public int updateOfEmailAndScore(User user, String email, String score);
    public int updateOfEmailAndPath(User user, String email, String path);
    public int updateOfEmailAndParam(User user, String email, String param);
    public int updateOfEmailAndLvl(User user, String email, String lvl);
    public int updateOfEmailAndNewIds(User user, String email, String newIds);
    public int updateOfEmailAndUserIds(User user, String email, String userIds);
    public int updateOfEmailAndDesc(User user, String email, String desc);
    public int updateOfEmailAndImage(User user, String email, String image);
    public int updateOfEmailAndFamous(User user, String email, String famous);
    public int updateOfEmailAndBUserIds(User user, String email, String bUserIds);
    public int updateOfMoneyAndScore(User user, String money, String score);
    public int updateOfMoneyAndPath(User user, String money, String path);
    public int updateOfMoneyAndParam(User user, String money, String param);
    public int updateOfMoneyAndLvl(User user, String money, String lvl);
    public int updateOfMoneyAndNewIds(User user, String money, String newIds);
    public int updateOfMoneyAndUserIds(User user, String money, String userIds);
    public int updateOfMoneyAndDesc(User user, String money, String desc);
    public int updateOfMoneyAndImage(User user, String money, String image);
    public int updateOfMoneyAndFamous(User user, String money, String famous);
    public int updateOfMoneyAndBUserIds(User user, String money, String bUserIds);
    public int updateOfScoreAndPath(User user, String score, String path);
    public int updateOfScoreAndParam(User user, String score, String param);
    public int updateOfScoreAndLvl(User user, String score, String lvl);
    public int updateOfScoreAndNewIds(User user, String score, String newIds);
    public int updateOfScoreAndUserIds(User user, String score, String userIds);
    public int updateOfScoreAndDesc(User user, String score, String desc);
    public int updateOfScoreAndImage(User user, String score, String image);
    public int updateOfScoreAndFamous(User user, String score, String famous);
    public int updateOfScoreAndBUserIds(User user, String score, String bUserIds);
    public int updateOfPathAndParam(User user, String path, String param);
    public int updateOfPathAndLvl(User user, String path, String lvl);
    public int updateOfPathAndNewIds(User user, String path, String newIds);
    public int updateOfPathAndUserIds(User user, String path, String userIds);
    public int updateOfPathAndDesc(User user, String path, String desc);
    public int updateOfPathAndImage(User user, String path, String image);
    public int updateOfPathAndFamous(User user, String path, String famous);
    public int updateOfPathAndBUserIds(User user, String path, String bUserIds);
    public int updateOfParamAndLvl(User user, String param, String lvl);
    public int updateOfParamAndNewIds(User user, String param, String newIds);
    public int updateOfParamAndUserIds(User user, String param, String userIds);
    public int updateOfParamAndDesc(User user, String param, String desc);
    public int updateOfParamAndImage(User user, String param, String image);
    public int updateOfParamAndFamous(User user, String param, String famous);
    public int updateOfParamAndBUserIds(User user, String param, String bUserIds);
    public int updateOfLvlAndNewIds(User user, String lvl, String newIds);
    public int updateOfLvlAndUserIds(User user, String lvl, String userIds);
    public int updateOfLvlAndDesc(User user, String lvl, String desc);
    public int updateOfLvlAndImage(User user, String lvl, String image);
    public int updateOfLvlAndFamous(User user, String lvl, String famous);
    public int updateOfLvlAndBUserIds(User user, String lvl, String bUserIds);
    public int updateOfNewIdsAndUserIds(User user, String newIds, String userIds);
    public int updateOfNewIdsAndDesc(User user, String newIds, String desc);
    public int updateOfNewIdsAndImage(User user, String newIds, String image);
    public int updateOfNewIdsAndFamous(User user, String newIds, String famous);
    public int updateOfNewIdsAndBUserIds(User user, String newIds, String bUserIds);
    public int updateOfUserIdsAndDesc(User user, String userIds, String desc);
    public int updateOfUserIdsAndImage(User user, String userIds, String image);
    public int updateOfUserIdsAndFamous(User user, String userIds, String famous);
    public int updateOfUserIdsAndBUserIds(User user, String userIds, String bUserIds);
    public int updateOfDescAndImage(User user, String desc, String image);
    public int updateOfDescAndFamous(User user, String desc, String famous);
    public int updateOfDescAndBUserIds(User user, String desc, String bUserIds);
    public int updateOfImageAndFamous(User user, String image, String famous);
    public int updateOfImageAndBUserIds(User user, String image, String bUserIds);
    public int updateOfFamousAndBUserIds(User user, String famous, String bUserIds);
    public int remove(User user);
    public int removeOfUserId(String userId);
    public int removeOfPassword(String password);
    public int removeOfName(String name);
    public int removeOfSex(String sex);
    public int removeOfRegisterDate(String registerDate);
    public int removeOfLoginDate(String loginDate);
    public int removeOfPhone(String phone);
    public int removeOfEmail(String email);
    public int removeOfMoney(String money);
    public int removeOfScore(String score);
    public int removeOfPath(String path);
    public int removeOfParam(String param);
    public int removeOfLvl(String lvl);
    public int removeOfNewIds(String newIds);
    public int removeOfUserIds(String userIds);
    public int removeOfDesc(String desc);
    public int removeOfImage(String image);
    public int removeOfFamous(String famous);
    public int removeOfBUserIds(String bUserIds);
    public int removeOfUserIdAndPassword(String userId, String password);
    public int removeOfUserIdAndName(String userId, String name);
    public int removeOfUserIdAndSex(String userId, String sex);
    public int removeOfUserIdAndRegisterDate(String userId, String registerDate);
    public int removeOfUserIdAndLoginDate(String userId, String loginDate);
    public int removeOfUserIdAndPhone(String userId, String phone);
    public int removeOfUserIdAndEmail(String userId, String email);
    public int removeOfUserIdAndMoney(String userId, String money);
    public int removeOfUserIdAndScore(String userId, String score);
    public int removeOfUserIdAndPath(String userId, String path);
    public int removeOfUserIdAndParam(String userId, String param);
    public int removeOfUserIdAndLvl(String userId, String lvl);
    public int removeOfUserIdAndNewIds(String userId, String newIds);
    public int removeOfUserIdAndUserIds(String userId, String userIds);
    public int removeOfUserIdAndDesc(String userId, String desc);
    public int removeOfUserIdAndImage(String userId, String image);
    public int removeOfUserIdAndFamous(String userId, String famous);
    public int removeOfUserIdAndBUserIds(String userId, String bUserIds);
    public int removeOfPasswordAndName(String password, String name);
    public int removeOfPasswordAndSex(String password, String sex);
    public int removeOfPasswordAndRegisterDate(String password, String registerDate);
    public int removeOfPasswordAndLoginDate(String password, String loginDate);
    public int removeOfPasswordAndPhone(String password, String phone);
    public int removeOfPasswordAndEmail(String password, String email);
    public int removeOfPasswordAndMoney(String password, String money);
    public int removeOfPasswordAndScore(String password, String score);
    public int removeOfPasswordAndPath(String password, String path);
    public int removeOfPasswordAndParam(String password, String param);
    public int removeOfPasswordAndLvl(String password, String lvl);
    public int removeOfPasswordAndNewIds(String password, String newIds);
    public int removeOfPasswordAndUserIds(String password, String userIds);
    public int removeOfPasswordAndDesc(String password, String desc);
    public int removeOfPasswordAndImage(String password, String image);
    public int removeOfPasswordAndFamous(String password, String famous);
    public int removeOfPasswordAndBUserIds(String password, String bUserIds);
    public int removeOfNameAndSex(String name, String sex);
    public int removeOfNameAndRegisterDate(String name, String registerDate);
    public int removeOfNameAndLoginDate(String name, String loginDate);
    public int removeOfNameAndPhone(String name, String phone);
    public int removeOfNameAndEmail(String name, String email);
    public int removeOfNameAndMoney(String name, String money);
    public int removeOfNameAndScore(String name, String score);
    public int removeOfNameAndPath(String name, String path);
    public int removeOfNameAndParam(String name, String param);
    public int removeOfNameAndLvl(String name, String lvl);
    public int removeOfNameAndNewIds(String name, String newIds);
    public int removeOfNameAndUserIds(String name, String userIds);
    public int removeOfNameAndDesc(String name, String desc);
    public int removeOfNameAndImage(String name, String image);
    public int removeOfNameAndFamous(String name, String famous);
    public int removeOfNameAndBUserIds(String name, String bUserIds);
    public int removeOfSexAndRegisterDate(String sex, String registerDate);
    public int removeOfSexAndLoginDate(String sex, String loginDate);
    public int removeOfSexAndPhone(String sex, String phone);
    public int removeOfSexAndEmail(String sex, String email);
    public int removeOfSexAndMoney(String sex, String money);
    public int removeOfSexAndScore(String sex, String score);
    public int removeOfSexAndPath(String sex, String path);
    public int removeOfSexAndParam(String sex, String param);
    public int removeOfSexAndLvl(String sex, String lvl);
    public int removeOfSexAndNewIds(String sex, String newIds);
    public int removeOfSexAndUserIds(String sex, String userIds);
    public int removeOfSexAndDesc(String sex, String desc);
    public int removeOfSexAndImage(String sex, String image);
    public int removeOfSexAndFamous(String sex, String famous);
    public int removeOfSexAndBUserIds(String sex, String bUserIds);
    public int removeOfRegisterDateAndLoginDate(String registerDate, String loginDate);
    public int removeOfRegisterDateAndPhone(String registerDate, String phone);
    public int removeOfRegisterDateAndEmail(String registerDate, String email);
    public int removeOfRegisterDateAndMoney(String registerDate, String money);
    public int removeOfRegisterDateAndScore(String registerDate, String score);
    public int removeOfRegisterDateAndPath(String registerDate, String path);
    public int removeOfRegisterDateAndParam(String registerDate, String param);
    public int removeOfRegisterDateAndLvl(String registerDate, String lvl);
    public int removeOfRegisterDateAndNewIds(String registerDate, String newIds);
    public int removeOfRegisterDateAndUserIds(String registerDate, String userIds);
    public int removeOfRegisterDateAndDesc(String registerDate, String desc);
    public int removeOfRegisterDateAndImage(String registerDate, String image);
    public int removeOfRegisterDateAndFamous(String registerDate, String famous);
    public int removeOfRegisterDateAndBUserIds(String registerDate, String bUserIds);
    public int removeOfLoginDateAndPhone(String loginDate, String phone);
    public int removeOfLoginDateAndEmail(String loginDate, String email);
    public int removeOfLoginDateAndMoney(String loginDate, String money);
    public int removeOfLoginDateAndScore(String loginDate, String score);
    public int removeOfLoginDateAndPath(String loginDate, String path);
    public int removeOfLoginDateAndParam(String loginDate, String param);
    public int removeOfLoginDateAndLvl(String loginDate, String lvl);
    public int removeOfLoginDateAndNewIds(String loginDate, String newIds);
    public int removeOfLoginDateAndUserIds(String loginDate, String userIds);
    public int removeOfLoginDateAndDesc(String loginDate, String desc);
    public int removeOfLoginDateAndImage(String loginDate, String image);
    public int removeOfLoginDateAndFamous(String loginDate, String famous);
    public int removeOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public int removeOfPhoneAndEmail(String phone, String email);
    public int removeOfPhoneAndMoney(String phone, String money);
    public int removeOfPhoneAndScore(String phone, String score);
    public int removeOfPhoneAndPath(String phone, String path);
    public int removeOfPhoneAndParam(String phone, String param);
    public int removeOfPhoneAndLvl(String phone, String lvl);
    public int removeOfPhoneAndNewIds(String phone, String newIds);
    public int removeOfPhoneAndUserIds(String phone, String userIds);
    public int removeOfPhoneAndDesc(String phone, String desc);
    public int removeOfPhoneAndImage(String phone, String image);
    public int removeOfPhoneAndFamous(String phone, String famous);
    public int removeOfPhoneAndBUserIds(String phone, String bUserIds);
    public int removeOfEmailAndMoney(String email, String money);
    public int removeOfEmailAndScore(String email, String score);
    public int removeOfEmailAndPath(String email, String path);
    public int removeOfEmailAndParam(String email, String param);
    public int removeOfEmailAndLvl(String email, String lvl);
    public int removeOfEmailAndNewIds(String email, String newIds);
    public int removeOfEmailAndUserIds(String email, String userIds);
    public int removeOfEmailAndDesc(String email, String desc);
    public int removeOfEmailAndImage(String email, String image);
    public int removeOfEmailAndFamous(String email, String famous);
    public int removeOfEmailAndBUserIds(String email, String bUserIds);
    public int removeOfMoneyAndScore(String money, String score);
    public int removeOfMoneyAndPath(String money, String path);
    public int removeOfMoneyAndParam(String money, String param);
    public int removeOfMoneyAndLvl(String money, String lvl);
    public int removeOfMoneyAndNewIds(String money, String newIds);
    public int removeOfMoneyAndUserIds(String money, String userIds);
    public int removeOfMoneyAndDesc(String money, String desc);
    public int removeOfMoneyAndImage(String money, String image);
    public int removeOfMoneyAndFamous(String money, String famous);
    public int removeOfMoneyAndBUserIds(String money, String bUserIds);
    public int removeOfScoreAndPath(String score, String path);
    public int removeOfScoreAndParam(String score, String param);
    public int removeOfScoreAndLvl(String score, String lvl);
    public int removeOfScoreAndNewIds(String score, String newIds);
    public int removeOfScoreAndUserIds(String score, String userIds);
    public int removeOfScoreAndDesc(String score, String desc);
    public int removeOfScoreAndImage(String score, String image);
    public int removeOfScoreAndFamous(String score, String famous);
    public int removeOfScoreAndBUserIds(String score, String bUserIds);
    public int removeOfPathAndParam(String path, String param);
    public int removeOfPathAndLvl(String path, String lvl);
    public int removeOfPathAndNewIds(String path, String newIds);
    public int removeOfPathAndUserIds(String path, String userIds);
    public int removeOfPathAndDesc(String path, String desc);
    public int removeOfPathAndImage(String path, String image);
    public int removeOfPathAndFamous(String path, String famous);
    public int removeOfPathAndBUserIds(String path, String bUserIds);
    public int removeOfParamAndLvl(String param, String lvl);
    public int removeOfParamAndNewIds(String param, String newIds);
    public int removeOfParamAndUserIds(String param, String userIds);
    public int removeOfParamAndDesc(String param, String desc);
    public int removeOfParamAndImage(String param, String image);
    public int removeOfParamAndFamous(String param, String famous);
    public int removeOfParamAndBUserIds(String param, String bUserIds);
    public int removeOfLvlAndNewIds(String lvl, String newIds);
    public int removeOfLvlAndUserIds(String lvl, String userIds);
    public int removeOfLvlAndDesc(String lvl, String desc);
    public int removeOfLvlAndImage(String lvl, String image);
    public int removeOfLvlAndFamous(String lvl, String famous);
    public int removeOfLvlAndBUserIds(String lvl, String bUserIds);
    public int removeOfNewIdsAndUserIds(String newIds, String userIds);
    public int removeOfNewIdsAndDesc(String newIds, String desc);
    public int removeOfNewIdsAndImage(String newIds, String image);
    public int removeOfNewIdsAndFamous(String newIds, String famous);
    public int removeOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public int removeOfUserIdsAndDesc(String userIds, String desc);
    public int removeOfUserIdsAndImage(String userIds, String image);
    public int removeOfUserIdsAndFamous(String userIds, String famous);
    public int removeOfUserIdsAndBUserIds(String userIds, String bUserIds);
    public int removeOfDescAndImage(String desc, String image);
    public int removeOfDescAndFamous(String desc, String famous);
    public int removeOfDescAndBUserIds(String desc, String bUserIds);
    public int removeOfImageAndFamous(String image, String famous);
    public int removeOfImageAndBUserIds(String image, String bUserIds);
    public int removeOfFamousAndBUserIds(String famous, String bUserIds);
    public int insert(User user);
    public int insertOfUserId(String userId);
    public int insertOfPassword(String password);
    public int insertOfName(String name);
    public int insertOfSex(String sex);
    public int insertOfRegisterDate(String registerDate);
    public int insertOfLoginDate(String loginDate);
    public int insertOfPhone(String phone);
    public int insertOfEmail(String email);
    public int insertOfMoney(String money);
    public int insertOfScore(String score);
    public int insertOfPath(String path);
    public int insertOfParam(String param);
    public int insertOfLvl(String lvl);
    public int insertOfNewIds(String newIds);
    public int insertOfUserIds(String userIds);
    public int insertOfDesc(String desc);
    public int insertOfImage(String image);
    public int insertOfFamous(String famous);
    public int insertOfBUserIds(String bUserIds);
    public int insertOfUserIdAndPassword(String userId, String password);
    public int insertOfUserIdAndName(String userId, String name);
    public int insertOfUserIdAndSex(String userId, String sex);
    public int insertOfUserIdAndRegisterDate(String userId, String registerDate);
    public int insertOfUserIdAndLoginDate(String userId, String loginDate);
    public int insertOfUserIdAndPhone(String userId, String phone);
    public int insertOfUserIdAndEmail(String userId, String email);
    public int insertOfUserIdAndMoney(String userId, String money);
    public int insertOfUserIdAndScore(String userId, String score);
    public int insertOfUserIdAndPath(String userId, String path);
    public int insertOfUserIdAndParam(String userId, String param);
    public int insertOfUserIdAndLvl(String userId, String lvl);
    public int insertOfUserIdAndNewIds(String userId, String newIds);
    public int insertOfUserIdAndUserIds(String userId, String userIds);
    public int insertOfUserIdAndDesc(String userId, String desc);
    public int insertOfUserIdAndImage(String userId, String image);
    public int insertOfUserIdAndFamous(String userId, String famous);
    public int insertOfUserIdAndBUserIds(String userId, String bUserIds);
    public int insertOfPasswordAndName(String password, String name);
    public int insertOfPasswordAndSex(String password, String sex);
    public int insertOfPasswordAndRegisterDate(String password, String registerDate);
    public int insertOfPasswordAndLoginDate(String password, String loginDate);
    public int insertOfPasswordAndPhone(String password, String phone);
    public int insertOfPasswordAndEmail(String password, String email);
    public int insertOfPasswordAndMoney(String password, String money);
    public int insertOfPasswordAndScore(String password, String score);
    public int insertOfPasswordAndPath(String password, String path);
    public int insertOfPasswordAndParam(String password, String param);
    public int insertOfPasswordAndLvl(String password, String lvl);
    public int insertOfPasswordAndNewIds(String password, String newIds);
    public int insertOfPasswordAndUserIds(String password, String userIds);
    public int insertOfPasswordAndDesc(String password, String desc);
    public int insertOfPasswordAndImage(String password, String image);
    public int insertOfPasswordAndFamous(String password, String famous);
    public int insertOfPasswordAndBUserIds(String password, String bUserIds);
    public int insertOfNameAndSex(String name, String sex);
    public int insertOfNameAndRegisterDate(String name, String registerDate);
    public int insertOfNameAndLoginDate(String name, String loginDate);
    public int insertOfNameAndPhone(String name, String phone);
    public int insertOfNameAndEmail(String name, String email);
    public int insertOfNameAndMoney(String name, String money);
    public int insertOfNameAndScore(String name, String score);
    public int insertOfNameAndPath(String name, String path);
    public int insertOfNameAndParam(String name, String param);
    public int insertOfNameAndLvl(String name, String lvl);
    public int insertOfNameAndNewIds(String name, String newIds);
    public int insertOfNameAndUserIds(String name, String userIds);
    public int insertOfNameAndDesc(String name, String desc);
    public int insertOfNameAndImage(String name, String image);
    public int insertOfNameAndFamous(String name, String famous);
    public int insertOfNameAndBUserIds(String name, String bUserIds);
    public int insertOfSexAndRegisterDate(String sex, String registerDate);
    public int insertOfSexAndLoginDate(String sex, String loginDate);
    public int insertOfSexAndPhone(String sex, String phone);
    public int insertOfSexAndEmail(String sex, String email);
    public int insertOfSexAndMoney(String sex, String money);
    public int insertOfSexAndScore(String sex, String score);
    public int insertOfSexAndPath(String sex, String path);
    public int insertOfSexAndParam(String sex, String param);
    public int insertOfSexAndLvl(String sex, String lvl);
    public int insertOfSexAndNewIds(String sex, String newIds);
    public int insertOfSexAndUserIds(String sex, String userIds);
    public int insertOfSexAndDesc(String sex, String desc);
    public int insertOfSexAndImage(String sex, String image);
    public int insertOfSexAndFamous(String sex, String famous);
    public int insertOfSexAndBUserIds(String sex, String bUserIds);
    public int insertOfRegisterDateAndLoginDate(String registerDate, String loginDate);
    public int insertOfRegisterDateAndPhone(String registerDate, String phone);
    public int insertOfRegisterDateAndEmail(String registerDate, String email);
    public int insertOfRegisterDateAndMoney(String registerDate, String money);
    public int insertOfRegisterDateAndScore(String registerDate, String score);
    public int insertOfRegisterDateAndPath(String registerDate, String path);
    public int insertOfRegisterDateAndParam(String registerDate, String param);
    public int insertOfRegisterDateAndLvl(String registerDate, String lvl);
    public int insertOfRegisterDateAndNewIds(String registerDate, String newIds);
    public int insertOfRegisterDateAndUserIds(String registerDate, String userIds);
    public int insertOfRegisterDateAndDesc(String registerDate, String desc);
    public int insertOfRegisterDateAndImage(String registerDate, String image);
    public int insertOfRegisterDateAndFamous(String registerDate, String famous);
    public int insertOfRegisterDateAndBUserIds(String registerDate, String bUserIds);
    public int insertOfLoginDateAndPhone(String loginDate, String phone);
    public int insertOfLoginDateAndEmail(String loginDate, String email);
    public int insertOfLoginDateAndMoney(String loginDate, String money);
    public int insertOfLoginDateAndScore(String loginDate, String score);
    public int insertOfLoginDateAndPath(String loginDate, String path);
    public int insertOfLoginDateAndParam(String loginDate, String param);
    public int insertOfLoginDateAndLvl(String loginDate, String lvl);
    public int insertOfLoginDateAndNewIds(String loginDate, String newIds);
    public int insertOfLoginDateAndUserIds(String loginDate, String userIds);
    public int insertOfLoginDateAndDesc(String loginDate, String desc);
    public int insertOfLoginDateAndImage(String loginDate, String image);
    public int insertOfLoginDateAndFamous(String loginDate, String famous);
    public int insertOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public int insertOfPhoneAndEmail(String phone, String email);
    public int insertOfPhoneAndMoney(String phone, String money);
    public int insertOfPhoneAndScore(String phone, String score);
    public int insertOfPhoneAndPath(String phone, String path);
    public int insertOfPhoneAndParam(String phone, String param);
    public int insertOfPhoneAndLvl(String phone, String lvl);
    public int insertOfPhoneAndNewIds(String phone, String newIds);
    public int insertOfPhoneAndUserIds(String phone, String userIds);
    public int insertOfPhoneAndDesc(String phone, String desc);
    public int insertOfPhoneAndImage(String phone, String image);
    public int insertOfPhoneAndFamous(String phone, String famous);
    public int insertOfPhoneAndBUserIds(String phone, String bUserIds);
    public int insertOfEmailAndMoney(String email, String money);
    public int insertOfEmailAndScore(String email, String score);
    public int insertOfEmailAndPath(String email, String path);
    public int insertOfEmailAndParam(String email, String param);
    public int insertOfEmailAndLvl(String email, String lvl);
    public int insertOfEmailAndNewIds(String email, String newIds);
    public int insertOfEmailAndUserIds(String email, String userIds);
    public int insertOfEmailAndDesc(String email, String desc);
    public int insertOfEmailAndImage(String email, String image);
    public int insertOfEmailAndFamous(String email, String famous);
    public int insertOfEmailAndBUserIds(String email, String bUserIds);
    public int insertOfMoneyAndScore(String money, String score);
    public int insertOfMoneyAndPath(String money, String path);
    public int insertOfMoneyAndParam(String money, String param);
    public int insertOfMoneyAndLvl(String money, String lvl);
    public int insertOfMoneyAndNewIds(String money, String newIds);
    public int insertOfMoneyAndUserIds(String money, String userIds);
    public int insertOfMoneyAndDesc(String money, String desc);
    public int insertOfMoneyAndImage(String money, String image);
    public int insertOfMoneyAndFamous(String money, String famous);
    public int insertOfMoneyAndBUserIds(String money, String bUserIds);
    public int insertOfScoreAndPath(String score, String path);
    public int insertOfScoreAndParam(String score, String param);
    public int insertOfScoreAndLvl(String score, String lvl);
    public int insertOfScoreAndNewIds(String score, String newIds);
    public int insertOfScoreAndUserIds(String score, String userIds);
    public int insertOfScoreAndDesc(String score, String desc);
    public int insertOfScoreAndImage(String score, String image);
    public int insertOfScoreAndFamous(String score, String famous);
    public int insertOfScoreAndBUserIds(String score, String bUserIds);
    public int insertOfPathAndParam(String path, String param);
    public int insertOfPathAndLvl(String path, String lvl);
    public int insertOfPathAndNewIds(String path, String newIds);
    public int insertOfPathAndUserIds(String path, String userIds);
    public int insertOfPathAndDesc(String path, String desc);
    public int insertOfPathAndImage(String path, String image);
    public int insertOfPathAndFamous(String path, String famous);
    public int insertOfPathAndBUserIds(String path, String bUserIds);
    public int insertOfParamAndLvl(String param, String lvl);
    public int insertOfParamAndNewIds(String param, String newIds);
    public int insertOfParamAndUserIds(String param, String userIds);
    public int insertOfParamAndDesc(String param, String desc);
    public int insertOfParamAndImage(String param, String image);
    public int insertOfParamAndFamous(String param, String famous);
    public int insertOfParamAndBUserIds(String param, String bUserIds);
    public int insertOfLvlAndNewIds(String lvl, String newIds);
    public int insertOfLvlAndUserIds(String lvl, String userIds);
    public int insertOfLvlAndDesc(String lvl, String desc);
    public int insertOfLvlAndImage(String lvl, String image);
    public int insertOfLvlAndFamous(String lvl, String famous);
    public int insertOfLvlAndBUserIds(String lvl, String bUserIds);
    public int insertOfNewIdsAndUserIds(String newIds, String userIds);
    public int insertOfNewIdsAndDesc(String newIds, String desc);
    public int insertOfNewIdsAndImage(String newIds, String image);
    public int insertOfNewIdsAndFamous(String newIds, String famous);
    public int insertOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public int insertOfUserIdsAndDesc(String userIds, String desc);
    public int insertOfUserIdsAndImage(String userIds, String image);
    public int insertOfUserIdsAndFamous(String userIds, String famous);
    public int insertOfUserIdsAndBUserIds(String userIds, String bUserIds);
    public int insertOfDescAndImage(String desc, String image);
    public int insertOfDescAndFamous(String desc, String famous);
    public int insertOfDescAndBUserIds(String desc, String bUserIds);
    public int insertOfImageAndFamous(String image, String famous);
    public int insertOfImageAndBUserIds(String image, String bUserIds);
    public int insertOfFamousAndBUserIds(String famous, String bUserIds);
    public User getUser(User user);
    public User getUserOfUserId(String userId);
    public User getUserOfPassword(String password);
    public User getUserOfName(String name);
    public User getUserOfSex(String sex);
    public User getUserOfRegisterDate(String registerDate);
    public User getUserOfLoginDate(String loginDate);
    public User getUserOfPhone(String phone);
    public User getUserOfEmail(String email);
    public User getUserOfMoney(String money);
    public User getUserOfScore(String score);
    public User getUserOfPath(String path);
    public User getUserOfParam(String param);
    public User getUserOfLvl(String lvl);
    public User getUserOfNewIds(String newIds);
    public User getUserOfUserIds(String userIds);
    public User getUserOfDesc(String desc);
    public User getUserOfImage(String image);
    public User getUserOfFamous(String famous);
    public User getUserOfBUserIds(String bUserIds);
    public User getUserOfUserIdAndPassword(String userId, String password);
    public User getUserOfUserIdAndName(String userId, String name);
    public User getUserOfUserIdAndSex(String userId, String sex);
    public User getUserOfUserIdAndRegisterDate(String userId, String registerDate);
    public User getUserOfUserIdAndLoginDate(String userId, String loginDate);
    public User getUserOfUserIdAndPhone(String userId, String phone);
    public User getUserOfUserIdAndEmail(String userId, String email);
    public User getUserOfUserIdAndMoney(String userId, String money);
    public User getUserOfUserIdAndScore(String userId, String score);
    public User getUserOfUserIdAndPath(String userId, String path);
    public User getUserOfUserIdAndParam(String userId, String param);
    public User getUserOfUserIdAndLvl(String userId, String lvl);
    public User getUserOfUserIdAndNewIds(String userId, String newIds);
    public User getUserOfUserIdAndUserIds(String userId, String userIds);
    public User getUserOfUserIdAndDesc(String userId, String desc);
    public User getUserOfUserIdAndImage(String userId, String image);
    public User getUserOfUserIdAndFamous(String userId, String famous);
    public User getUserOfUserIdAndBUserIds(String userId, String bUserIds);
    public User getUserOfPasswordAndName(String password, String name);
    public User getUserOfPasswordAndSex(String password, String sex);
    public User getUserOfPasswordAndRegisterDate(String password, String registerDate);
    public User getUserOfPasswordAndLoginDate(String password, String loginDate);
    public User getUserOfPasswordAndPhone(String password, String phone);
    public User getUserOfPasswordAndEmail(String password, String email);
    public User getUserOfPasswordAndMoney(String password, String money);
    public User getUserOfPasswordAndScore(String password, String score);
    public User getUserOfPasswordAndPath(String password, String path);
    public User getUserOfPasswordAndParam(String password, String param);
    public User getUserOfPasswordAndLvl(String password, String lvl);
    public User getUserOfPasswordAndNewIds(String password, String newIds);
    public User getUserOfPasswordAndUserIds(String password, String userIds);
    public User getUserOfPasswordAndDesc(String password, String desc);
    public User getUserOfPasswordAndImage(String password, String image);
    public User getUserOfPasswordAndFamous(String password, String famous);
    public User getUserOfPasswordAndBUserIds(String password, String bUserIds);
    public User getUserOfNameAndSex(String name, String sex);
    public User getUserOfNameAndRegisterDate(String name, String registerDate);
    public User getUserOfNameAndLoginDate(String name, String loginDate);
    public User getUserOfNameAndPhone(String name, String phone);
    public User getUserOfNameAndEmail(String name, String email);
    public User getUserOfNameAndMoney(String name, String money);
    public User getUserOfNameAndScore(String name, String score);
    public User getUserOfNameAndPath(String name, String path);
    public User getUserOfNameAndParam(String name, String param);
    public User getUserOfNameAndLvl(String name, String lvl);
    public User getUserOfNameAndNewIds(String name, String newIds);
    public User getUserOfNameAndUserIds(String name, String userIds);
    public User getUserOfNameAndDesc(String name, String desc);
    public User getUserOfNameAndImage(String name, String image);
    public User getUserOfNameAndFamous(String name, String famous);
    public User getUserOfNameAndBUserIds(String name, String bUserIds);
    public User getUserOfSexAndRegisterDate(String sex, String registerDate);
    public User getUserOfSexAndLoginDate(String sex, String loginDate);
    public User getUserOfSexAndPhone(String sex, String phone);
    public User getUserOfSexAndEmail(String sex, String email);
    public User getUserOfSexAndMoney(String sex, String money);
    public User getUserOfSexAndScore(String sex, String score);
    public User getUserOfSexAndPath(String sex, String path);
    public User getUserOfSexAndParam(String sex, String param);
    public User getUserOfSexAndLvl(String sex, String lvl);
    public User getUserOfSexAndNewIds(String sex, String newIds);
    public User getUserOfSexAndUserIds(String sex, String userIds);
    public User getUserOfSexAndDesc(String sex, String desc);
    public User getUserOfSexAndImage(String sex, String image);
    public User getUserOfSexAndFamous(String sex, String famous);
    public User getUserOfSexAndBUserIds(String sex, String bUserIds);
    public User getUserOfRegisterDateAndLoginDate(String registerDate, String loginDate);
    public User getUserOfRegisterDateAndPhone(String registerDate, String phone);
    public User getUserOfRegisterDateAndEmail(String registerDate, String email);
    public User getUserOfRegisterDateAndMoney(String registerDate, String money);
    public User getUserOfRegisterDateAndScore(String registerDate, String score);
    public User getUserOfRegisterDateAndPath(String registerDate, String path);
    public User getUserOfRegisterDateAndParam(String registerDate, String param);
    public User getUserOfRegisterDateAndLvl(String registerDate, String lvl);
    public User getUserOfRegisterDateAndNewIds(String registerDate, String newIds);
    public User getUserOfRegisterDateAndUserIds(String registerDate, String userIds);
    public User getUserOfRegisterDateAndDesc(String registerDate, String desc);
    public User getUserOfRegisterDateAndImage(String registerDate, String image);
    public User getUserOfRegisterDateAndFamous(String registerDate, String famous);
    public User getUserOfRegisterDateAndBUserIds(String registerDate, String bUserIds);
    public User getUserOfLoginDateAndPhone(String loginDate, String phone);
    public User getUserOfLoginDateAndEmail(String loginDate, String email);
    public User getUserOfLoginDateAndMoney(String loginDate, String money);
    public User getUserOfLoginDateAndScore(String loginDate, String score);
    public User getUserOfLoginDateAndPath(String loginDate, String path);
    public User getUserOfLoginDateAndParam(String loginDate, String param);
    public User getUserOfLoginDateAndLvl(String loginDate, String lvl);
    public User getUserOfLoginDateAndNewIds(String loginDate, String newIds);
    public User getUserOfLoginDateAndUserIds(String loginDate, String userIds);
    public User getUserOfLoginDateAndDesc(String loginDate, String desc);
    public User getUserOfLoginDateAndImage(String loginDate, String image);
    public User getUserOfLoginDateAndFamous(String loginDate, String famous);
    public User getUserOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public User getUserOfPhoneAndEmail(String phone, String email);
    public User getUserOfPhoneAndMoney(String phone, String money);
    public User getUserOfPhoneAndScore(String phone, String score);
    public User getUserOfPhoneAndPath(String phone, String path);
    public User getUserOfPhoneAndParam(String phone, String param);
    public User getUserOfPhoneAndLvl(String phone, String lvl);
    public User getUserOfPhoneAndNewIds(String phone, String newIds);
    public User getUserOfPhoneAndUserIds(String phone, String userIds);
    public User getUserOfPhoneAndDesc(String phone, String desc);
    public User getUserOfPhoneAndImage(String phone, String image);
    public User getUserOfPhoneAndFamous(String phone, String famous);
    public User getUserOfPhoneAndBUserIds(String phone, String bUserIds);
    public User getUserOfEmailAndMoney(String email, String money);
    public User getUserOfEmailAndScore(String email, String score);
    public User getUserOfEmailAndPath(String email, String path);
    public User getUserOfEmailAndParam(String email, String param);
    public User getUserOfEmailAndLvl(String email, String lvl);
    public User getUserOfEmailAndNewIds(String email, String newIds);
    public User getUserOfEmailAndUserIds(String email, String userIds);
    public User getUserOfEmailAndDesc(String email, String desc);
    public User getUserOfEmailAndImage(String email, String image);
    public User getUserOfEmailAndFamous(String email, String famous);
    public User getUserOfEmailAndBUserIds(String email, String bUserIds);
    public User getUserOfMoneyAndScore(String money, String score);
    public User getUserOfMoneyAndPath(String money, String path);
    public User getUserOfMoneyAndParam(String money, String param);
    public User getUserOfMoneyAndLvl(String money, String lvl);
    public User getUserOfMoneyAndNewIds(String money, String newIds);
    public User getUserOfMoneyAndUserIds(String money, String userIds);
    public User getUserOfMoneyAndDesc(String money, String desc);
    public User getUserOfMoneyAndImage(String money, String image);
    public User getUserOfMoneyAndFamous(String money, String famous);
    public User getUserOfMoneyAndBUserIds(String money, String bUserIds);
    public User getUserOfScoreAndPath(String score, String path);
    public User getUserOfScoreAndParam(String score, String param);
    public User getUserOfScoreAndLvl(String score, String lvl);
    public User getUserOfScoreAndNewIds(String score, String newIds);
    public User getUserOfScoreAndUserIds(String score, String userIds);
    public User getUserOfScoreAndDesc(String score, String desc);
    public User getUserOfScoreAndImage(String score, String image);
    public User getUserOfScoreAndFamous(String score, String famous);
    public User getUserOfScoreAndBUserIds(String score, String bUserIds);
    public User getUserOfPathAndParam(String path, String param);
    public User getUserOfPathAndLvl(String path, String lvl);
    public User getUserOfPathAndNewIds(String path, String newIds);
    public User getUserOfPathAndUserIds(String path, String userIds);
    public User getUserOfPathAndDesc(String path, String desc);
    public User getUserOfPathAndImage(String path, String image);
    public User getUserOfPathAndFamous(String path, String famous);
    public User getUserOfPathAndBUserIds(String path, String bUserIds);
    public User getUserOfParamAndLvl(String param, String lvl);
    public User getUserOfParamAndNewIds(String param, String newIds);
    public User getUserOfParamAndUserIds(String param, String userIds);
    public User getUserOfParamAndDesc(String param, String desc);
    public User getUserOfParamAndImage(String param, String image);
    public User getUserOfParamAndFamous(String param, String famous);
    public User getUserOfParamAndBUserIds(String param, String bUserIds);
    public User getUserOfLvlAndNewIds(String lvl, String newIds);
    public User getUserOfLvlAndUserIds(String lvl, String userIds);
    public User getUserOfLvlAndDesc(String lvl, String desc);
    public User getUserOfLvlAndImage(String lvl, String image);
    public User getUserOfLvlAndFamous(String lvl, String famous);
    public User getUserOfLvlAndBUserIds(String lvl, String bUserIds);
    public User getUserOfNewIdsAndUserIds(String newIds, String userIds);
    public User getUserOfNewIdsAndDesc(String newIds, String desc);
    public User getUserOfNewIdsAndImage(String newIds, String image);
    public User getUserOfNewIdsAndFamous(String newIds, String famous);
    public User getUserOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public User getUserOfUserIdsAndDesc(String userIds, String desc);
    public User getUserOfUserIdsAndImage(String userIds, String image);
    public User getUserOfUserIdsAndFamous(String userIds, String famous);
    public User getUserOfUserIdsAndBUserIds(String userIds, String bUserIds);
    public User getUserOfDescAndImage(String desc, String image);
    public User getUserOfDescAndFamous(String desc, String famous);
    public User getUserOfDescAndBUserIds(String desc, String bUserIds);
    public User getUserOfImageAndFamous(String image, String famous);
    public User getUserOfImageAndBUserIds(String image, String bUserIds);
    public User getUserOfFamousAndBUserIds(String famous, String bUserIds);
    public List<User> getUsers(User user);
    public List<User> getUsersOfUserId(String userId);
    public List<User> getUsersOfPassword(String password);
    public List<User> getUsersOfName(String name);
    public List<User> getUsersOfSex(String sex);
    public List<User> getUsersOfRegisterDate(String registerDate);
    public List<User> getUsersOfLoginDate(String loginDate);
    public List<User> getUsersOfPhone(String phone);
    public List<User> getUsersOfEmail(String email);
    public List<User> getUsersOfMoney(String money);
    public List<User> getUsersOfScore(String score);
    public List<User> getUsersOfPath(String path);
    public List<User> getUsersOfParam(String param);
    public List<User> getUsersOfLvl(String lvl);
    public List<User> getUsersOfNewIds(String newIds);
    public List<User> getUsersOfUserIds(String userIds);
    public List<User> getUsersOfDesc(String desc);
    public List<User> getUsersOfImage(String image);
    public List<User> getUsersOfFamous(String famous);
    public List<User> getUsersOfBUserIds(String bUserIds);
    public List<User> getUsersOfUserIdAndPassword(String userId, String password);
    public List<User> getUsersOfUserIdAndName(String userId, String name);
    public List<User> getUsersOfUserIdAndSex(String userId, String sex);
    public List<User> getUsersOfUserIdAndRegisterDate(String userId, String registerDate);
    public List<User> getUsersOfUserIdAndLoginDate(String userId, String loginDate);
    public List<User> getUsersOfUserIdAndPhone(String userId, String phone);
    public List<User> getUsersOfUserIdAndEmail(String userId, String email);
    public List<User> getUsersOfUserIdAndMoney(String userId, String money);
    public List<User> getUsersOfUserIdAndScore(String userId, String score);
    public List<User> getUsersOfUserIdAndPath(String userId, String path);
    public List<User> getUsersOfUserIdAndParam(String userId, String param);
    public List<User> getUsersOfUserIdAndLvl(String userId, String lvl);
    public List<User> getUsersOfUserIdAndNewIds(String userId, String newIds);
    public List<User> getUsersOfUserIdAndUserIds(String userId, String userIds);
    public List<User> getUsersOfUserIdAndDesc(String userId, String desc);
    public List<User> getUsersOfUserIdAndImage(String userId, String image);
    public List<User> getUsersOfUserIdAndFamous(String userId, String famous);
    public List<User> getUsersOfUserIdAndBUserIds(String userId, String bUserIds);
    public List<User> getUsersOfPasswordAndName(String password, String name);
    public List<User> getUsersOfPasswordAndSex(String password, String sex);
    public List<User> getUsersOfPasswordAndRegisterDate(String password, String registerDate);
    public List<User> getUsersOfPasswordAndLoginDate(String password, String loginDate);
    public List<User> getUsersOfPasswordAndPhone(String password, String phone);
    public List<User> getUsersOfPasswordAndEmail(String password, String email);
    public List<User> getUsersOfPasswordAndMoney(String password, String money);
    public List<User> getUsersOfPasswordAndScore(String password, String score);
    public List<User> getUsersOfPasswordAndPath(String password, String path);
    public List<User> getUsersOfPasswordAndParam(String password, String param);
    public List<User> getUsersOfPasswordAndLvl(String password, String lvl);
    public List<User> getUsersOfPasswordAndNewIds(String password, String newIds);
    public List<User> getUsersOfPasswordAndUserIds(String password, String userIds);
    public List<User> getUsersOfPasswordAndDesc(String password, String desc);
    public List<User> getUsersOfPasswordAndImage(String password, String image);
    public List<User> getUsersOfPasswordAndFamous(String password, String famous);
    public List<User> getUsersOfPasswordAndBUserIds(String password, String bUserIds);
    public List<User> getUsersOfNameAndSex(String name, String sex);
    public List<User> getUsersOfNameAndRegisterDate(String name, String registerDate);
    public List<User> getUsersOfNameAndLoginDate(String name, String loginDate);
    public List<User> getUsersOfNameAndPhone(String name, String phone);
    public List<User> getUsersOfNameAndEmail(String name, String email);
    public List<User> getUsersOfNameAndMoney(String name, String money);
    public List<User> getUsersOfNameAndScore(String name, String score);
    public List<User> getUsersOfNameAndPath(String name, String path);
    public List<User> getUsersOfNameAndParam(String name, String param);
    public List<User> getUsersOfNameAndLvl(String name, String lvl);
    public List<User> getUsersOfNameAndNewIds(String name, String newIds);
    public List<User> getUsersOfNameAndUserIds(String name, String userIds);
    public List<User> getUsersOfNameAndDesc(String name, String desc);
    public List<User> getUsersOfNameAndImage(String name, String image);
    public List<User> getUsersOfNameAndFamous(String name, String famous);
    public List<User> getUsersOfNameAndBUserIds(String name, String bUserIds);
    public List<User> getUsersOfSexAndRegisterDate(String sex, String registerDate);
    public List<User> getUsersOfSexAndLoginDate(String sex, String loginDate);
    public List<User> getUsersOfSexAndPhone(String sex, String phone);
    public List<User> getUsersOfSexAndEmail(String sex, String email);
    public List<User> getUsersOfSexAndMoney(String sex, String money);
    public List<User> getUsersOfSexAndScore(String sex, String score);
    public List<User> getUsersOfSexAndPath(String sex, String path);
    public List<User> getUsersOfSexAndParam(String sex, String param);
    public List<User> getUsersOfSexAndLvl(String sex, String lvl);
    public List<User> getUsersOfSexAndNewIds(String sex, String newIds);
    public List<User> getUsersOfSexAndUserIds(String sex, String userIds);
    public List<User> getUsersOfSexAndDesc(String sex, String desc);
    public List<User> getUsersOfSexAndImage(String sex, String image);
    public List<User> getUsersOfSexAndFamous(String sex, String famous);
    public List<User> getUsersOfSexAndBUserIds(String sex, String bUserIds);
    public List<User> getUsersOfRegisterDateAndLoginDate(String registerDate, String loginDate);
    public List<User> getUsersOfRegisterDateAndPhone(String registerDate, String phone);
    public List<User> getUsersOfRegisterDateAndEmail(String registerDate, String email);
    public List<User> getUsersOfRegisterDateAndMoney(String registerDate, String money);
    public List<User> getUsersOfRegisterDateAndScore(String registerDate, String score);
    public List<User> getUsersOfRegisterDateAndPath(String registerDate, String path);
    public List<User> getUsersOfRegisterDateAndParam(String registerDate, String param);
    public List<User> getUsersOfRegisterDateAndLvl(String registerDate, String lvl);
    public List<User> getUsersOfRegisterDateAndNewIds(String registerDate, String newIds);
    public List<User> getUsersOfRegisterDateAndUserIds(String registerDate, String userIds);
    public List<User> getUsersOfRegisterDateAndDesc(String registerDate, String desc);
    public List<User> getUsersOfRegisterDateAndImage(String registerDate, String image);
    public List<User> getUsersOfRegisterDateAndFamous(String registerDate, String famous);
    public List<User> getUsersOfRegisterDateAndBUserIds(String registerDate, String bUserIds);
    public List<User> getUsersOfLoginDateAndPhone(String loginDate, String phone);
    public List<User> getUsersOfLoginDateAndEmail(String loginDate, String email);
    public List<User> getUsersOfLoginDateAndMoney(String loginDate, String money);
    public List<User> getUsersOfLoginDateAndScore(String loginDate, String score);
    public List<User> getUsersOfLoginDateAndPath(String loginDate, String path);
    public List<User> getUsersOfLoginDateAndParam(String loginDate, String param);
    public List<User> getUsersOfLoginDateAndLvl(String loginDate, String lvl);
    public List<User> getUsersOfLoginDateAndNewIds(String loginDate, String newIds);
    public List<User> getUsersOfLoginDateAndUserIds(String loginDate, String userIds);
    public List<User> getUsersOfLoginDateAndDesc(String loginDate, String desc);
    public List<User> getUsersOfLoginDateAndImage(String loginDate, String image);
    public List<User> getUsersOfLoginDateAndFamous(String loginDate, String famous);
    public List<User> getUsersOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public List<User> getUsersOfPhoneAndEmail(String phone, String email);
    public List<User> getUsersOfPhoneAndMoney(String phone, String money);
    public List<User> getUsersOfPhoneAndScore(String phone, String score);
    public List<User> getUsersOfPhoneAndPath(String phone, String path);
    public List<User> getUsersOfPhoneAndParam(String phone, String param);
    public List<User> getUsersOfPhoneAndLvl(String phone, String lvl);
    public List<User> getUsersOfPhoneAndNewIds(String phone, String newIds);
    public List<User> getUsersOfPhoneAndUserIds(String phone, String userIds);
    public List<User> getUsersOfPhoneAndDesc(String phone, String desc);
    public List<User> getUsersOfPhoneAndImage(String phone, String image);
    public List<User> getUsersOfPhoneAndFamous(String phone, String famous);
    public List<User> getUsersOfPhoneAndBUserIds(String phone, String bUserIds);
    public List<User> getUsersOfEmailAndMoney(String email, String money);
    public List<User> getUsersOfEmailAndScore(String email, String score);
    public List<User> getUsersOfEmailAndPath(String email, String path);
    public List<User> getUsersOfEmailAndParam(String email, String param);
    public List<User> getUsersOfEmailAndLvl(String email, String lvl);
    public List<User> getUsersOfEmailAndNewIds(String email, String newIds);
    public List<User> getUsersOfEmailAndUserIds(String email, String userIds);
    public List<User> getUsersOfEmailAndDesc(String email, String desc);
    public List<User> getUsersOfEmailAndImage(String email, String image);
    public List<User> getUsersOfEmailAndFamous(String email, String famous);
    public List<User> getUsersOfEmailAndBUserIds(String email, String bUserIds);
    public List<User> getUsersOfMoneyAndScore(String money, String score);
    public List<User> getUsersOfMoneyAndPath(String money, String path);
    public List<User> getUsersOfMoneyAndParam(String money, String param);
    public List<User> getUsersOfMoneyAndLvl(String money, String lvl);
    public List<User> getUsersOfMoneyAndNewIds(String money, String newIds);
    public List<User> getUsersOfMoneyAndUserIds(String money, String userIds);
    public List<User> getUsersOfMoneyAndDesc(String money, String desc);
    public List<User> getUsersOfMoneyAndImage(String money, String image);
    public List<User> getUsersOfMoneyAndFamous(String money, String famous);
    public List<User> getUsersOfMoneyAndBUserIds(String money, String bUserIds);
    public List<User> getUsersOfScoreAndPath(String score, String path);
    public List<User> getUsersOfScoreAndParam(String score, String param);
    public List<User> getUsersOfScoreAndLvl(String score, String lvl);
    public List<User> getUsersOfScoreAndNewIds(String score, String newIds);
    public List<User> getUsersOfScoreAndUserIds(String score, String userIds);
    public List<User> getUsersOfScoreAndDesc(String score, String desc);
    public List<User> getUsersOfScoreAndImage(String score, String image);
    public List<User> getUsersOfScoreAndFamous(String score, String famous);
    public List<User> getUsersOfScoreAndBUserIds(String score, String bUserIds);
    public List<User> getUsersOfPathAndParam(String path, String param);
    public List<User> getUsersOfPathAndLvl(String path, String lvl);
    public List<User> getUsersOfPathAndNewIds(String path, String newIds);
    public List<User> getUsersOfPathAndUserIds(String path, String userIds);
    public List<User> getUsersOfPathAndDesc(String path, String desc);
    public List<User> getUsersOfPathAndImage(String path, String image);
    public List<User> getUsersOfPathAndFamous(String path, String famous);
    public List<User> getUsersOfPathAndBUserIds(String path, String bUserIds);
    public List<User> getUsersOfParamAndLvl(String param, String lvl);
    public List<User> getUsersOfParamAndNewIds(String param, String newIds);
    public List<User> getUsersOfParamAndUserIds(String param, String userIds);
    public List<User> getUsersOfParamAndDesc(String param, String desc);
    public List<User> getUsersOfParamAndImage(String param, String image);
    public List<User> getUsersOfParamAndFamous(String param, String famous);
    public List<User> getUsersOfParamAndBUserIds(String param, String bUserIds);
    public List<User> getUsersOfLvlAndNewIds(String lvl, String newIds);
    public List<User> getUsersOfLvlAndUserIds(String lvl, String userIds);
    public List<User> getUsersOfLvlAndDesc(String lvl, String desc);
    public List<User> getUsersOfLvlAndImage(String lvl, String image);
    public List<User> getUsersOfLvlAndFamous(String lvl, String famous);
    public List<User> getUsersOfLvlAndBUserIds(String lvl, String bUserIds);
    public List<User> getUsersOfNewIdsAndUserIds(String newIds, String userIds);
    public List<User> getUsersOfNewIdsAndDesc(String newIds, String desc);
    public List<User> getUsersOfNewIdsAndImage(String newIds, String image);
    public List<User> getUsersOfNewIdsAndFamous(String newIds, String famous);
    public List<User> getUsersOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public List<User> getUsersOfUserIdsAndDesc(String userIds, String desc);
    public List<User> getUsersOfUserIdsAndImage(String userIds, String image);
    public List<User> getUsersOfUserIdsAndFamous(String userIds, String famous);
    public List<User> getUsersOfUserIdsAndBUserIds(String userIds, String bUserIds);
    public List<User> getUsersOfDescAndImage(String desc, String image);
    public List<User> getUsersOfDescAndFamous(String desc, String famous);
    public List<User> getUsersOfDescAndBUserIds(String desc, String bUserIds);
    public List<User> getUsersOfImageAndFamous(String image, String famous);
    public List<User> getUsersOfImageAndBUserIds(String image, String bUserIds);
    public List<User> getUsersOfFamousAndBUserIds(String famous, String bUserIds);
}
