package com.news.linglian.dao;

import java.util.List;

import com.news.linglian.entity.User;

public interface IUserDao {
    public int update(User user, User keyUser);
    public int updateOfUserId(User user, String userId);
    public int updateOfPassword(User user, String password);
    public int updateOfName(User user, String name);
    public int updateOfSex(User user, String sex);
    public int updateOfRegisterDate(User user, String registerDate);
    public int updateOfLoginDate(User user, String loginDate);
    public int updateOfPhone(User user, String phone);
    public int updateOfEmail(User user, String email);
    public int updateOfMoney(User user, String money);
    public int updateOfScore(User user, String score);
    public int updateOfPath(User user, String path);
    public int updateOfParam(User user, String param);
    public int updateOfLvl(User user, String lvl);
    public int updateOfNewIds(User user, String newIds);
    public int updateOfUserIds(User user, String userIds);
    public int updateOfSignature(User user, String signature);
    public int updateOfImage(User user, String image);
    public int updateOfFamous(User user, String famous);
    public int updateOfBUserIds(User user, String bUserIds);
    public int updateOfDays(User user, String days);
    public int updateOfNowDays(User user, String nowDays);
    public int updateOfUserIdAndPassword(User user, String userId, String password);
    public int updateOfUserIdAndName(User user, String userId, String name);
    public int updateOfUserIdAndSex(User user, String userId, String sex);
    public int updateOfUserIdAndRegisterDate(User user, String userId, String registerDate);
    public int updateOfUserIdAndLoginDate(User user, String userId, String loginDate);
    public int updateOfUserIdAndPhone(User user, String userId, String phone);
    public int updateOfUserIdAndEmail(User user, String userId, String email);
    public int updateOfUserIdAndMoney(User user, String userId, String money);
    public int updateOfUserIdAndScore(User user, String userId, String score);
    public int updateOfUserIdAndPath(User user, String userId, String path);
    public int updateOfUserIdAndParam(User user, String userId, String param);
    public int updateOfUserIdAndLvl(User user, String userId, String lvl);
    public int updateOfUserIdAndNewIds(User user, String userId, String newIds);
    public int updateOfUserIdAndUserIds(User user, String userId, String userIds);
    public int updateOfUserIdAndSignature(User user, String userId, String signature);
    public int updateOfUserIdAndImage(User user, String userId, String image);
    public int updateOfUserIdAndFamous(User user, String userId, String famous);
    public int updateOfUserIdAndBUserIds(User user, String userId, String bUserIds);
    public int updateOfUserIdAndDays(User user, String userId, String days);
    public int updateOfUserIdAndNowDays(User user, String userId, String nowDays);
    public int updateOfPasswordAndName(User user, String password, String name);
    public int updateOfPasswordAndSex(User user, String password, String sex);
    public int updateOfPasswordAndRegisterDate(User user, String password, String registerDate);
    public int updateOfPasswordAndLoginDate(User user, String password, String loginDate);
    public int updateOfPasswordAndPhone(User user, String password, String phone);
    public int updateOfPasswordAndEmail(User user, String password, String email);
    public int updateOfPasswordAndMoney(User user, String password, String money);
    public int updateOfPasswordAndScore(User user, String password, String score);
    public int updateOfPasswordAndPath(User user, String password, String path);
    public int updateOfPasswordAndParam(User user, String password, String param);
    public int updateOfPasswordAndLvl(User user, String password, String lvl);
    public int updateOfPasswordAndNewIds(User user, String password, String newIds);
    public int updateOfPasswordAndUserIds(User user, String password, String userIds);
    public int updateOfPasswordAndSignature(User user, String password, String signature);
    public int updateOfPasswordAndImage(User user, String password, String image);
    public int updateOfPasswordAndFamous(User user, String password, String famous);
    public int updateOfPasswordAndBUserIds(User user, String password, String bUserIds);
    public int updateOfPasswordAndDays(User user, String password, String days);
    public int updateOfPasswordAndNowDays(User user, String password, String nowDays);
    public int updateOfNameAndSex(User user, String name, String sex);
    public int updateOfNameAndRegisterDate(User user, String name, String registerDate);
    public int updateOfNameAndLoginDate(User user, String name, String loginDate);
    public int updateOfNameAndPhone(User user, String name, String phone);
    public int updateOfNameAndEmail(User user, String name, String email);
    public int updateOfNameAndMoney(User user, String name, String money);
    public int updateOfNameAndScore(User user, String name, String score);
    public int updateOfNameAndPath(User user, String name, String path);
    public int updateOfNameAndParam(User user, String name, String param);
    public int updateOfNameAndLvl(User user, String name, String lvl);
    public int updateOfNameAndNewIds(User user, String name, String newIds);
    public int updateOfNameAndUserIds(User user, String name, String userIds);
    public int updateOfNameAndSignature(User user, String name, String signature);
    public int updateOfNameAndImage(User user, String name, String image);
    public int updateOfNameAndFamous(User user, String name, String famous);
    public int updateOfNameAndBUserIds(User user, String name, String bUserIds);
    public int updateOfNameAndDays(User user, String name, String days);
    public int updateOfNameAndNowDays(User user, String name, String nowDays);
    public int updateOfSexAndRegisterDate(User user, String sex, String registerDate);
    public int updateOfSexAndLoginDate(User user, String sex, String loginDate);
    public int updateOfSexAndPhone(User user, String sex, String phone);
    public int updateOfSexAndEmail(User user, String sex, String email);
    public int updateOfSexAndMoney(User user, String sex, String money);
    public int updateOfSexAndScore(User user, String sex, String score);
    public int updateOfSexAndPath(User user, String sex, String path);
    public int updateOfSexAndParam(User user, String sex, String param);
    public int updateOfSexAndLvl(User user, String sex, String lvl);
    public int updateOfSexAndNewIds(User user, String sex, String newIds);
    public int updateOfSexAndUserIds(User user, String sex, String userIds);
    public int updateOfSexAndSignature(User user, String sex, String signature);
    public int updateOfSexAndImage(User user, String sex, String image);
    public int updateOfSexAndFamous(User user, String sex, String famous);
    public int updateOfSexAndBUserIds(User user, String sex, String bUserIds);
    public int updateOfSexAndDays(User user, String sex, String days);
    public int updateOfSexAndNowDays(User user, String sex, String nowDays);
    public int updateOfRegisterDateAndLoginDate(User user, String registerDate, String loginDate);
    public int updateOfRegisterDateAndPhone(User user, String registerDate, String phone);
    public int updateOfRegisterDateAndEmail(User user, String registerDate, String email);
    public int updateOfRegisterDateAndMoney(User user, String registerDate, String money);
    public int updateOfRegisterDateAndScore(User user, String registerDate, String score);
    public int updateOfRegisterDateAndPath(User user, String registerDate, String path);
    public int updateOfRegisterDateAndParam(User user, String registerDate, String param);
    public int updateOfRegisterDateAndLvl(User user, String registerDate, String lvl);
    public int updateOfRegisterDateAndNewIds(User user, String registerDate, String newIds);
    public int updateOfRegisterDateAndUserIds(User user, String registerDate, String userIds);
    public int updateOfRegisterDateAndSignature(User user, String registerDate, String signature);
    public int updateOfRegisterDateAndImage(User user, String registerDate, String image);
    public int updateOfRegisterDateAndFamous(User user, String registerDate, String famous);
    public int updateOfRegisterDateAndBUserIds(User user, String registerDate, String bUserIds);
    public int updateOfRegisterDateAndDays(User user, String registerDate, String days);
    public int updateOfRegisterDateAndNowDays(User user, String registerDate, String nowDays);
    public int updateOfLoginDateAndPhone(User user, String loginDate, String phone);
    public int updateOfLoginDateAndEmail(User user, String loginDate, String email);
    public int updateOfLoginDateAndMoney(User user, String loginDate, String money);
    public int updateOfLoginDateAndScore(User user, String loginDate, String score);
    public int updateOfLoginDateAndPath(User user, String loginDate, String path);
    public int updateOfLoginDateAndParam(User user, String loginDate, String param);
    public int updateOfLoginDateAndLvl(User user, String loginDate, String lvl);
    public int updateOfLoginDateAndNewIds(User user, String loginDate, String newIds);
    public int updateOfLoginDateAndUserIds(User user, String loginDate, String userIds);
    public int updateOfLoginDateAndSignature(User user, String loginDate, String signature);
    public int updateOfLoginDateAndImage(User user, String loginDate, String image);
    public int updateOfLoginDateAndFamous(User user, String loginDate, String famous);
    public int updateOfLoginDateAndBUserIds(User user, String loginDate, String bUserIds);
    public int updateOfLoginDateAndDays(User user, String loginDate, String days);
    public int updateOfLoginDateAndNowDays(User user, String loginDate, String nowDays);
    public int updateOfPhoneAndEmail(User user, String phone, String email);
    public int updateOfPhoneAndMoney(User user, String phone, String money);
    public int updateOfPhoneAndScore(User user, String phone, String score);
    public int updateOfPhoneAndPath(User user, String phone, String path);
    public int updateOfPhoneAndParam(User user, String phone, String param);
    public int updateOfPhoneAndLvl(User user, String phone, String lvl);
    public int updateOfPhoneAndNewIds(User user, String phone, String newIds);
    public int updateOfPhoneAndUserIds(User user, String phone, String userIds);
    public int updateOfPhoneAndSignature(User user, String phone, String signature);
    public int updateOfPhoneAndImage(User user, String phone, String image);
    public int updateOfPhoneAndFamous(User user, String phone, String famous);
    public int updateOfPhoneAndBUserIds(User user, String phone, String bUserIds);
    public int updateOfPhoneAndDays(User user, String phone, String days);
    public int updateOfPhoneAndNowDays(User user, String phone, String nowDays);
    public int updateOfEmailAndMoney(User user, String email, String money);
    public int updateOfEmailAndScore(User user, String email, String score);
    public int updateOfEmailAndPath(User user, String email, String path);
    public int updateOfEmailAndParam(User user, String email, String param);
    public int updateOfEmailAndLvl(User user, String email, String lvl);
    public int updateOfEmailAndNewIds(User user, String email, String newIds);
    public int updateOfEmailAndUserIds(User user, String email, String userIds);
    public int updateOfEmailAndSignature(User user, String email, String signature);
    public int updateOfEmailAndImage(User user, String email, String image);
    public int updateOfEmailAndFamous(User user, String email, String famous);
    public int updateOfEmailAndBUserIds(User user, String email, String bUserIds);
    public int updateOfEmailAndDays(User user, String email, String days);
    public int updateOfEmailAndNowDays(User user, String email, String nowDays);
    public int updateOfMoneyAndScore(User user, String money, String score);
    public int updateOfMoneyAndPath(User user, String money, String path);
    public int updateOfMoneyAndParam(User user, String money, String param);
    public int updateOfMoneyAndLvl(User user, String money, String lvl);
    public int updateOfMoneyAndNewIds(User user, String money, String newIds);
    public int updateOfMoneyAndUserIds(User user, String money, String userIds);
    public int updateOfMoneyAndSignature(User user, String money, String signature);
    public int updateOfMoneyAndImage(User user, String money, String image);
    public int updateOfMoneyAndFamous(User user, String money, String famous);
    public int updateOfMoneyAndBUserIds(User user, String money, String bUserIds);
    public int updateOfMoneyAndDays(User user, String money, String days);
    public int updateOfMoneyAndNowDays(User user, String money, String nowDays);
    public int updateOfScoreAndPath(User user, String score, String path);
    public int updateOfScoreAndParam(User user, String score, String param);
    public int updateOfScoreAndLvl(User user, String score, String lvl);
    public int updateOfScoreAndNewIds(User user, String score, String newIds);
    public int updateOfScoreAndUserIds(User user, String score, String userIds);
    public int updateOfScoreAndSignature(User user, String score, String signature);
    public int updateOfScoreAndImage(User user, String score, String image);
    public int updateOfScoreAndFamous(User user, String score, String famous);
    public int updateOfScoreAndBUserIds(User user, String score, String bUserIds);
    public int updateOfScoreAndDays(User user, String score, String days);
    public int updateOfScoreAndNowDays(User user, String score, String nowDays);
    public int updateOfPathAndParam(User user, String path, String param);
    public int updateOfPathAndLvl(User user, String path, String lvl);
    public int updateOfPathAndNewIds(User user, String path, String newIds);
    public int updateOfPathAndUserIds(User user, String path, String userIds);
    public int updateOfPathAndSignature(User user, String path, String signature);
    public int updateOfPathAndImage(User user, String path, String image);
    public int updateOfPathAndFamous(User user, String path, String famous);
    public int updateOfPathAndBUserIds(User user, String path, String bUserIds);
    public int updateOfPathAndDays(User user, String path, String days);
    public int updateOfPathAndNowDays(User user, String path, String nowDays);
    public int updateOfParamAndLvl(User user, String param, String lvl);
    public int updateOfParamAndNewIds(User user, String param, String newIds);
    public int updateOfParamAndUserIds(User user, String param, String userIds);
    public int updateOfParamAndSignature(User user, String param, String signature);
    public int updateOfParamAndImage(User user, String param, String image);
    public int updateOfParamAndFamous(User user, String param, String famous);
    public int updateOfParamAndBUserIds(User user, String param, String bUserIds);
    public int updateOfParamAndDays(User user, String param, String days);
    public int updateOfParamAndNowDays(User user, String param, String nowDays);
    public int updateOfLvlAndNewIds(User user, String lvl, String newIds);
    public int updateOfLvlAndUserIds(User user, String lvl, String userIds);
    public int updateOfLvlAndSignature(User user, String lvl, String signature);
    public int updateOfLvlAndImage(User user, String lvl, String image);
    public int updateOfLvlAndFamous(User user, String lvl, String famous);
    public int updateOfLvlAndBUserIds(User user, String lvl, String bUserIds);
    public int updateOfLvlAndDays(User user, String lvl, String days);
    public int updateOfLvlAndNowDays(User user, String lvl, String nowDays);
    public int updateOfNewIdsAndUserIds(User user, String newIds, String userIds);
    public int updateOfNewIdsAndSignature(User user, String newIds, String signature);
    public int updateOfNewIdsAndImage(User user, String newIds, String image);
    public int updateOfNewIdsAndFamous(User user, String newIds, String famous);
    public int updateOfNewIdsAndBUserIds(User user, String newIds, String bUserIds);
    public int updateOfNewIdsAndDays(User user, String newIds, String days);
    public int updateOfNewIdsAndNowDays(User user, String newIds, String nowDays);
    public int updateOfUserIdsAndSignature(User user, String userIds, String signature);
    public int updateOfUserIdsAndImage(User user, String userIds, String image);
    public int updateOfUserIdsAndFamous(User user, String userIds, String famous);
    public int updateOfUserIdsAndBUserIds(User user, String userIds, String bUserIds);
    public int updateOfUserIdsAndDays(User user, String userIds, String days);
    public int updateOfUserIdsAndNowDays(User user, String userIds, String nowDays);
    public int updateOfSignatureAndImage(User user, String signature, String image);
    public int updateOfSignatureAndFamous(User user, String signature, String famous);
    public int updateOfSignatureAndBUserIds(User user, String signature, String bUserIds);
    public int updateOfSignatureAndDays(User user, String signature, String days);
    public int updateOfSignatureAndNowDays(User user, String signature, String nowDays);
    public int updateOfImageAndFamous(User user, String image, String famous);
    public int updateOfImageAndBUserIds(User user, String image, String bUserIds);
    public int updateOfImageAndDays(User user, String image, String days);
    public int updateOfImageAndNowDays(User user, String image, String nowDays);
    public int updateOfFamousAndBUserIds(User user, String famous, String bUserIds);
    public int updateOfFamousAndDays(User user, String famous, String days);
    public int updateOfFamousAndNowDays(User user, String famous, String nowDays);
    public int updateOfBUserIdsAndDays(User user, String bUserIds, String days);
    public int updateOfBUserIdsAndNowDays(User user, String bUserIds, String nowDays);
    public int updateOfDaysAndNowDays(User user, String days, String nowDays);
    public int remove(User user);
    public int removeOfUserId(String userId);
    public int removeOfPassword(String password);
    public int removeOfName(String name);
    public int removeOfSex(String sex);
    public int removeOfRegisterDate(String registerDate);
    public int removeOfLoginDate(String loginDate);
    public int removeOfPhone(String phone);
    public int removeOfEmail(String email);
    public int removeOfMoney(String money);
    public int removeOfScore(String score);
    public int removeOfPath(String path);
    public int removeOfParam(String param);
    public int removeOfLvl(String lvl);
    public int removeOfNewIds(String newIds);
    public int removeOfUserIds(String userIds);
    public int removeOfSignature(String signature);
    public int removeOfImage(String image);
    public int removeOfFamous(String famous);
    public int removeOfBUserIds(String bUserIds);
    public int removeOfDays(String days);
    public int removeOfNowDays(String nowDays);
    public int removeOfUserIdAndPassword(String userId, String password);
    public int removeOfUserIdAndName(String userId, String name);
    public int removeOfUserIdAndSex(String userId, String sex);
    public int removeOfUserIdAndRegisterDate(String userId, String registerDate);
    public int removeOfUserIdAndLoginDate(String userId, String loginDate);
    public int removeOfUserIdAndPhone(String userId, String phone);
    public int removeOfUserIdAndEmail(String userId, String email);
    public int removeOfUserIdAndMoney(String userId, String money);
    public int removeOfUserIdAndScore(String userId, String score);
    public int removeOfUserIdAndPath(String userId, String path);
    public int removeOfUserIdAndParam(String userId, String param);
    public int removeOfUserIdAndLvl(String userId, String lvl);
    public int removeOfUserIdAndNewIds(String userId, String newIds);
    public int removeOfUserIdAndUserIds(String userId, String userIds);
    public int removeOfUserIdAndSignature(String userId, String signature);
    public int removeOfUserIdAndImage(String userId, String image);
    public int removeOfUserIdAndFamous(String userId, String famous);
    public int removeOfUserIdAndBUserIds(String userId, String bUserIds);
    public int removeOfUserIdAndDays(String userId, String days);
    public int removeOfUserIdAndNowDays(String userId, String nowDays);
    public int removeOfPasswordAndName(String password, String name);
    public int removeOfPasswordAndSex(String password, String sex);
    public int removeOfPasswordAndRegisterDate(String password, String registerDate);
    public int removeOfPasswordAndLoginDate(String password, String loginDate);
    public int removeOfPasswordAndPhone(String password, String phone);
    public int removeOfPasswordAndEmail(String password, String email);
    public int removeOfPasswordAndMoney(String password, String money);
    public int removeOfPasswordAndScore(String password, String score);
    public int removeOfPasswordAndPath(String password, String path);
    public int removeOfPasswordAndParam(String password, String param);
    public int removeOfPasswordAndLvl(String password, String lvl);
    public int removeOfPasswordAndNewIds(String password, String newIds);
    public int removeOfPasswordAndUserIds(String password, String userIds);
    public int removeOfPasswordAndSignature(String password, String signature);
    public int removeOfPasswordAndImage(String password, String image);
    public int removeOfPasswordAndFamous(String password, String famous);
    public int removeOfPasswordAndBUserIds(String password, String bUserIds);
    public int removeOfPasswordAndDays(String password, String days);
    public int removeOfPasswordAndNowDays(String password, String nowDays);
    public int removeOfNameAndSex(String name, String sex);
    public int removeOfNameAndRegisterDate(String name, String registerDate);
    public int removeOfNameAndLoginDate(String name, String loginDate);
    public int removeOfNameAndPhone(String name, String phone);
    public int removeOfNameAndEmail(String name, String email);
    public int removeOfNameAndMoney(String name, String money);
    public int removeOfNameAndScore(String name, String score);
    public int removeOfNameAndPath(String name, String path);
    public int removeOfNameAndParam(String name, String param);
    public int removeOfNameAndLvl(String name, String lvl);
    public int removeOfNameAndNewIds(String name, String newIds);
    public int removeOfNameAndUserIds(String name, String userIds);
    public int removeOfNameAndSignature(String name, String signature);
    public int removeOfNameAndImage(String name, String image);
    public int removeOfNameAndFamous(String name, String famous);
    public int removeOfNameAndBUserIds(String name, String bUserIds);
    public int removeOfNameAndDays(String name, String days);
    public int removeOfNameAndNowDays(String name, String nowDays);
    public int removeOfSexAndRegisterDate(String sex, String registerDate);
    public int removeOfSexAndLoginDate(String sex, String loginDate);
    public int removeOfSexAndPhone(String sex, String phone);
    public int removeOfSexAndEmail(String sex, String email);
    public int removeOfSexAndMoney(String sex, String money);
    public int removeOfSexAndScore(String sex, String score);
    public int removeOfSexAndPath(String sex, String path);
    public int removeOfSexAndParam(String sex, String param);
    public int removeOfSexAndLvl(String sex, String lvl);
    public int removeOfSexAndNewIds(String sex, String newIds);
    public int removeOfSexAndUserIds(String sex, String userIds);
    public int removeOfSexAndSignature(String sex, String signature);
    public int removeOfSexAndImage(String sex, String image);
    public int removeOfSexAndFamous(String sex, String famous);
    public int removeOfSexAndBUserIds(String sex, String bUserIds);
    public int removeOfSexAndDays(String sex, String days);
    public int removeOfSexAndNowDays(String sex, String nowDays);
    public int removeOfRegisterDateAndLoginDate(String registerDate, String loginDate);
    public int removeOfRegisterDateAndPhone(String registerDate, String phone);
    public int removeOfRegisterDateAndEmail(String registerDate, String email);
    public int removeOfRegisterDateAndMoney(String registerDate, String money);
    public int removeOfRegisterDateAndScore(String registerDate, String score);
    public int removeOfRegisterDateAndPath(String registerDate, String path);
    public int removeOfRegisterDateAndParam(String registerDate, String param);
    public int removeOfRegisterDateAndLvl(String registerDate, String lvl);
    public int removeOfRegisterDateAndNewIds(String registerDate, String newIds);
    public int removeOfRegisterDateAndUserIds(String registerDate, String userIds);
    public int removeOfRegisterDateAndSignature(String registerDate, String signature);
    public int removeOfRegisterDateAndImage(String registerDate, String image);
    public int removeOfRegisterDateAndFamous(String registerDate, String famous);
    public int removeOfRegisterDateAndBUserIds(String registerDate, String bUserIds);
    public int removeOfRegisterDateAndDays(String registerDate, String days);
    public int removeOfRegisterDateAndNowDays(String registerDate, String nowDays);
    public int removeOfLoginDateAndPhone(String loginDate, String phone);
    public int removeOfLoginDateAndEmail(String loginDate, String email);
    public int removeOfLoginDateAndMoney(String loginDate, String money);
    public int removeOfLoginDateAndScore(String loginDate, String score);
    public int removeOfLoginDateAndPath(String loginDate, String path);
    public int removeOfLoginDateAndParam(String loginDate, String param);
    public int removeOfLoginDateAndLvl(String loginDate, String lvl);
    public int removeOfLoginDateAndNewIds(String loginDate, String newIds);
    public int removeOfLoginDateAndUserIds(String loginDate, String userIds);
    public int removeOfLoginDateAndSignature(String loginDate, String signature);
    public int removeOfLoginDateAndImage(String loginDate, String image);
    public int removeOfLoginDateAndFamous(String loginDate, String famous);
    public int removeOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public int removeOfLoginDateAndDays(String loginDate, String days);
    public int removeOfLoginDateAndNowDays(String loginDate, String nowDays);
    public int removeOfPhoneAndEmail(String phone, String email);
    public int removeOfPhoneAndMoney(String phone, String money);
    public int removeOfPhoneAndScore(String phone, String score);
    public int removeOfPhoneAndPath(String phone, String path);
    public int removeOfPhoneAndParam(String phone, String param);
    public int removeOfPhoneAndLvl(String phone, String lvl);
    public int removeOfPhoneAndNewIds(String phone, String newIds);
    public int removeOfPhoneAndUserIds(String phone, String userIds);
    public int removeOfPhoneAndSignature(String phone, String signature);
    public int removeOfPhoneAndImage(String phone, String image);
    public int removeOfPhoneAndFamous(String phone, String famous);
    public int removeOfPhoneAndBUserIds(String phone, String bUserIds);
    public int removeOfPhoneAndDays(String phone, String days);
    public int removeOfPhoneAndNowDays(String phone, String nowDays);
    public int removeOfEmailAndMoney(String email, String money);
    public int removeOfEmailAndScore(String email, String score);
    public int removeOfEmailAndPath(String email, String path);
    public int removeOfEmailAndParam(String email, String param);
    public int removeOfEmailAndLvl(String email, String lvl);
    public int removeOfEmailAndNewIds(String email, String newIds);
    public int removeOfEmailAndUserIds(String email, String userIds);
    public int removeOfEmailAndSignature(String email, String signature);
    public int removeOfEmailAndImage(String email, String image);
    public int removeOfEmailAndFamous(String email, String famous);
    public int removeOfEmailAndBUserIds(String email, String bUserIds);
    public int removeOfEmailAndDays(String email, String days);
    public int removeOfEmailAndNowDays(String email, String nowDays);
    public int removeOfMoneyAndScore(String money, String score);
    public int removeOfMoneyAndPath(String money, String path);
    public int removeOfMoneyAndParam(String money, String param);
    public int removeOfMoneyAndLvl(String money, String lvl);
    public int removeOfMoneyAndNewIds(String money, String newIds);
    public int removeOfMoneyAndUserIds(String money, String userIds);
    public int removeOfMoneyAndSignature(String money, String signature);
    public int removeOfMoneyAndImage(String money, String image);
    public int removeOfMoneyAndFamous(String money, String famous);
    public int removeOfMoneyAndBUserIds(String money, String bUserIds);
    public int removeOfMoneyAndDays(String money, String days);
    public int removeOfMoneyAndNowDays(String money, String nowDays);
    public int removeOfScoreAndPath(String score, String path);
    public int removeOfScoreAndParam(String score, String param);
    public int removeOfScoreAndLvl(String score, String lvl);
    public int removeOfScoreAndNewIds(String score, String newIds);
    public int removeOfScoreAndUserIds(String score, String userIds);
    public int removeOfScoreAndSignature(String score, String signature);
    public int removeOfScoreAndImage(String score, String image);
    public int removeOfScoreAndFamous(String score, String famous);
    public int removeOfScoreAndBUserIds(String score, String bUserIds);
    public int removeOfScoreAndDays(String score, String days);
    public int removeOfScoreAndNowDays(String score, String nowDays);
    public int removeOfPathAndParam(String path, String param);
    public int removeOfPathAndLvl(String path, String lvl);
    public int removeOfPathAndNewIds(String path, String newIds);
    public int removeOfPathAndUserIds(String path, String userIds);
    public int removeOfPathAndSignature(String path, String signature);
    public int removeOfPathAndImage(String path, String image);
    public int removeOfPathAndFamous(String path, String famous);
    public int removeOfPathAndBUserIds(String path, String bUserIds);
    public int removeOfPathAndDays(String path, String days);
    public int removeOfPathAndNowDays(String path, String nowDays);
    public int removeOfParamAndLvl(String param, String lvl);
    public int removeOfParamAndNewIds(String param, String newIds);
    public int removeOfParamAndUserIds(String param, String userIds);
    public int removeOfParamAndSignature(String param, String signature);
    public int removeOfParamAndImage(String param, String image);
    public int removeOfParamAndFamous(String param, String famous);
    public int removeOfParamAndBUserIds(String param, String bUserIds);
    public int removeOfParamAndDays(String param, String days);
    public int removeOfParamAndNowDays(String param, String nowDays);
    public int removeOfLvlAndNewIds(String lvl, String newIds);
    public int removeOfLvlAndUserIds(String lvl, String userIds);
    public int removeOfLvlAndSignature(String lvl, String signature);
    public int removeOfLvlAndImage(String lvl, String image);
    public int removeOfLvlAndFamous(String lvl, String famous);
    public int removeOfLvlAndBUserIds(String lvl, String bUserIds);
    public int removeOfLvlAndDays(String lvl, String days);
    public int removeOfLvlAndNowDays(String lvl, String nowDays);
    public int removeOfNewIdsAndUserIds(String newIds, String userIds);
    public int removeOfNewIdsAndSignature(String newIds, String signature);
    public int removeOfNewIdsAndImage(String newIds, String image);
    public int removeOfNewIdsAndFamous(String newIds, String famous);
    public int removeOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public int removeOfNewIdsAndDays(String newIds, String days);
    public int removeOfNewIdsAndNowDays(String newIds, String nowDays);
    public int removeOfUserIdsAndSignature(String userIds, String signature);
    public int removeOfUserIdsAndImage(String userIds, String image);
    public int removeOfUserIdsAndFamous(String userIds, String famous);
    public int removeOfUserIdsAndBUserIds(String userIds, String bUserIds);
    public int removeOfUserIdsAndDays(String userIds, String days);
    public int removeOfUserIdsAndNowDays(String userIds, String nowDays);
    public int removeOfSignatureAndImage(String signature, String image);
    public int removeOfSignatureAndFamous(String signature, String famous);
    public int removeOfSignatureAndBUserIds(String signature, String bUserIds);
    public int removeOfSignatureAndDays(String signature, String days);
    public int removeOfSignatureAndNowDays(String signature, String nowDays);
    public int removeOfImageAndFamous(String image, String famous);
    public int removeOfImageAndBUserIds(String image, String bUserIds);
    public int removeOfImageAndDays(String image, String days);
    public int removeOfImageAndNowDays(String image, String nowDays);
    public int removeOfFamousAndBUserIds(String famous, String bUserIds);
    public int removeOfFamousAndDays(String famous, String days);
    public int removeOfFamousAndNowDays(String famous, String nowDays);
    public int removeOfBUserIdsAndDays(String bUserIds, String days);
    public int removeOfBUserIdsAndNowDays(String bUserIds, String nowDays);
    public int removeOfDaysAndNowDays(String days, String nowDays);
    public int insert(User user);
    public int insertOfUserId(String userId);
    public int insertOfPassword(String password);
    public int insertOfName(String name);
    public int insertOfSex(String sex);
    public int insertOfRegisterDate(String registerDate);
    public int insertOfLoginDate(String loginDate);
    public int insertOfPhone(String phone);
    public int insertOfEmail(String email);
    public int insertOfMoney(String money);
    public int insertOfScore(String score);
    public int insertOfPath(String path);
    public int insertOfParam(String param);
    public int insertOfLvl(String lvl);
    public int insertOfNewIds(String newIds);
    public int insertOfUserIds(String userIds);
    public int insertOfSignature(String signature);
    public int insertOfImage(String image);
    public int insertOfFamous(String famous);
    public int insertOfBUserIds(String bUserIds);
    public int insertOfDays(String days);
    public int insertOfNowDays(String nowDays);
    public int insertOfUserIdAndPassword(String userId, String password);
    public int insertOfUserIdAndName(String userId, String name);
    public int insertOfUserIdAndSex(String userId, String sex);
    public int insertOfUserIdAndRegisterDate(String userId, String registerDate);
    public int insertOfUserIdAndLoginDate(String userId, String loginDate);
    public int insertOfUserIdAndPhone(String userId, String phone);
    public int insertOfUserIdAndEmail(String userId, String email);
    public int insertOfUserIdAndMoney(String userId, String money);
    public int insertOfUserIdAndScore(String userId, String score);
    public int insertOfUserIdAndPath(String userId, String path);
    public int insertOfUserIdAndParam(String userId, String param);
    public int insertOfUserIdAndLvl(String userId, String lvl);
    public int insertOfUserIdAndNewIds(String userId, String newIds);
    public int insertOfUserIdAndUserIds(String userId, String userIds);
    public int insertOfUserIdAndSignature(String userId, String signature);
    public int insertOfUserIdAndImage(String userId, String image);
    public int insertOfUserIdAndFamous(String userId, String famous);
    public int insertOfUserIdAndBUserIds(String userId, String bUserIds);
    public int insertOfUserIdAndDays(String userId, String days);
    public int insertOfUserIdAndNowDays(String userId, String nowDays);
    public int insertOfPasswordAndName(String password, String name);
    public int insertOfPasswordAndSex(String password, String sex);
    public int insertOfPasswordAndRegisterDate(String password, String registerDate);
    public int insertOfPasswordAndLoginDate(String password, String loginDate);
    public int insertOfPasswordAndPhone(String password, String phone);
    public int insertOfPasswordAndEmail(String password, String email);
    public int insertOfPasswordAndMoney(String password, String money);
    public int insertOfPasswordAndScore(String password, String score);
    public int insertOfPasswordAndPath(String password, String path);
    public int insertOfPasswordAndParam(String password, String param);
    public int insertOfPasswordAndLvl(String password, String lvl);
    public int insertOfPasswordAndNewIds(String password, String newIds);
    public int insertOfPasswordAndUserIds(String password, String userIds);
    public int insertOfPasswordAndSignature(String password, String signature);
    public int insertOfPasswordAndImage(String password, String image);
    public int insertOfPasswordAndFamous(String password, String famous);
    public int insertOfPasswordAndBUserIds(String password, String bUserIds);
    public int insertOfPasswordAndDays(String password, String days);
    public int insertOfPasswordAndNowDays(String password, String nowDays);
    public int insertOfNameAndSex(String name, String sex);
    public int insertOfNameAndRegisterDate(String name, String registerDate);
    public int insertOfNameAndLoginDate(String name, String loginDate);
    public int insertOfNameAndPhone(String name, String phone);
    public int insertOfNameAndEmail(String name, String email);
    public int insertOfNameAndMoney(String name, String money);
    public int insertOfNameAndScore(String name, String score);
    public int insertOfNameAndPath(String name, String path);
    public int insertOfNameAndParam(String name, String param);
    public int insertOfNameAndLvl(String name, String lvl);
    public int insertOfNameAndNewIds(String name, String newIds);
    public int insertOfNameAndUserIds(String name, String userIds);
    public int insertOfNameAndSignature(String name, String signature);
    public int insertOfNameAndImage(String name, String image);
    public int insertOfNameAndFamous(String name, String famous);
    public int insertOfNameAndBUserIds(String name, String bUserIds);
    public int insertOfNameAndDays(String name, String days);
    public int insertOfNameAndNowDays(String name, String nowDays);
    public int insertOfSexAndRegisterDate(String sex, String registerDate);
    public int insertOfSexAndLoginDate(String sex, String loginDate);
    public int insertOfSexAndPhone(String sex, String phone);
    public int insertOfSexAndEmail(String sex, String email);
    public int insertOfSexAndMoney(String sex, String money);
    public int insertOfSexAndScore(String sex, String score);
    public int insertOfSexAndPath(String sex, String path);
    public int insertOfSexAndParam(String sex, String param);
    public int insertOfSexAndLvl(String sex, String lvl);
    public int insertOfSexAndNewIds(String sex, String newIds);
    public int insertOfSexAndUserIds(String sex, String userIds);
    public int insertOfSexAndSignature(String sex, String signature);
    public int insertOfSexAndImage(String sex, String image);
    public int insertOfSexAndFamous(String sex, String famous);
    public int insertOfSexAndBUserIds(String sex, String bUserIds);
    public int insertOfSexAndDays(String sex, String days);
    public int insertOfSexAndNowDays(String sex, String nowDays);
    public int insertOfRegisterDateAndLoginDate(String registerDate, String loginDate);
    public int insertOfRegisterDateAndPhone(String registerDate, String phone);
    public int insertOfRegisterDateAndEmail(String registerDate, String email);
    public int insertOfRegisterDateAndMoney(String registerDate, String money);
    public int insertOfRegisterDateAndScore(String registerDate, String score);
    public int insertOfRegisterDateAndPath(String registerDate, String path);
    public int insertOfRegisterDateAndParam(String registerDate, String param);
    public int insertOfRegisterDateAndLvl(String registerDate, String lvl);
    public int insertOfRegisterDateAndNewIds(String registerDate, String newIds);
    public int insertOfRegisterDateAndUserIds(String registerDate, String userIds);
    public int insertOfRegisterDateAndSignature(String registerDate, String signature);
    public int insertOfRegisterDateAndImage(String registerDate, String image);
    public int insertOfRegisterDateAndFamous(String registerDate, String famous);
    public int insertOfRegisterDateAndBUserIds(String registerDate, String bUserIds);
    public int insertOfRegisterDateAndDays(String registerDate, String days);
    public int insertOfRegisterDateAndNowDays(String registerDate, String nowDays);
    public int insertOfLoginDateAndPhone(String loginDate, String phone);
    public int insertOfLoginDateAndEmail(String loginDate, String email);
    public int insertOfLoginDateAndMoney(String loginDate, String money);
    public int insertOfLoginDateAndScore(String loginDate, String score);
    public int insertOfLoginDateAndPath(String loginDate, String path);
    public int insertOfLoginDateAndParam(String loginDate, String param);
    public int insertOfLoginDateAndLvl(String loginDate, String lvl);
    public int insertOfLoginDateAndNewIds(String loginDate, String newIds);
    public int insertOfLoginDateAndUserIds(String loginDate, String userIds);
    public int insertOfLoginDateAndSignature(String loginDate, String signature);
    public int insertOfLoginDateAndImage(String loginDate, String image);
    public int insertOfLoginDateAndFamous(String loginDate, String famous);
    public int insertOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public int insertOfLoginDateAndDays(String loginDate, String days);
    public int insertOfLoginDateAndNowDays(String loginDate, String nowDays);
    public int insertOfPhoneAndEmail(String phone, String email);
    public int insertOfPhoneAndMoney(String phone, String money);
    public int insertOfPhoneAndScore(String phone, String score);
    public int insertOfPhoneAndPath(String phone, String path);
    public int insertOfPhoneAndParam(String phone, String param);
    public int insertOfPhoneAndLvl(String phone, String lvl);
    public int insertOfPhoneAndNewIds(String phone, String newIds);
    public int insertOfPhoneAndUserIds(String phone, String userIds);
    public int insertOfPhoneAndSignature(String phone, String signature);
    public int insertOfPhoneAndImage(String phone, String image);
    public int insertOfPhoneAndFamous(String phone, String famous);
    public int insertOfPhoneAndBUserIds(String phone, String bUserIds);
    public int insertOfPhoneAndDays(String phone, String days);
    public int insertOfPhoneAndNowDays(String phone, String nowDays);
    public int insertOfEmailAndMoney(String email, String money);
    public int insertOfEmailAndScore(String email, String score);
    public int insertOfEmailAndPath(String email, String path);
    public int insertOfEmailAndParam(String email, String param);
    public int insertOfEmailAndLvl(String email, String lvl);
    public int insertOfEmailAndNewIds(String email, String newIds);
    public int insertOfEmailAndUserIds(String email, String userIds);
    public int insertOfEmailAndSignature(String email, String signature);
    public int insertOfEmailAndImage(String email, String image);
    public int insertOfEmailAndFamous(String email, String famous);
    public int insertOfEmailAndBUserIds(String email, String bUserIds);
    public int insertOfEmailAndDays(String email, String days);
    public int insertOfEmailAndNowDays(String email, String nowDays);
    public int insertOfMoneyAndScore(String money, String score);
    public int insertOfMoneyAndPath(String money, String path);
    public int insertOfMoneyAndParam(String money, String param);
    public int insertOfMoneyAndLvl(String money, String lvl);
    public int insertOfMoneyAndNewIds(String money, String newIds);
    public int insertOfMoneyAndUserIds(String money, String userIds);
    public int insertOfMoneyAndSignature(String money, String signature);
    public int insertOfMoneyAndImage(String money, String image);
    public int insertOfMoneyAndFamous(String money, String famous);
    public int insertOfMoneyAndBUserIds(String money, String bUserIds);
    public int insertOfMoneyAndDays(String money, String days);
    public int insertOfMoneyAndNowDays(String money, String nowDays);
    public int insertOfScoreAndPath(String score, String path);
    public int insertOfScoreAndParam(String score, String param);
    public int insertOfScoreAndLvl(String score, String lvl);
    public int insertOfScoreAndNewIds(String score, String newIds);
    public int insertOfScoreAndUserIds(String score, String userIds);
    public int insertOfScoreAndSignature(String score, String signature);
    public int insertOfScoreAndImage(String score, String image);
    public int insertOfScoreAndFamous(String score, String famous);
    public int insertOfScoreAndBUserIds(String score, String bUserIds);
    public int insertOfScoreAndDays(String score, String days);
    public int insertOfScoreAndNowDays(String score, String nowDays);
    public int insertOfPathAndParam(String path, String param);
    public int insertOfPathAndLvl(String path, String lvl);
    public int insertOfPathAndNewIds(String path, String newIds);
    public int insertOfPathAndUserIds(String path, String userIds);
    public int insertOfPathAndSignature(String path, String signature);
    public int insertOfPathAndImage(String path, String image);
    public int insertOfPathAndFamous(String path, String famous);
    public int insertOfPathAndBUserIds(String path, String bUserIds);
    public int insertOfPathAndDays(String path, String days);
    public int insertOfPathAndNowDays(String path, String nowDays);
    public int insertOfParamAndLvl(String param, String lvl);
    public int insertOfParamAndNewIds(String param, String newIds);
    public int insertOfParamAndUserIds(String param, String userIds);
    public int insertOfParamAndSignature(String param, String signature);
    public int insertOfParamAndImage(String param, String image);
    public int insertOfParamAndFamous(String param, String famous);
    public int insertOfParamAndBUserIds(String param, String bUserIds);
    public int insertOfParamAndDays(String param, String days);
    public int insertOfParamAndNowDays(String param, String nowDays);
    public int insertOfLvlAndNewIds(String lvl, String newIds);
    public int insertOfLvlAndUserIds(String lvl, String userIds);
    public int insertOfLvlAndSignature(String lvl, String signature);
    public int insertOfLvlAndImage(String lvl, String image);
    public int insertOfLvlAndFamous(String lvl, String famous);
    public int insertOfLvlAndBUserIds(String lvl, String bUserIds);
    public int insertOfLvlAndDays(String lvl, String days);
    public int insertOfLvlAndNowDays(String lvl, String nowDays);
    public int insertOfNewIdsAndUserIds(String newIds, String userIds);
    public int insertOfNewIdsAndSignature(String newIds, String signature);
    public int insertOfNewIdsAndImage(String newIds, String image);
    public int insertOfNewIdsAndFamous(String newIds, String famous);
    public int insertOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public int insertOfNewIdsAndDays(String newIds, String days);
    public int insertOfNewIdsAndNowDays(String newIds, String nowDays);
    public int insertOfUserIdsAndSignature(String userIds, String signature);
    public int insertOfUserIdsAndImage(String userIds, String image);
    public int insertOfUserIdsAndFamous(String userIds, String famous);
    public int insertOfUserIdsAndBUserIds(String userIds, String bUserIds);
    public int insertOfUserIdsAndDays(String userIds, String days);
    public int insertOfUserIdsAndNowDays(String userIds, String nowDays);
    public int insertOfSignatureAndImage(String signature, String image);
    public int insertOfSignatureAndFamous(String signature, String famous);
    public int insertOfSignatureAndBUserIds(String signature, String bUserIds);
    public int insertOfSignatureAndDays(String signature, String days);
    public int insertOfSignatureAndNowDays(String signature, String nowDays);
    public int insertOfImageAndFamous(String image, String famous);
    public int insertOfImageAndBUserIds(String image, String bUserIds);
    public int insertOfImageAndDays(String image, String days);
    public int insertOfImageAndNowDays(String image, String nowDays);
    public int insertOfFamousAndBUserIds(String famous, String bUserIds);
    public int insertOfFamousAndDays(String famous, String days);
    public int insertOfFamousAndNowDays(String famous, String nowDays);
    public int insertOfBUserIdsAndDays(String bUserIds, String days);
    public int insertOfBUserIdsAndNowDays(String bUserIds, String nowDays);
    public int insertOfDaysAndNowDays(String days, String nowDays);
    public User getUser(User user);
    public User getUserOfUserId(String userId);
    public User getUserOfPassword(String password);
    public User getUserOfName(String name);
    public User getUserOfSex(String sex);
    public User getUserOfRegisterDate(String registerDate);
    public User getUserOfLoginDate(String loginDate);
    public User getUserOfPhone(String phone);
    public User getUserOfEmail(String email);
    public User getUserOfMoney(String money);
    public User getUserOfScore(String score);
    public User getUserOfPath(String path);
    public User getUserOfParam(String param);
    public User getUserOfLvl(String lvl);
    public User getUserOfNewIds(String newIds);
    public User getUserOfUserIds(String userIds);
    public User getUserOfSignature(String signature);
    public User getUserOfImage(String image);
    public User getUserOfFamous(String famous);
    public User getUserOfBUserIds(String bUserIds);
    public User getUserOfDays(String days);
    public User getUserOfNowDays(String nowDays);
    public User getUserOfUserIdAndPassword(String userId, String password);
    public User getUserOfUserIdAndName(String userId, String name);
    public User getUserOfUserIdAndSex(String userId, String sex);
    public User getUserOfUserIdAndRegisterDate(String userId, String registerDate);
    public User getUserOfUserIdAndLoginDate(String userId, String loginDate);
    public User getUserOfUserIdAndPhone(String userId, String phone);
    public User getUserOfUserIdAndEmail(String userId, String email);
    public User getUserOfUserIdAndMoney(String userId, String money);
    public User getUserOfUserIdAndScore(String userId, String score);
    public User getUserOfUserIdAndPath(String userId, String path);
    public User getUserOfUserIdAndParam(String userId, String param);
    public User getUserOfUserIdAndLvl(String userId, String lvl);
    public User getUserOfUserIdAndNewIds(String userId, String newIds);
    public User getUserOfUserIdAndUserIds(String userId, String userIds);
    public User getUserOfUserIdAndSignature(String userId, String signature);
    public User getUserOfUserIdAndImage(String userId, String image);
    public User getUserOfUserIdAndFamous(String userId, String famous);
    public User getUserOfUserIdAndBUserIds(String userId, String bUserIds);
    public User getUserOfUserIdAndDays(String userId, String days);
    public User getUserOfUserIdAndNowDays(String userId, String nowDays);
    public User getUserOfPasswordAndName(String password, String name);
    public User getUserOfPasswordAndSex(String password, String sex);
    public User getUserOfPasswordAndRegisterDate(String password, String registerDate);
    public User getUserOfPasswordAndLoginDate(String password, String loginDate);
    public User getUserOfPasswordAndPhone(String password, String phone);
    public User getUserOfPasswordAndEmail(String password, String email);
    public User getUserOfPasswordAndMoney(String password, String money);
    public User getUserOfPasswordAndScore(String password, String score);
    public User getUserOfPasswordAndPath(String password, String path);
    public User getUserOfPasswordAndParam(String password, String param);
    public User getUserOfPasswordAndLvl(String password, String lvl);
    public User getUserOfPasswordAndNewIds(String password, String newIds);
    public User getUserOfPasswordAndUserIds(String password, String userIds);
    public User getUserOfPasswordAndSignature(String password, String signature);
    public User getUserOfPasswordAndImage(String password, String image);
    public User getUserOfPasswordAndFamous(String password, String famous);
    public User getUserOfPasswordAndBUserIds(String password, String bUserIds);
    public User getUserOfPasswordAndDays(String password, String days);
    public User getUserOfPasswordAndNowDays(String password, String nowDays);
    public User getUserOfNameAndSex(String name, String sex);
    public User getUserOfNameAndRegisterDate(String name, String registerDate);
    public User getUserOfNameAndLoginDate(String name, String loginDate);
    public User getUserOfNameAndPhone(String name, String phone);
    public User getUserOfNameAndEmail(String name, String email);
    public User getUserOfNameAndMoney(String name, String money);
    public User getUserOfNameAndScore(String name, String score);
    public User getUserOfNameAndPath(String name, String path);
    public User getUserOfNameAndParam(String name, String param);
    public User getUserOfNameAndLvl(String name, String lvl);
    public User getUserOfNameAndNewIds(String name, String newIds);
    public User getUserOfNameAndUserIds(String name, String userIds);
    public User getUserOfNameAndSignature(String name, String signature);
    public User getUserOfNameAndImage(String name, String image);
    public User getUserOfNameAndFamous(String name, String famous);
    public User getUserOfNameAndBUserIds(String name, String bUserIds);
    public User getUserOfNameAndDays(String name, String days);
    public User getUserOfNameAndNowDays(String name, String nowDays);
    public User getUserOfSexAndRegisterDate(String sex, String registerDate);
    public User getUserOfSexAndLoginDate(String sex, String loginDate);
    public User getUserOfSexAndPhone(String sex, String phone);
    public User getUserOfSexAndEmail(String sex, String email);
    public User getUserOfSexAndMoney(String sex, String money);
    public User getUserOfSexAndScore(String sex, String score);
    public User getUserOfSexAndPath(String sex, String path);
    public User getUserOfSexAndParam(String sex, String param);
    public User getUserOfSexAndLvl(String sex, String lvl);
    public User getUserOfSexAndNewIds(String sex, String newIds);
    public User getUserOfSexAndUserIds(String sex, String userIds);
    public User getUserOfSexAndSignature(String sex, String signature);
    public User getUserOfSexAndImage(String sex, String image);
    public User getUserOfSexAndFamous(String sex, String famous);
    public User getUserOfSexAndBUserIds(String sex, String bUserIds);
    public User getUserOfSexAndDays(String sex, String days);
    public User getUserOfSexAndNowDays(String sex, String nowDays);
    public User getUserOfRegisterDateAndLoginDate(String registerDate, String loginDate);
    public User getUserOfRegisterDateAndPhone(String registerDate, String phone);
    public User getUserOfRegisterDateAndEmail(String registerDate, String email);
    public User getUserOfRegisterDateAndMoney(String registerDate, String money);
    public User getUserOfRegisterDateAndScore(String registerDate, String score);
    public User getUserOfRegisterDateAndPath(String registerDate, String path);
    public User getUserOfRegisterDateAndParam(String registerDate, String param);
    public User getUserOfRegisterDateAndLvl(String registerDate, String lvl);
    public User getUserOfRegisterDateAndNewIds(String registerDate, String newIds);
    public User getUserOfRegisterDateAndUserIds(String registerDate, String userIds);
    public User getUserOfRegisterDateAndSignature(String registerDate, String signature);
    public User getUserOfRegisterDateAndImage(String registerDate, String image);
    public User getUserOfRegisterDateAndFamous(String registerDate, String famous);
    public User getUserOfRegisterDateAndBUserIds(String registerDate, String bUserIds);
    public User getUserOfRegisterDateAndDays(String registerDate, String days);
    public User getUserOfRegisterDateAndNowDays(String registerDate, String nowDays);
    public User getUserOfLoginDateAndPhone(String loginDate, String phone);
    public User getUserOfLoginDateAndEmail(String loginDate, String email);
    public User getUserOfLoginDateAndMoney(String loginDate, String money);
    public User getUserOfLoginDateAndScore(String loginDate, String score);
    public User getUserOfLoginDateAndPath(String loginDate, String path);
    public User getUserOfLoginDateAndParam(String loginDate, String param);
    public User getUserOfLoginDateAndLvl(String loginDate, String lvl);
    public User getUserOfLoginDateAndNewIds(String loginDate, String newIds);
    public User getUserOfLoginDateAndUserIds(String loginDate, String userIds);
    public User getUserOfLoginDateAndSignature(String loginDate, String signature);
    public User getUserOfLoginDateAndImage(String loginDate, String image);
    public User getUserOfLoginDateAndFamous(String loginDate, String famous);
    public User getUserOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public User getUserOfLoginDateAndDays(String loginDate, String days);
    public User getUserOfLoginDateAndNowDays(String loginDate, String nowDays);
    public User getUserOfPhoneAndEmail(String phone, String email);
    public User getUserOfPhoneAndMoney(String phone, String money);
    public User getUserOfPhoneAndScore(String phone, String score);
    public User getUserOfPhoneAndPath(String phone, String path);
    public User getUserOfPhoneAndParam(String phone, String param);
    public User getUserOfPhoneAndLvl(String phone, String lvl);
    public User getUserOfPhoneAndNewIds(String phone, String newIds);
    public User getUserOfPhoneAndUserIds(String phone, String userIds);
    public User getUserOfPhoneAndSignature(String phone, String signature);
    public User getUserOfPhoneAndImage(String phone, String image);
    public User getUserOfPhoneAndFamous(String phone, String famous);
    public User getUserOfPhoneAndBUserIds(String phone, String bUserIds);
    public User getUserOfPhoneAndDays(String phone, String days);
    public User getUserOfPhoneAndNowDays(String phone, String nowDays);
    public User getUserOfEmailAndMoney(String email, String money);
    public User getUserOfEmailAndScore(String email, String score);
    public User getUserOfEmailAndPath(String email, String path);
    public User getUserOfEmailAndParam(String email, String param);
    public User getUserOfEmailAndLvl(String email, String lvl);
    public User getUserOfEmailAndNewIds(String email, String newIds);
    public User getUserOfEmailAndUserIds(String email, String userIds);
    public User getUserOfEmailAndSignature(String email, String signature);
    public User getUserOfEmailAndImage(String email, String image);
    public User getUserOfEmailAndFamous(String email, String famous);
    public User getUserOfEmailAndBUserIds(String email, String bUserIds);
    public User getUserOfEmailAndDays(String email, String days);
    public User getUserOfEmailAndNowDays(String email, String nowDays);
    public User getUserOfMoneyAndScore(String money, String score);
    public User getUserOfMoneyAndPath(String money, String path);
    public User getUserOfMoneyAndParam(String money, String param);
    public User getUserOfMoneyAndLvl(String money, String lvl);
    public User getUserOfMoneyAndNewIds(String money, String newIds);
    public User getUserOfMoneyAndUserIds(String money, String userIds);
    public User getUserOfMoneyAndSignature(String money, String signature);
    public User getUserOfMoneyAndImage(String money, String image);
    public User getUserOfMoneyAndFamous(String money, String famous);
    public User getUserOfMoneyAndBUserIds(String money, String bUserIds);
    public User getUserOfMoneyAndDays(String money, String days);
    public User getUserOfMoneyAndNowDays(String money, String nowDays);
    public User getUserOfScoreAndPath(String score, String path);
    public User getUserOfScoreAndParam(String score, String param);
    public User getUserOfScoreAndLvl(String score, String lvl);
    public User getUserOfScoreAndNewIds(String score, String newIds);
    public User getUserOfScoreAndUserIds(String score, String userIds);
    public User getUserOfScoreAndSignature(String score, String signature);
    public User getUserOfScoreAndImage(String score, String image);
    public User getUserOfScoreAndFamous(String score, String famous);
    public User getUserOfScoreAndBUserIds(String score, String bUserIds);
    public User getUserOfScoreAndDays(String score, String days);
    public User getUserOfScoreAndNowDays(String score, String nowDays);
    public User getUserOfPathAndParam(String path, String param);
    public User getUserOfPathAndLvl(String path, String lvl);
    public User getUserOfPathAndNewIds(String path, String newIds);
    public User getUserOfPathAndUserIds(String path, String userIds);
    public User getUserOfPathAndSignature(String path, String signature);
    public User getUserOfPathAndImage(String path, String image);
    public User getUserOfPathAndFamous(String path, String famous);
    public User getUserOfPathAndBUserIds(String path, String bUserIds);
    public User getUserOfPathAndDays(String path, String days);
    public User getUserOfPathAndNowDays(String path, String nowDays);
    public User getUserOfParamAndLvl(String param, String lvl);
    public User getUserOfParamAndNewIds(String param, String newIds);
    public User getUserOfParamAndUserIds(String param, String userIds);
    public User getUserOfParamAndSignature(String param, String signature);
    public User getUserOfParamAndImage(String param, String image);
    public User getUserOfParamAndFamous(String param, String famous);
    public User getUserOfParamAndBUserIds(String param, String bUserIds);
    public User getUserOfParamAndDays(String param, String days);
    public User getUserOfParamAndNowDays(String param, String nowDays);
    public User getUserOfLvlAndNewIds(String lvl, String newIds);
    public User getUserOfLvlAndUserIds(String lvl, String userIds);
    public User getUserOfLvlAndSignature(String lvl, String signature);
    public User getUserOfLvlAndImage(String lvl, String image);
    public User getUserOfLvlAndFamous(String lvl, String famous);
    public User getUserOfLvlAndBUserIds(String lvl, String bUserIds);
    public User getUserOfLvlAndDays(String lvl, String days);
    public User getUserOfLvlAndNowDays(String lvl, String nowDays);
    public User getUserOfNewIdsAndUserIds(String newIds, String userIds);
    public User getUserOfNewIdsAndSignature(String newIds, String signature);
    public User getUserOfNewIdsAndImage(String newIds, String image);
    public User getUserOfNewIdsAndFamous(String newIds, String famous);
    public User getUserOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public User getUserOfNewIdsAndDays(String newIds, String days);
    public User getUserOfNewIdsAndNowDays(String newIds, String nowDays);
    public User getUserOfUserIdsAndSignature(String userIds, String signature);
    public User getUserOfUserIdsAndImage(String userIds, String image);
    public User getUserOfUserIdsAndFamous(String userIds, String famous);
    public User getUserOfUserIdsAndBUserIds(String userIds, String bUserIds);
    public User getUserOfUserIdsAndDays(String userIds, String days);
    public User getUserOfUserIdsAndNowDays(String userIds, String nowDays);
    public User getUserOfSignatureAndImage(String signature, String image);
    public User getUserOfSignatureAndFamous(String signature, String famous);
    public User getUserOfSignatureAndBUserIds(String signature, String bUserIds);
    public User getUserOfSignatureAndDays(String signature, String days);
    public User getUserOfSignatureAndNowDays(String signature, String nowDays);
    public User getUserOfImageAndFamous(String image, String famous);
    public User getUserOfImageAndBUserIds(String image, String bUserIds);
    public User getUserOfImageAndDays(String image, String days);
    public User getUserOfImageAndNowDays(String image, String nowDays);
    public User getUserOfFamousAndBUserIds(String famous, String bUserIds);
    public User getUserOfFamousAndDays(String famous, String days);
    public User getUserOfFamousAndNowDays(String famous, String nowDays);
    public User getUserOfBUserIdsAndDays(String bUserIds, String days);
    public User getUserOfBUserIdsAndNowDays(String bUserIds, String nowDays);
    public User getUserOfDaysAndNowDays(String days, String nowDays);
    public List<User> getUsers(User user);
    public List<User> getUsersOfUserId(String userId);
    public List<User> getUsersOfPassword(String password);
    public List<User> getUsersOfName(String name);
    public List<User> getUsersOfSex(String sex);
    public List<User> getUsersOfRegisterDate(String registerDate);
    public List<User> getUsersOfLoginDate(String loginDate);
    public List<User> getUsersOfPhone(String phone);
    public List<User> getUsersOfEmail(String email);
    public List<User> getUsersOfMoney(String money);
    public List<User> getUsersOfScore(String score);
    public List<User> getUsersOfPath(String path);
    public List<User> getUsersOfParam(String param);
    public List<User> getUsersOfLvl(String lvl);
    public List<User> getUsersOfNewIds(String newIds);
    public List<User> getUsersOfUserIds(String userIds);
    public List<User> getUsersOfSignature(String signature);
    public List<User> getUsersOfImage(String image);
    public List<User> getUsersOfFamous(String famous);
    public List<User> getUsersOfBUserIds(String bUserIds);
    public List<User> getUsersOfDays(String days);
    public List<User> getUsersOfNowDays(String nowDays);
    public List<User> getUsersOfUserIdAndPassword(String userId, String password);
    public List<User> getUsersOfUserIdAndName(String userId, String name);
    public List<User> getUsersOfUserIdAndSex(String userId, String sex);
    public List<User> getUsersOfUserIdAndRegisterDate(String userId, String registerDate);
    public List<User> getUsersOfUserIdAndLoginDate(String userId, String loginDate);
    public List<User> getUsersOfUserIdAndPhone(String userId, String phone);
    public List<User> getUsersOfUserIdAndEmail(String userId, String email);
    public List<User> getUsersOfUserIdAndMoney(String userId, String money);
    public List<User> getUsersOfUserIdAndScore(String userId, String score);
    public List<User> getUsersOfUserIdAndPath(String userId, String path);
    public List<User> getUsersOfUserIdAndParam(String userId, String param);
    public List<User> getUsersOfUserIdAndLvl(String userId, String lvl);
    public List<User> getUsersOfUserIdAndNewIds(String userId, String newIds);
    public List<User> getUsersOfUserIdAndUserIds(String userId, String userIds);
    public List<User> getUsersOfUserIdAndSignature(String userId, String signature);
    public List<User> getUsersOfUserIdAndImage(String userId, String image);
    public List<User> getUsersOfUserIdAndFamous(String userId, String famous);
    public List<User> getUsersOfUserIdAndBUserIds(String userId, String bUserIds);
    public List<User> getUsersOfUserIdAndDays(String userId, String days);
    public List<User> getUsersOfUserIdAndNowDays(String userId, String nowDays);
    public List<User> getUsersOfPasswordAndName(String password, String name);
    public List<User> getUsersOfPasswordAndSex(String password, String sex);
    public List<User> getUsersOfPasswordAndRegisterDate(String password, String registerDate);
    public List<User> getUsersOfPasswordAndLoginDate(String password, String loginDate);
    public List<User> getUsersOfPasswordAndPhone(String password, String phone);
    public List<User> getUsersOfPasswordAndEmail(String password, String email);
    public List<User> getUsersOfPasswordAndMoney(String password, String money);
    public List<User> getUsersOfPasswordAndScore(String password, String score);
    public List<User> getUsersOfPasswordAndPath(String password, String path);
    public List<User> getUsersOfPasswordAndParam(String password, String param);
    public List<User> getUsersOfPasswordAndLvl(String password, String lvl);
    public List<User> getUsersOfPasswordAndNewIds(String password, String newIds);
    public List<User> getUsersOfPasswordAndUserIds(String password, String userIds);
    public List<User> getUsersOfPasswordAndSignature(String password, String signature);
    public List<User> getUsersOfPasswordAndImage(String password, String image);
    public List<User> getUsersOfPasswordAndFamous(String password, String famous);
    public List<User> getUsersOfPasswordAndBUserIds(String password, String bUserIds);
    public List<User> getUsersOfPasswordAndDays(String password, String days);
    public List<User> getUsersOfPasswordAndNowDays(String password, String nowDays);
    public List<User> getUsersOfNameAndSex(String name, String sex);
    public List<User> getUsersOfNameAndRegisterDate(String name, String registerDate);
    public List<User> getUsersOfNameAndLoginDate(String name, String loginDate);
    public List<User> getUsersOfNameAndPhone(String name, String phone);
    public List<User> getUsersOfNameAndEmail(String name, String email);
    public List<User> getUsersOfNameAndMoney(String name, String money);
    public List<User> getUsersOfNameAndScore(String name, String score);
    public List<User> getUsersOfNameAndPath(String name, String path);
    public List<User> getUsersOfNameAndParam(String name, String param);
    public List<User> getUsersOfNameAndLvl(String name, String lvl);
    public List<User> getUsersOfNameAndNewIds(String name, String newIds);
    public List<User> getUsersOfNameAndUserIds(String name, String userIds);
    public List<User> getUsersOfNameAndSignature(String name, String signature);
    public List<User> getUsersOfNameAndImage(String name, String image);
    public List<User> getUsersOfNameAndFamous(String name, String famous);
    public List<User> getUsersOfNameAndBUserIds(String name, String bUserIds);
    public List<User> getUsersOfNameAndDays(String name, String days);
    public List<User> getUsersOfNameAndNowDays(String name, String nowDays);
    public List<User> getUsersOfSexAndRegisterDate(String sex, String registerDate);
    public List<User> getUsersOfSexAndLoginDate(String sex, String loginDate);
    public List<User> getUsersOfSexAndPhone(String sex, String phone);
    public List<User> getUsersOfSexAndEmail(String sex, String email);
    public List<User> getUsersOfSexAndMoney(String sex, String money);
    public List<User> getUsersOfSexAndScore(String sex, String score);
    public List<User> getUsersOfSexAndPath(String sex, String path);
    public List<User> getUsersOfSexAndParam(String sex, String param);
    public List<User> getUsersOfSexAndLvl(String sex, String lvl);
    public List<User> getUsersOfSexAndNewIds(String sex, String newIds);
    public List<User> getUsersOfSexAndUserIds(String sex, String userIds);
    public List<User> getUsersOfSexAndSignature(String sex, String signature);
    public List<User> getUsersOfSexAndImage(String sex, String image);
    public List<User> getUsersOfSexAndFamous(String sex, String famous);
    public List<User> getUsersOfSexAndBUserIds(String sex, String bUserIds);
    public List<User> getUsersOfSexAndDays(String sex, String days);
    public List<User> getUsersOfSexAndNowDays(String sex, String nowDays);
    public List<User> getUsersOfRegisterDateAndLoginDate(String registerDate, String loginDate);
    public List<User> getUsersOfRegisterDateAndPhone(String registerDate, String phone);
    public List<User> getUsersOfRegisterDateAndEmail(String registerDate, String email);
    public List<User> getUsersOfRegisterDateAndMoney(String registerDate, String money);
    public List<User> getUsersOfRegisterDateAndScore(String registerDate, String score);
    public List<User> getUsersOfRegisterDateAndPath(String registerDate, String path);
    public List<User> getUsersOfRegisterDateAndParam(String registerDate, String param);
    public List<User> getUsersOfRegisterDateAndLvl(String registerDate, String lvl);
    public List<User> getUsersOfRegisterDateAndNewIds(String registerDate, String newIds);
    public List<User> getUsersOfRegisterDateAndUserIds(String registerDate, String userIds);
    public List<User> getUsersOfRegisterDateAndSignature(String registerDate, String signature);
    public List<User> getUsersOfRegisterDateAndImage(String registerDate, String image);
    public List<User> getUsersOfRegisterDateAndFamous(String registerDate, String famous);
    public List<User> getUsersOfRegisterDateAndBUserIds(String registerDate, String bUserIds);
    public List<User> getUsersOfRegisterDateAndDays(String registerDate, String days);
    public List<User> getUsersOfRegisterDateAndNowDays(String registerDate, String nowDays);
    public List<User> getUsersOfLoginDateAndPhone(String loginDate, String phone);
    public List<User> getUsersOfLoginDateAndEmail(String loginDate, String email);
    public List<User> getUsersOfLoginDateAndMoney(String loginDate, String money);
    public List<User> getUsersOfLoginDateAndScore(String loginDate, String score);
    public List<User> getUsersOfLoginDateAndPath(String loginDate, String path);
    public List<User> getUsersOfLoginDateAndParam(String loginDate, String param);
    public List<User> getUsersOfLoginDateAndLvl(String loginDate, String lvl);
    public List<User> getUsersOfLoginDateAndNewIds(String loginDate, String newIds);
    public List<User> getUsersOfLoginDateAndUserIds(String loginDate, String userIds);
    public List<User> getUsersOfLoginDateAndSignature(String loginDate, String signature);
    public List<User> getUsersOfLoginDateAndImage(String loginDate, String image);
    public List<User> getUsersOfLoginDateAndFamous(String loginDate, String famous);
    public List<User> getUsersOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public List<User> getUsersOfLoginDateAndDays(String loginDate, String days);
    public List<User> getUsersOfLoginDateAndNowDays(String loginDate, String nowDays);
    public List<User> getUsersOfPhoneAndEmail(String phone, String email);
    public List<User> getUsersOfPhoneAndMoney(String phone, String money);
    public List<User> getUsersOfPhoneAndScore(String phone, String score);
    public List<User> getUsersOfPhoneAndPath(String phone, String path);
    public List<User> getUsersOfPhoneAndParam(String phone, String param);
    public List<User> getUsersOfPhoneAndLvl(String phone, String lvl);
    public List<User> getUsersOfPhoneAndNewIds(String phone, String newIds);
    public List<User> getUsersOfPhoneAndUserIds(String phone, String userIds);
    public List<User> getUsersOfPhoneAndSignature(String phone, String signature);
    public List<User> getUsersOfPhoneAndImage(String phone, String image);
    public List<User> getUsersOfPhoneAndFamous(String phone, String famous);
    public List<User> getUsersOfPhoneAndBUserIds(String phone, String bUserIds);
    public List<User> getUsersOfPhoneAndDays(String phone, String days);
    public List<User> getUsersOfPhoneAndNowDays(String phone, String nowDays);
    public List<User> getUsersOfEmailAndMoney(String email, String money);
    public List<User> getUsersOfEmailAndScore(String email, String score);
    public List<User> getUsersOfEmailAndPath(String email, String path);
    public List<User> getUsersOfEmailAndParam(String email, String param);
    public List<User> getUsersOfEmailAndLvl(String email, String lvl);
    public List<User> getUsersOfEmailAndNewIds(String email, String newIds);
    public List<User> getUsersOfEmailAndUserIds(String email, String userIds);
    public List<User> getUsersOfEmailAndSignature(String email, String signature);
    public List<User> getUsersOfEmailAndImage(String email, String image);
    public List<User> getUsersOfEmailAndFamous(String email, String famous);
    public List<User> getUsersOfEmailAndBUserIds(String email, String bUserIds);
    public List<User> getUsersOfEmailAndDays(String email, String days);
    public List<User> getUsersOfEmailAndNowDays(String email, String nowDays);
    public List<User> getUsersOfMoneyAndScore(String money, String score);
    public List<User> getUsersOfMoneyAndPath(String money, String path);
    public List<User> getUsersOfMoneyAndParam(String money, String param);
    public List<User> getUsersOfMoneyAndLvl(String money, String lvl);
    public List<User> getUsersOfMoneyAndNewIds(String money, String newIds);
    public List<User> getUsersOfMoneyAndUserIds(String money, String userIds);
    public List<User> getUsersOfMoneyAndSignature(String money, String signature);
    public List<User> getUsersOfMoneyAndImage(String money, String image);
    public List<User> getUsersOfMoneyAndFamous(String money, String famous);
    public List<User> getUsersOfMoneyAndBUserIds(String money, String bUserIds);
    public List<User> getUsersOfMoneyAndDays(String money, String days);
    public List<User> getUsersOfMoneyAndNowDays(String money, String nowDays);
    public List<User> getUsersOfScoreAndPath(String score, String path);
    public List<User> getUsersOfScoreAndParam(String score, String param);
    public List<User> getUsersOfScoreAndLvl(String score, String lvl);
    public List<User> getUsersOfScoreAndNewIds(String score, String newIds);
    public List<User> getUsersOfScoreAndUserIds(String score, String userIds);
    public List<User> getUsersOfScoreAndSignature(String score, String signature);
    public List<User> getUsersOfScoreAndImage(String score, String image);
    public List<User> getUsersOfScoreAndFamous(String score, String famous);
    public List<User> getUsersOfScoreAndBUserIds(String score, String bUserIds);
    public List<User> getUsersOfScoreAndDays(String score, String days);
    public List<User> getUsersOfScoreAndNowDays(String score, String nowDays);
    public List<User> getUsersOfPathAndParam(String path, String param);
    public List<User> getUsersOfPathAndLvl(String path, String lvl);
    public List<User> getUsersOfPathAndNewIds(String path, String newIds);
    public List<User> getUsersOfPathAndUserIds(String path, String userIds);
    public List<User> getUsersOfPathAndSignature(String path, String signature);
    public List<User> getUsersOfPathAndImage(String path, String image);
    public List<User> getUsersOfPathAndFamous(String path, String famous);
    public List<User> getUsersOfPathAndBUserIds(String path, String bUserIds);
    public List<User> getUsersOfPathAndDays(String path, String days);
    public List<User> getUsersOfPathAndNowDays(String path, String nowDays);
    public List<User> getUsersOfParamAndLvl(String param, String lvl);
    public List<User> getUsersOfParamAndNewIds(String param, String newIds);
    public List<User> getUsersOfParamAndUserIds(String param, String userIds);
    public List<User> getUsersOfParamAndSignature(String param, String signature);
    public List<User> getUsersOfParamAndImage(String param, String image);
    public List<User> getUsersOfParamAndFamous(String param, String famous);
    public List<User> getUsersOfParamAndBUserIds(String param, String bUserIds);
    public List<User> getUsersOfParamAndDays(String param, String days);
    public List<User> getUsersOfParamAndNowDays(String param, String nowDays);
    public List<User> getUsersOfLvlAndNewIds(String lvl, String newIds);
    public List<User> getUsersOfLvlAndUserIds(String lvl, String userIds);
    public List<User> getUsersOfLvlAndSignature(String lvl, String signature);
    public List<User> getUsersOfLvlAndImage(String lvl, String image);
    public List<User> getUsersOfLvlAndFamous(String lvl, String famous);
    public List<User> getUsersOfLvlAndBUserIds(String lvl, String bUserIds);
    public List<User> getUsersOfLvlAndDays(String lvl, String days);
    public List<User> getUsersOfLvlAndNowDays(String lvl, String nowDays);
    public List<User> getUsersOfNewIdsAndUserIds(String newIds, String userIds);
    public List<User> getUsersOfNewIdsAndSignature(String newIds, String signature);
    public List<User> getUsersOfNewIdsAndImage(String newIds, String image);
    public List<User> getUsersOfNewIdsAndFamous(String newIds, String famous);
    public List<User> getUsersOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public List<User> getUsersOfNewIdsAndDays(String newIds, String days);
    public List<User> getUsersOfNewIdsAndNowDays(String newIds, String nowDays);
    public List<User> getUsersOfUserIdsAndSignature(String userIds, String signature);
    public List<User> getUsersOfUserIdsAndImage(String userIds, String image);
    public List<User> getUsersOfUserIdsAndFamous(String userIds, String famous);
    public List<User> getUsersOfUserIdsAndBUserIds(String userIds, String bUserIds);
    public List<User> getUsersOfUserIdsAndDays(String userIds, String days);
    public List<User> getUsersOfUserIdsAndNowDays(String userIds, String nowDays);
    public List<User> getUsersOfSignatureAndImage(String signature, String image);
    public List<User> getUsersOfSignatureAndFamous(String signature, String famous);
    public List<User> getUsersOfSignatureAndBUserIds(String signature, String bUserIds);
    public List<User> getUsersOfSignatureAndDays(String signature, String days);
    public List<User> getUsersOfSignatureAndNowDays(String signature, String nowDays);
    public List<User> getUsersOfImageAndFamous(String image, String famous);
    public List<User> getUsersOfImageAndBUserIds(String image, String bUserIds);
    public List<User> getUsersOfImageAndDays(String image, String days);
    public List<User> getUsersOfImageAndNowDays(String image, String nowDays);
    public List<User> getUsersOfFamousAndBUserIds(String famous, String bUserIds);
    public List<User> getUsersOfFamousAndDays(String famous, String days);
    public List<User> getUsersOfFamousAndNowDays(String famous, String nowDays);
    public List<User> getUsersOfBUserIdsAndDays(String bUserIds, String days);
    public List<User> getUsersOfBUserIdsAndNowDays(String bUserIds, String nowDays);
    public List<User> getUsersOfDaysAndNowDays(String days, String nowDays);
}
