package com.news.linglian.service;

import java.util.List;

import com.news.linglian.entity.Comment;

public interface ICommentService {
    public int update(Comment comment, Comment keyComment);
    public int updateOfCommentId(Comment comment, String commentId);
    public int updateOfFid(Comment comment, String fid);
    public int updateOfCids(Comment comment, String cids);
    public int updateOfBody(Comment comment, String body);
    public int updateOfTime(Comment comment, String time);
    public int updateOfGood(Comment comment, String good);
    public int updateOfBad(Comment comment, String bad);
    public int updateOfCommentIdAndFid(Comment comment, String commentId, String fid);
    public int updateOfCommentIdAndCids(Comment comment, String commentId, String cids);
    public int updateOfCommentIdAndBody(Comment comment, String commentId, String body);
    public int updateOfCommentIdAndTime(Comment comment, String commentId, String time);
    public int updateOfCommentIdAndGood(Comment comment, String commentId, String good);
    public int updateOfCommentIdAndBad(Comment comment, String commentId, String bad);
    public int updateOfFidAndCids(Comment comment, String fid, String cids);
    public int updateOfFidAndBody(Comment comment, String fid, String body);
    public int updateOfFidAndTime(Comment comment, String fid, String time);
    public int updateOfFidAndGood(Comment comment, String fid, String good);
    public int updateOfFidAndBad(Comment comment, String fid, String bad);
    public int updateOfCidsAndBody(Comment comment, String cids, String body);
    public int updateOfCidsAndTime(Comment comment, String cids, String time);
    public int updateOfCidsAndGood(Comment comment, String cids, String good);
    public int updateOfCidsAndBad(Comment comment, String cids, String bad);
    public int updateOfBodyAndTime(Comment comment, String body, String time);
    public int updateOfBodyAndGood(Comment comment, String body, String good);
    public int updateOfBodyAndBad(Comment comment, String body, String bad);
    public int updateOfTimeAndGood(Comment comment, String time, String good);
    public int updateOfTimeAndBad(Comment comment, String time, String bad);
    public int updateOfGoodAndBad(Comment comment, String good, String bad);
    public int remove(Comment comment);
    public int removeOfCommentId(String commentId);
    public int removeOfFid(String fid);
    public int removeOfCids(String cids);
    public int removeOfBody(String body);
    public int removeOfTime(String time);
    public int removeOfGood(String good);
    public int removeOfBad(String bad);
    public int removeOfCommentIdAndFid(String commentId, String fid);
    public int removeOfCommentIdAndCids(String commentId, String cids);
    public int removeOfCommentIdAndBody(String commentId, String body);
    public int removeOfCommentIdAndTime(String commentId, String time);
    public int removeOfCommentIdAndGood(String commentId, String good);
    public int removeOfCommentIdAndBad(String commentId, String bad);
    public int removeOfFidAndCids(String fid, String cids);
    public int removeOfFidAndBody(String fid, String body);
    public int removeOfFidAndTime(String fid, String time);
    public int removeOfFidAndGood(String fid, String good);
    public int removeOfFidAndBad(String fid, String bad);
    public int removeOfCidsAndBody(String cids, String body);
    public int removeOfCidsAndTime(String cids, String time);
    public int removeOfCidsAndGood(String cids, String good);
    public int removeOfCidsAndBad(String cids, String bad);
    public int removeOfBodyAndTime(String body, String time);
    public int removeOfBodyAndGood(String body, String good);
    public int removeOfBodyAndBad(String body, String bad);
    public int removeOfTimeAndGood(String time, String good);
    public int removeOfTimeAndBad(String time, String bad);
    public int removeOfGoodAndBad(String good, String bad);
    public int insert(Comment comment);
    public int insertOfCommentId(String commentId);
    public int insertOfFid(String fid);
    public int insertOfCids(String cids);
    public int insertOfBody(String body);
    public int insertOfTime(String time);
    public int insertOfGood(String good);
    public int insertOfBad(String bad);
    public int insertOfCommentIdAndFid(String commentId, String fid);
    public int insertOfCommentIdAndCids(String commentId, String cids);
    public int insertOfCommentIdAndBody(String commentId, String body);
    public int insertOfCommentIdAndTime(String commentId, String time);
    public int insertOfCommentIdAndGood(String commentId, String good);
    public int insertOfCommentIdAndBad(String commentId, String bad);
    public int insertOfFidAndCids(String fid, String cids);
    public int insertOfFidAndBody(String fid, String body);
    public int insertOfFidAndTime(String fid, String time);
    public int insertOfFidAndGood(String fid, String good);
    public int insertOfFidAndBad(String fid, String bad);
    public int insertOfCidsAndBody(String cids, String body);
    public int insertOfCidsAndTime(String cids, String time);
    public int insertOfCidsAndGood(String cids, String good);
    public int insertOfCidsAndBad(String cids, String bad);
    public int insertOfBodyAndTime(String body, String time);
    public int insertOfBodyAndGood(String body, String good);
    public int insertOfBodyAndBad(String body, String bad);
    public int insertOfTimeAndGood(String time, String good);
    public int insertOfTimeAndBad(String time, String bad);
    public int insertOfGoodAndBad(String good, String bad);
    public Comment getComment(Comment comment);
    public Comment getCommentOfCommentId(String commentId);
    public Comment getCommentOfFid(String fid);
    public Comment getCommentOfCids(String cids);
    public Comment getCommentOfBody(String body);
    public Comment getCommentOfTime(String time);
    public Comment getCommentOfGood(String good);
    public Comment getCommentOfBad(String bad);
    public Comment getCommentOfCommentIdAndFid(String commentId, String fid);
    public Comment getCommentOfCommentIdAndCids(String commentId, String cids);
    public Comment getCommentOfCommentIdAndBody(String commentId, String body);
    public Comment getCommentOfCommentIdAndTime(String commentId, String time);
    public Comment getCommentOfCommentIdAndGood(String commentId, String good);
    public Comment getCommentOfCommentIdAndBad(String commentId, String bad);
    public Comment getCommentOfFidAndCids(String fid, String cids);
    public Comment getCommentOfFidAndBody(String fid, String body);
    public Comment getCommentOfFidAndTime(String fid, String time);
    public Comment getCommentOfFidAndGood(String fid, String good);
    public Comment getCommentOfFidAndBad(String fid, String bad);
    public Comment getCommentOfCidsAndBody(String cids, String body);
    public Comment getCommentOfCidsAndTime(String cids, String time);
    public Comment getCommentOfCidsAndGood(String cids, String good);
    public Comment getCommentOfCidsAndBad(String cids, String bad);
    public Comment getCommentOfBodyAndTime(String body, String time);
    public Comment getCommentOfBodyAndGood(String body, String good);
    public Comment getCommentOfBodyAndBad(String body, String bad);
    public Comment getCommentOfTimeAndGood(String time, String good);
    public Comment getCommentOfTimeAndBad(String time, String bad);
    public Comment getCommentOfGoodAndBad(String good, String bad);
    public List<Comment> getComments(Comment comment);
    public List<Comment> getCommentsOfCommentId(String commentId);
    public List<Comment> getCommentsOfFid(String fid);
    public List<Comment> getCommentsOfCids(String cids);
    public List<Comment> getCommentsOfBody(String body);
    public List<Comment> getCommentsOfTime(String time);
    public List<Comment> getCommentsOfGood(String good);
    public List<Comment> getCommentsOfBad(String bad);
    public List<Comment> getCommentsOfCommentIdAndFid(String commentId, String fid);
    public List<Comment> getCommentsOfCommentIdAndCids(String commentId, String cids);
    public List<Comment> getCommentsOfCommentIdAndBody(String commentId, String body);
    public List<Comment> getCommentsOfCommentIdAndTime(String commentId, String time);
    public List<Comment> getCommentsOfCommentIdAndGood(String commentId, String good);
    public List<Comment> getCommentsOfCommentIdAndBad(String commentId, String bad);
    public List<Comment> getCommentsOfFidAndCids(String fid, String cids);
    public List<Comment> getCommentsOfFidAndBody(String fid, String body);
    public List<Comment> getCommentsOfFidAndTime(String fid, String time);
    public List<Comment> getCommentsOfFidAndGood(String fid, String good);
    public List<Comment> getCommentsOfFidAndBad(String fid, String bad);
    public List<Comment> getCommentsOfCidsAndBody(String cids, String body);
    public List<Comment> getCommentsOfCidsAndTime(String cids, String time);
    public List<Comment> getCommentsOfCidsAndGood(String cids, String good);
    public List<Comment> getCommentsOfCidsAndBad(String cids, String bad);
    public List<Comment> getCommentsOfBodyAndTime(String body, String time);
    public List<Comment> getCommentsOfBodyAndGood(String body, String good);
    public List<Comment> getCommentsOfBodyAndBad(String body, String bad);
    public List<Comment> getCommentsOfTimeAndGood(String time, String good);
    public List<Comment> getCommentsOfTimeAndBad(String time, String bad);
    public List<Comment> getCommentsOfGoodAndBad(String good, String bad);
}
