package com.news.linglian.service;

import java.util.List;

import com.news.linglian.entity.Log;

public interface ILogService {
    public int update(Log log, Log keyLog);
    public int updateOfLogid(Log log, String logid);
    public int updateOfBody(Log log, String body);
    public int updateOfLogdate(Log log, String logdate);
    public int updateOfAdminid(Log log, String adminid);
    public int updateOfLogidAndBody(Log log, String logid, String body);
    public int updateOfLogidAndLogdate(Log log, String logid, String logdate);
    public int updateOfLogidAndAdminid(Log log, String logid, String adminid);
    public int updateOfBodyAndLogdate(Log log, String body, String logdate);
    public int updateOfBodyAndAdminid(Log log, String body, String adminid);
    public int updateOfLogdateAndAdminid(Log log, String logdate, String adminid);
    public int updateOfLogidAndBodyAndLogdate(Log log, String logid, String body, String logdate);
    public int updateOfLogidAndBodyAndAdminid(Log log, String logid, String body, String adminid);
    public int updateOfLogidAndLogdateAndAdminid(Log log, String logid, String logdate, String adminid);
    public int updateOfBodyAndLogdateAndAdminid(Log log, String body, String logdate, String adminid);
    public int updateOfLogidAndBodyAndLogdateAndAdminid(Log log, String logid, String body, String logdate, String adminid);
    public int remove(Log log);
    public int removeOfLogid(String logid);
    public int removeOfBody(String body);
    public int removeOfLogdate(String logdate);
    public int removeOfAdminid(String adminid);
    public int removeOfLogidAndBody(String logid, String body);
    public int removeOfLogidAndLogdate(String logid, String logdate);
    public int removeOfLogidAndAdminid(String logid, String adminid);
    public int removeOfBodyAndLogdate(String body, String logdate);
    public int removeOfBodyAndAdminid(String body, String adminid);
    public int removeOfLogdateAndAdminid(String logdate, String adminid);
    public int removeOfLogidAndBodyAndLogdate(String logid, String body, String logdate);
    public int removeOfLogidAndBodyAndAdminid(String logid, String body, String adminid);
    public int removeOfLogidAndLogdateAndAdminid(String logid, String logdate, String adminid);
    public int removeOfBodyAndLogdateAndAdminid(String body, String logdate, String adminid);
    public int removeOfLogidAndBodyAndLogdateAndAdminid(String logid, String body, String logdate, String adminid);
    public int insert(Log log);
    public int insertOfLogid(String logid);
    public int insertOfBody(String body);
    public int insertOfLogdate(String logdate);
    public int insertOfAdminid(String adminid);
    public int insertOfLogidAndBody(String logid, String body);
    public int insertOfLogidAndLogdate(String logid, String logdate);
    public int insertOfLogidAndAdminid(String logid, String adminid);
    public int insertOfBodyAndLogdate(String body, String logdate);
    public int insertOfBodyAndAdminid(String body, String adminid);
    public int insertOfLogdateAndAdminid(String logdate, String adminid);
    public int insertOfLogidAndBodyAndLogdate(String logid, String body, String logdate);
    public int insertOfLogidAndBodyAndAdminid(String logid, String body, String adminid);
    public int insertOfLogidAndLogdateAndAdminid(String logid, String logdate, String adminid);
    public int insertOfBodyAndLogdateAndAdminid(String body, String logdate, String adminid);
    public int insertOfLogidAndBodyAndLogdateAndAdminid(String logid, String body, String logdate, String adminid);
    public Log getLog(Log log);
    public Log getLogOfLogid(String logid);
    public Log getLogOfBody(String body);
    public Log getLogOfLogdate(String logdate);
    public Log getLogOfAdminid(String adminid);
    public Log getLogOfLogidAndBody(String logid, String body);
    public Log getLogOfLogidAndLogdate(String logid, String logdate);
    public Log getLogOfLogidAndAdminid(String logid, String adminid);
    public Log getLogOfBodyAndLogdate(String body, String logdate);
    public Log getLogOfBodyAndAdminid(String body, String adminid);
    public Log getLogOfLogdateAndAdminid(String logdate, String adminid);
    public Log getLogOfLogidAndBodyAndLogdate(String logid, String body, String logdate);
    public Log getLogOfLogidAndBodyAndAdminid(String logid, String body, String adminid);
    public Log getLogOfLogidAndLogdateAndAdminid(String logid, String logdate, String adminid);
    public Log getLogOfBodyAndLogdateAndAdminid(String body, String logdate, String adminid);
    public Log getLogOfLogidAndBodyAndLogdateAndAdminid(String logid, String body, String logdate, String adminid);
    public List<Log> getLogs(Log log);
    public List<Log> getLogsOfLogid(String logid);
    public List<Log> getLogsOfBody(String body);
    public List<Log> getLogsOfLogdate(String logdate);
    public List<Log> getLogsOfAdminid(String adminid);
    public List<Log> getLogsOfLogidAndBody(String logid, String body);
    public List<Log> getLogsOfLogidAndLogdate(String logid, String logdate);
    public List<Log> getLogsOfLogidAndAdminid(String logid, String adminid);
    public List<Log> getLogsOfBodyAndLogdate(String body, String logdate);
    public List<Log> getLogsOfBodyAndAdminid(String body, String adminid);
    public List<Log> getLogsOfLogdateAndAdminid(String logdate, String adminid);
    public List<Log> getLogsOfLogidAndBodyAndLogdate(String logid, String body, String logdate);
    public List<Log> getLogsOfLogidAndBodyAndAdminid(String logid, String body, String adminid);
    public List<Log> getLogsOfLogidAndLogdateAndAdminid(String logid, String logdate, String adminid);
    public List<Log> getLogsOfBodyAndLogdateAndAdminid(String body, String logdate, String adminid);
    public List<Log> getLogsOfLogidAndBodyAndLogdateAndAdminid(String logid, String body, String logdate, String adminid);
}
