package com.news.linglian.service;

import java.util.List;

import com.news.linglian.entity.User;

public interface IUserService {
    public int update(User user, User keyUser);
    public int updateOfImage(User user, String image);
    public int updateOfLvl(User user, String lvl);
    public int updateOfNewIds(User user, String newIds);
    public int updateOfFamous(User user, String famous);
    public int updateOfSex(User user, String sex);
    public int updateOfLoginDate(User user, String loginDate);
    public int updateOfUserId(User user, String userId);
    public int updateOfBUserIds(User user, String bUserIds);
    public int updateOfScore(User user, String score);
    public int updateOfPath(User user, String path);
    public int updateOfPassword(User user, String password);
    public int updateOfMoney(User user, String money);
    public int updateOfPhone(User user, String phone);
    public int updateOfParam(User user, String param);
    public int updateOfUserIds(User user, String userIds);
    public int updateOfName(User user, String name);
    public int updateOfResgisterDate(User user, String resgisterDate);
    public int updateOfEmail(User user, String email);
    public int updateOfDesc(User user, String desc);
    public int updateOfImageAndLvl(User user, String image, String lvl);
    public int updateOfImageAndNewIds(User user, String image, String newIds);
    public int updateOfImageAndFamous(User user, String image, String famous);
    public int updateOfImageAndSex(User user, String image, String sex);
    public int updateOfImageAndLoginDate(User user, String image, String loginDate);
    public int updateOfImageAndUserId(User user, String image, String userId);
    public int updateOfImageAndBUserIds(User user, String image, String bUserIds);
    public int updateOfImageAndScore(User user, String image, String score);
    public int updateOfImageAndPath(User user, String image, String path);
    public int updateOfImageAndPassword(User user, String image, String password);
    public int updateOfImageAndMoney(User user, String image, String money);
    public int updateOfImageAndPhone(User user, String image, String phone);
    public int updateOfImageAndParam(User user, String image, String param);
    public int updateOfImageAndUserIds(User user, String image, String userIds);
    public int updateOfImageAndName(User user, String image, String name);
    public int updateOfImageAndResgisterDate(User user, String image, String resgisterDate);
    public int updateOfImageAndEmail(User user, String image, String email);
    public int updateOfImageAndDesc(User user, String image, String desc);
    public int updateOfLvlAndNewIds(User user, String lvl, String newIds);
    public int updateOfLvlAndFamous(User user, String lvl, String famous);
    public int updateOfLvlAndSex(User user, String lvl, String sex);
    public int updateOfLvlAndLoginDate(User user, String lvl, String loginDate);
    public int updateOfLvlAndUserId(User user, String lvl, String userId);
    public int updateOfLvlAndBUserIds(User user, String lvl, String bUserIds);
    public int updateOfLvlAndScore(User user, String lvl, String score);
    public int updateOfLvlAndPath(User user, String lvl, String path);
    public int updateOfLvlAndPassword(User user, String lvl, String password);
    public int updateOfLvlAndMoney(User user, String lvl, String money);
    public int updateOfLvlAndPhone(User user, String lvl, String phone);
    public int updateOfLvlAndParam(User user, String lvl, String param);
    public int updateOfLvlAndUserIds(User user, String lvl, String userIds);
    public int updateOfLvlAndName(User user, String lvl, String name);
    public int updateOfLvlAndResgisterDate(User user, String lvl, String resgisterDate);
    public int updateOfLvlAndEmail(User user, String lvl, String email);
    public int updateOfLvlAndDesc(User user, String lvl, String desc);
    public int updateOfNewIdsAndFamous(User user, String newIds, String famous);
    public int updateOfNewIdsAndSex(User user, String newIds, String sex);
    public int updateOfNewIdsAndLoginDate(User user, String newIds, String loginDate);
    public int updateOfNewIdsAndUserId(User user, String newIds, String userId);
    public int updateOfNewIdsAndBUserIds(User user, String newIds, String bUserIds);
    public int updateOfNewIdsAndScore(User user, String newIds, String score);
    public int updateOfNewIdsAndPath(User user, String newIds, String path);
    public int updateOfNewIdsAndPassword(User user, String newIds, String password);
    public int updateOfNewIdsAndMoney(User user, String newIds, String money);
    public int updateOfNewIdsAndPhone(User user, String newIds, String phone);
    public int updateOfNewIdsAndParam(User user, String newIds, String param);
    public int updateOfNewIdsAndUserIds(User user, String newIds, String userIds);
    public int updateOfNewIdsAndName(User user, String newIds, String name);
    public int updateOfNewIdsAndResgisterDate(User user, String newIds, String resgisterDate);
    public int updateOfNewIdsAndEmail(User user, String newIds, String email);
    public int updateOfNewIdsAndDesc(User user, String newIds, String desc);
    public int updateOfFamousAndSex(User user, String famous, String sex);
    public int updateOfFamousAndLoginDate(User user, String famous, String loginDate);
    public int updateOfFamousAndUserId(User user, String famous, String userId);
    public int updateOfFamousAndBUserIds(User user, String famous, String bUserIds);
    public int updateOfFamousAndScore(User user, String famous, String score);
    public int updateOfFamousAndPath(User user, String famous, String path);
    public int updateOfFamousAndPassword(User user, String famous, String password);
    public int updateOfFamousAndMoney(User user, String famous, String money);
    public int updateOfFamousAndPhone(User user, String famous, String phone);
    public int updateOfFamousAndParam(User user, String famous, String param);
    public int updateOfFamousAndUserIds(User user, String famous, String userIds);
    public int updateOfFamousAndName(User user, String famous, String name);
    public int updateOfFamousAndResgisterDate(User user, String famous, String resgisterDate);
    public int updateOfFamousAndEmail(User user, String famous, String email);
    public int updateOfFamousAndDesc(User user, String famous, String desc);
    public int updateOfSexAndLoginDate(User user, String sex, String loginDate);
    public int updateOfSexAndUserId(User user, String sex, String userId);
    public int updateOfSexAndBUserIds(User user, String sex, String bUserIds);
    public int updateOfSexAndScore(User user, String sex, String score);
    public int updateOfSexAndPath(User user, String sex, String path);
    public int updateOfSexAndPassword(User user, String sex, String password);
    public int updateOfSexAndMoney(User user, String sex, String money);
    public int updateOfSexAndPhone(User user, String sex, String phone);
    public int updateOfSexAndParam(User user, String sex, String param);
    public int updateOfSexAndUserIds(User user, String sex, String userIds);
    public int updateOfSexAndName(User user, String sex, String name);
    public int updateOfSexAndResgisterDate(User user, String sex, String resgisterDate);
    public int updateOfSexAndEmail(User user, String sex, String email);
    public int updateOfSexAndDesc(User user, String sex, String desc);
    public int updateOfLoginDateAndUserId(User user, String loginDate, String userId);
    public int updateOfLoginDateAndBUserIds(User user, String loginDate, String bUserIds);
    public int updateOfLoginDateAndScore(User user, String loginDate, String score);
    public int updateOfLoginDateAndPath(User user, String loginDate, String path);
    public int updateOfLoginDateAndPassword(User user, String loginDate, String password);
    public int updateOfLoginDateAndMoney(User user, String loginDate, String money);
    public int updateOfLoginDateAndPhone(User user, String loginDate, String phone);
    public int updateOfLoginDateAndParam(User user, String loginDate, String param);
    public int updateOfLoginDateAndUserIds(User user, String loginDate, String userIds);
    public int updateOfLoginDateAndName(User user, String loginDate, String name);
    public int updateOfLoginDateAndResgisterDate(User user, String loginDate, String resgisterDate);
    public int updateOfLoginDateAndEmail(User user, String loginDate, String email);
    public int updateOfLoginDateAndDesc(User user, String loginDate, String desc);
    public int updateOfUserIdAndBUserIds(User user, String userId, String bUserIds);
    public int updateOfUserIdAndScore(User user, String userId, String score);
    public int updateOfUserIdAndPath(User user, String userId, String path);
    public int updateOfUserIdAndPassword(User user, String userId, String password);
    public int updateOfUserIdAndMoney(User user, String userId, String money);
    public int updateOfUserIdAndPhone(User user, String userId, String phone);
    public int updateOfUserIdAndParam(User user, String userId, String param);
    public int updateOfUserIdAndUserIds(User user, String userId, String userIds);
    public int updateOfUserIdAndName(User user, String userId, String name);
    public int updateOfUserIdAndResgisterDate(User user, String userId, String resgisterDate);
    public int updateOfUserIdAndEmail(User user, String userId, String email);
    public int updateOfUserIdAndDesc(User user, String userId, String desc);
    public int updateOfBUserIdsAndScore(User user, String bUserIds, String score);
    public int updateOfBUserIdsAndPath(User user, String bUserIds, String path);
    public int updateOfBUserIdsAndPassword(User user, String bUserIds, String password);
    public int updateOfBUserIdsAndMoney(User user, String bUserIds, String money);
    public int updateOfBUserIdsAndPhone(User user, String bUserIds, String phone);
    public int updateOfBUserIdsAndParam(User user, String bUserIds, String param);
    public int updateOfBUserIdsAndUserIds(User user, String bUserIds, String userIds);
    public int updateOfBUserIdsAndName(User user, String bUserIds, String name);
    public int updateOfBUserIdsAndResgisterDate(User user, String bUserIds, String resgisterDate);
    public int updateOfBUserIdsAndEmail(User user, String bUserIds, String email);
    public int updateOfBUserIdsAndDesc(User user, String bUserIds, String desc);
    public int updateOfScoreAndPath(User user, String score, String path);
    public int updateOfScoreAndPassword(User user, String score, String password);
    public int updateOfScoreAndMoney(User user, String score, String money);
    public int updateOfScoreAndPhone(User user, String score, String phone);
    public int updateOfScoreAndParam(User user, String score, String param);
    public int updateOfScoreAndUserIds(User user, String score, String userIds);
    public int updateOfScoreAndName(User user, String score, String name);
    public int updateOfScoreAndResgisterDate(User user, String score, String resgisterDate);
    public int updateOfScoreAndEmail(User user, String score, String email);
    public int updateOfScoreAndDesc(User user, String score, String desc);
    public int updateOfPathAndPassword(User user, String path, String password);
    public int updateOfPathAndMoney(User user, String path, String money);
    public int updateOfPathAndPhone(User user, String path, String phone);
    public int updateOfPathAndParam(User user, String path, String param);
    public int updateOfPathAndUserIds(User user, String path, String userIds);
    public int updateOfPathAndName(User user, String path, String name);
    public int updateOfPathAndResgisterDate(User user, String path, String resgisterDate);
    public int updateOfPathAndEmail(User user, String path, String email);
    public int updateOfPathAndDesc(User user, String path, String desc);
    public int updateOfPasswordAndMoney(User user, String password, String money);
    public int updateOfPasswordAndPhone(User user, String password, String phone);
    public int updateOfPasswordAndParam(User user, String password, String param);
    public int updateOfPasswordAndUserIds(User user, String password, String userIds);
    public int updateOfPasswordAndName(User user, String password, String name);
    public int updateOfPasswordAndResgisterDate(User user, String password, String resgisterDate);
    public int updateOfPasswordAndEmail(User user, String password, String email);
    public int updateOfPasswordAndDesc(User user, String password, String desc);
    public int updateOfMoneyAndPhone(User user, String money, String phone);
    public int updateOfMoneyAndParam(User user, String money, String param);
    public int updateOfMoneyAndUserIds(User user, String money, String userIds);
    public int updateOfMoneyAndName(User user, String money, String name);
    public int updateOfMoneyAndResgisterDate(User user, String money, String resgisterDate);
    public int updateOfMoneyAndEmail(User user, String money, String email);
    public int updateOfMoneyAndDesc(User user, String money, String desc);
    public int updateOfPhoneAndParam(User user, String phone, String param);
    public int updateOfPhoneAndUserIds(User user, String phone, String userIds);
    public int updateOfPhoneAndName(User user, String phone, String name);
    public int updateOfPhoneAndResgisterDate(User user, String phone, String resgisterDate);
    public int updateOfPhoneAndEmail(User user, String phone, String email);
    public int updateOfPhoneAndDesc(User user, String phone, String desc);
    public int updateOfParamAndUserIds(User user, String param, String userIds);
    public int updateOfParamAndName(User user, String param, String name);
    public int updateOfParamAndResgisterDate(User user, String param, String resgisterDate);
    public int updateOfParamAndEmail(User user, String param, String email);
    public int updateOfParamAndDesc(User user, String param, String desc);
    public int updateOfUserIdsAndName(User user, String userIds, String name);
    public int updateOfUserIdsAndResgisterDate(User user, String userIds, String resgisterDate);
    public int updateOfUserIdsAndEmail(User user, String userIds, String email);
    public int updateOfUserIdsAndDesc(User user, String userIds, String desc);
    public int updateOfNameAndResgisterDate(User user, String name, String resgisterDate);
    public int updateOfNameAndEmail(User user, String name, String email);
    public int updateOfNameAndDesc(User user, String name, String desc);
    public int updateOfResgisterDateAndEmail(User user, String resgisterDate, String email);
    public int updateOfResgisterDateAndDesc(User user, String resgisterDate, String desc);
    public int updateOfEmailAndDesc(User user, String email, String desc);
    public int remove(User user);
    public int removeOfImage(String image);
    public int removeOfLvl(String lvl);
    public int removeOfNewIds(String newIds);
    public int removeOfFamous(String famous);
    public int removeOfSex(String sex);
    public int removeOfLoginDate(String loginDate);
    public int removeOfUserId(String userId);
    public int removeOfBUserIds(String bUserIds);
    public int removeOfScore(String score);
    public int removeOfPath(String path);
    public int removeOfPassword(String password);
    public int removeOfMoney(String money);
    public int removeOfPhone(String phone);
    public int removeOfParam(String param);
    public int removeOfUserIds(String userIds);
    public int removeOfName(String name);
    public int removeOfResgisterDate(String resgisterDate);
    public int removeOfEmail(String email);
    public int removeOfDesc(String desc);
    public int removeOfImageAndLvl(String image, String lvl);
    public int removeOfImageAndNewIds(String image, String newIds);
    public int removeOfImageAndFamous(String image, String famous);
    public int removeOfImageAndSex(String image, String sex);
    public int removeOfImageAndLoginDate(String image, String loginDate);
    public int removeOfImageAndUserId(String image, String userId);
    public int removeOfImageAndBUserIds(String image, String bUserIds);
    public int removeOfImageAndScore(String image, String score);
    public int removeOfImageAndPath(String image, String path);
    public int removeOfImageAndPassword(String image, String password);
    public int removeOfImageAndMoney(String image, String money);
    public int removeOfImageAndPhone(String image, String phone);
    public int removeOfImageAndParam(String image, String param);
    public int removeOfImageAndUserIds(String image, String userIds);
    public int removeOfImageAndName(String image, String name);
    public int removeOfImageAndResgisterDate(String image, String resgisterDate);
    public int removeOfImageAndEmail(String image, String email);
    public int removeOfImageAndDesc(String image, String desc);
    public int removeOfLvlAndNewIds(String lvl, String newIds);
    public int removeOfLvlAndFamous(String lvl, String famous);
    public int removeOfLvlAndSex(String lvl, String sex);
    public int removeOfLvlAndLoginDate(String lvl, String loginDate);
    public int removeOfLvlAndUserId(String lvl, String userId);
    public int removeOfLvlAndBUserIds(String lvl, String bUserIds);
    public int removeOfLvlAndScore(String lvl, String score);
    public int removeOfLvlAndPath(String lvl, String path);
    public int removeOfLvlAndPassword(String lvl, String password);
    public int removeOfLvlAndMoney(String lvl, String money);
    public int removeOfLvlAndPhone(String lvl, String phone);
    public int removeOfLvlAndParam(String lvl, String param);
    public int removeOfLvlAndUserIds(String lvl, String userIds);
    public int removeOfLvlAndName(String lvl, String name);
    public int removeOfLvlAndResgisterDate(String lvl, String resgisterDate);
    public int removeOfLvlAndEmail(String lvl, String email);
    public int removeOfLvlAndDesc(String lvl, String desc);
    public int removeOfNewIdsAndFamous(String newIds, String famous);
    public int removeOfNewIdsAndSex(String newIds, String sex);
    public int removeOfNewIdsAndLoginDate(String newIds, String loginDate);
    public int removeOfNewIdsAndUserId(String newIds, String userId);
    public int removeOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public int removeOfNewIdsAndScore(String newIds, String score);
    public int removeOfNewIdsAndPath(String newIds, String path);
    public int removeOfNewIdsAndPassword(String newIds, String password);
    public int removeOfNewIdsAndMoney(String newIds, String money);
    public int removeOfNewIdsAndPhone(String newIds, String phone);
    public int removeOfNewIdsAndParam(String newIds, String param);
    public int removeOfNewIdsAndUserIds(String newIds, String userIds);
    public int removeOfNewIdsAndName(String newIds, String name);
    public int removeOfNewIdsAndResgisterDate(String newIds, String resgisterDate);
    public int removeOfNewIdsAndEmail(String newIds, String email);
    public int removeOfNewIdsAndDesc(String newIds, String desc);
    public int removeOfFamousAndSex(String famous, String sex);
    public int removeOfFamousAndLoginDate(String famous, String loginDate);
    public int removeOfFamousAndUserId(String famous, String userId);
    public int removeOfFamousAndBUserIds(String famous, String bUserIds);
    public int removeOfFamousAndScore(String famous, String score);
    public int removeOfFamousAndPath(String famous, String path);
    public int removeOfFamousAndPassword(String famous, String password);
    public int removeOfFamousAndMoney(String famous, String money);
    public int removeOfFamousAndPhone(String famous, String phone);
    public int removeOfFamousAndParam(String famous, String param);
    public int removeOfFamousAndUserIds(String famous, String userIds);
    public int removeOfFamousAndName(String famous, String name);
    public int removeOfFamousAndResgisterDate(String famous, String resgisterDate);
    public int removeOfFamousAndEmail(String famous, String email);
    public int removeOfFamousAndDesc(String famous, String desc);
    public int removeOfSexAndLoginDate(String sex, String loginDate);
    public int removeOfSexAndUserId(String sex, String userId);
    public int removeOfSexAndBUserIds(String sex, String bUserIds);
    public int removeOfSexAndScore(String sex, String score);
    public int removeOfSexAndPath(String sex, String path);
    public int removeOfSexAndPassword(String sex, String password);
    public int removeOfSexAndMoney(String sex, String money);
    public int removeOfSexAndPhone(String sex, String phone);
    public int removeOfSexAndParam(String sex, String param);
    public int removeOfSexAndUserIds(String sex, String userIds);
    public int removeOfSexAndName(String sex, String name);
    public int removeOfSexAndResgisterDate(String sex, String resgisterDate);
    public int removeOfSexAndEmail(String sex, String email);
    public int removeOfSexAndDesc(String sex, String desc);
    public int removeOfLoginDateAndUserId(String loginDate, String userId);
    public int removeOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public int removeOfLoginDateAndScore(String loginDate, String score);
    public int removeOfLoginDateAndPath(String loginDate, String path);
    public int removeOfLoginDateAndPassword(String loginDate, String password);
    public int removeOfLoginDateAndMoney(String loginDate, String money);
    public int removeOfLoginDateAndPhone(String loginDate, String phone);
    public int removeOfLoginDateAndParam(String loginDate, String param);
    public int removeOfLoginDateAndUserIds(String loginDate, String userIds);
    public int removeOfLoginDateAndName(String loginDate, String name);
    public int removeOfLoginDateAndResgisterDate(String loginDate, String resgisterDate);
    public int removeOfLoginDateAndEmail(String loginDate, String email);
    public int removeOfLoginDateAndDesc(String loginDate, String desc);
    public int removeOfUserIdAndBUserIds(String userId, String bUserIds);
    public int removeOfUserIdAndScore(String userId, String score);
    public int removeOfUserIdAndPath(String userId, String path);
    public int removeOfUserIdAndPassword(String userId, String password);
    public int removeOfUserIdAndMoney(String userId, String money);
    public int removeOfUserIdAndPhone(String userId, String phone);
    public int removeOfUserIdAndParam(String userId, String param);
    public int removeOfUserIdAndUserIds(String userId, String userIds);
    public int removeOfUserIdAndName(String userId, String name);
    public int removeOfUserIdAndResgisterDate(String userId, String resgisterDate);
    public int removeOfUserIdAndEmail(String userId, String email);
    public int removeOfUserIdAndDesc(String userId, String desc);
    public int removeOfBUserIdsAndScore(String bUserIds, String score);
    public int removeOfBUserIdsAndPath(String bUserIds, String path);
    public int removeOfBUserIdsAndPassword(String bUserIds, String password);
    public int removeOfBUserIdsAndMoney(String bUserIds, String money);
    public int removeOfBUserIdsAndPhone(String bUserIds, String phone);
    public int removeOfBUserIdsAndParam(String bUserIds, String param);
    public int removeOfBUserIdsAndUserIds(String bUserIds, String userIds);
    public int removeOfBUserIdsAndName(String bUserIds, String name);
    public int removeOfBUserIdsAndResgisterDate(String bUserIds, String resgisterDate);
    public int removeOfBUserIdsAndEmail(String bUserIds, String email);
    public int removeOfBUserIdsAndDesc(String bUserIds, String desc);
    public int removeOfScoreAndPath(String score, String path);
    public int removeOfScoreAndPassword(String score, String password);
    public int removeOfScoreAndMoney(String score, String money);
    public int removeOfScoreAndPhone(String score, String phone);
    public int removeOfScoreAndParam(String score, String param);
    public int removeOfScoreAndUserIds(String score, String userIds);
    public int removeOfScoreAndName(String score, String name);
    public int removeOfScoreAndResgisterDate(String score, String resgisterDate);
    public int removeOfScoreAndEmail(String score, String email);
    public int removeOfScoreAndDesc(String score, String desc);
    public int removeOfPathAndPassword(String path, String password);
    public int removeOfPathAndMoney(String path, String money);
    public int removeOfPathAndPhone(String path, String phone);
    public int removeOfPathAndParam(String path, String param);
    public int removeOfPathAndUserIds(String path, String userIds);
    public int removeOfPathAndName(String path, String name);
    public int removeOfPathAndResgisterDate(String path, String resgisterDate);
    public int removeOfPathAndEmail(String path, String email);
    public int removeOfPathAndDesc(String path, String desc);
    public int removeOfPasswordAndMoney(String password, String money);
    public int removeOfPasswordAndPhone(String password, String phone);
    public int removeOfPasswordAndParam(String password, String param);
    public int removeOfPasswordAndUserIds(String password, String userIds);
    public int removeOfPasswordAndName(String password, String name);
    public int removeOfPasswordAndResgisterDate(String password, String resgisterDate);
    public int removeOfPasswordAndEmail(String password, String email);
    public int removeOfPasswordAndDesc(String password, String desc);
    public int removeOfMoneyAndPhone(String money, String phone);
    public int removeOfMoneyAndParam(String money, String param);
    public int removeOfMoneyAndUserIds(String money, String userIds);
    public int removeOfMoneyAndName(String money, String name);
    public int removeOfMoneyAndResgisterDate(String money, String resgisterDate);
    public int removeOfMoneyAndEmail(String money, String email);
    public int removeOfMoneyAndDesc(String money, String desc);
    public int removeOfPhoneAndParam(String phone, String param);
    public int removeOfPhoneAndUserIds(String phone, String userIds);
    public int removeOfPhoneAndName(String phone, String name);
    public int removeOfPhoneAndResgisterDate(String phone, String resgisterDate);
    public int removeOfPhoneAndEmail(String phone, String email);
    public int removeOfPhoneAndDesc(String phone, String desc);
    public int removeOfParamAndUserIds(String param, String userIds);
    public int removeOfParamAndName(String param, String name);
    public int removeOfParamAndResgisterDate(String param, String resgisterDate);
    public int removeOfParamAndEmail(String param, String email);
    public int removeOfParamAndDesc(String param, String desc);
    public int removeOfUserIdsAndName(String userIds, String name);
    public int removeOfUserIdsAndResgisterDate(String userIds, String resgisterDate);
    public int removeOfUserIdsAndEmail(String userIds, String email);
    public int removeOfUserIdsAndDesc(String userIds, String desc);
    public int removeOfNameAndResgisterDate(String name, String resgisterDate);
    public int removeOfNameAndEmail(String name, String email);
    public int removeOfNameAndDesc(String name, String desc);
    public int removeOfResgisterDateAndEmail(String resgisterDate, String email);
    public int removeOfResgisterDateAndDesc(String resgisterDate, String desc);
    public int removeOfEmailAndDesc(String email, String desc);
    public int insert(User user);
    public int insertOfImage(String image);
    public int insertOfLvl(String lvl);
    public int insertOfNewIds(String newIds);
    public int insertOfFamous(String famous);
    public int insertOfSex(String sex);
    public int insertOfLoginDate(String loginDate);
    public int insertOfUserId(String userId);
    public int insertOfBUserIds(String bUserIds);
    public int insertOfScore(String score);
    public int insertOfPath(String path);
    public int insertOfPassword(String password);
    public int insertOfMoney(String money);
    public int insertOfPhone(String phone);
    public int insertOfParam(String param);
    public int insertOfUserIds(String userIds);
    public int insertOfName(String name);
    public int insertOfResgisterDate(String resgisterDate);
    public int insertOfEmail(String email);
    public int insertOfDesc(String desc);
    public int insertOfImageAndLvl(String image, String lvl);
    public int insertOfImageAndNewIds(String image, String newIds);
    public int insertOfImageAndFamous(String image, String famous);
    public int insertOfImageAndSex(String image, String sex);
    public int insertOfImageAndLoginDate(String image, String loginDate);
    public int insertOfImageAndUserId(String image, String userId);
    public int insertOfImageAndBUserIds(String image, String bUserIds);
    public int insertOfImageAndScore(String image, String score);
    public int insertOfImageAndPath(String image, String path);
    public int insertOfImageAndPassword(String image, String password);
    public int insertOfImageAndMoney(String image, String money);
    public int insertOfImageAndPhone(String image, String phone);
    public int insertOfImageAndParam(String image, String param);
    public int insertOfImageAndUserIds(String image, String userIds);
    public int insertOfImageAndName(String image, String name);
    public int insertOfImageAndResgisterDate(String image, String resgisterDate);
    public int insertOfImageAndEmail(String image, String email);
    public int insertOfImageAndDesc(String image, String desc);
    public int insertOfLvlAndNewIds(String lvl, String newIds);
    public int insertOfLvlAndFamous(String lvl, String famous);
    public int insertOfLvlAndSex(String lvl, String sex);
    public int insertOfLvlAndLoginDate(String lvl, String loginDate);
    public int insertOfLvlAndUserId(String lvl, String userId);
    public int insertOfLvlAndBUserIds(String lvl, String bUserIds);
    public int insertOfLvlAndScore(String lvl, String score);
    public int insertOfLvlAndPath(String lvl, String path);
    public int insertOfLvlAndPassword(String lvl, String password);
    public int insertOfLvlAndMoney(String lvl, String money);
    public int insertOfLvlAndPhone(String lvl, String phone);
    public int insertOfLvlAndParam(String lvl, String param);
    public int insertOfLvlAndUserIds(String lvl, String userIds);
    public int insertOfLvlAndName(String lvl, String name);
    public int insertOfLvlAndResgisterDate(String lvl, String resgisterDate);
    public int insertOfLvlAndEmail(String lvl, String email);
    public int insertOfLvlAndDesc(String lvl, String desc);
    public int insertOfNewIdsAndFamous(String newIds, String famous);
    public int insertOfNewIdsAndSex(String newIds, String sex);
    public int insertOfNewIdsAndLoginDate(String newIds, String loginDate);
    public int insertOfNewIdsAndUserId(String newIds, String userId);
    public int insertOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public int insertOfNewIdsAndScore(String newIds, String score);
    public int insertOfNewIdsAndPath(String newIds, String path);
    public int insertOfNewIdsAndPassword(String newIds, String password);
    public int insertOfNewIdsAndMoney(String newIds, String money);
    public int insertOfNewIdsAndPhone(String newIds, String phone);
    public int insertOfNewIdsAndParam(String newIds, String param);
    public int insertOfNewIdsAndUserIds(String newIds, String userIds);
    public int insertOfNewIdsAndName(String newIds, String name);
    public int insertOfNewIdsAndResgisterDate(String newIds, String resgisterDate);
    public int insertOfNewIdsAndEmail(String newIds, String email);
    public int insertOfNewIdsAndDesc(String newIds, String desc);
    public int insertOfFamousAndSex(String famous, String sex);
    public int insertOfFamousAndLoginDate(String famous, String loginDate);
    public int insertOfFamousAndUserId(String famous, String userId);
    public int insertOfFamousAndBUserIds(String famous, String bUserIds);
    public int insertOfFamousAndScore(String famous, String score);
    public int insertOfFamousAndPath(String famous, String path);
    public int insertOfFamousAndPassword(String famous, String password);
    public int insertOfFamousAndMoney(String famous, String money);
    public int insertOfFamousAndPhone(String famous, String phone);
    public int insertOfFamousAndParam(String famous, String param);
    public int insertOfFamousAndUserIds(String famous, String userIds);
    public int insertOfFamousAndName(String famous, String name);
    public int insertOfFamousAndResgisterDate(String famous, String resgisterDate);
    public int insertOfFamousAndEmail(String famous, String email);
    public int insertOfFamousAndDesc(String famous, String desc);
    public int insertOfSexAndLoginDate(String sex, String loginDate);
    public int insertOfSexAndUserId(String sex, String userId);
    public int insertOfSexAndBUserIds(String sex, String bUserIds);
    public int insertOfSexAndScore(String sex, String score);
    public int insertOfSexAndPath(String sex, String path);
    public int insertOfSexAndPassword(String sex, String password);
    public int insertOfSexAndMoney(String sex, String money);
    public int insertOfSexAndPhone(String sex, String phone);
    public int insertOfSexAndParam(String sex, String param);
    public int insertOfSexAndUserIds(String sex, String userIds);
    public int insertOfSexAndName(String sex, String name);
    public int insertOfSexAndResgisterDate(String sex, String resgisterDate);
    public int insertOfSexAndEmail(String sex, String email);
    public int insertOfSexAndDesc(String sex, String desc);
    public int insertOfLoginDateAndUserId(String loginDate, String userId);
    public int insertOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public int insertOfLoginDateAndScore(String loginDate, String score);
    public int insertOfLoginDateAndPath(String loginDate, String path);
    public int insertOfLoginDateAndPassword(String loginDate, String password);
    public int insertOfLoginDateAndMoney(String loginDate, String money);
    public int insertOfLoginDateAndPhone(String loginDate, String phone);
    public int insertOfLoginDateAndParam(String loginDate, String param);
    public int insertOfLoginDateAndUserIds(String loginDate, String userIds);
    public int insertOfLoginDateAndName(String loginDate, String name);
    public int insertOfLoginDateAndResgisterDate(String loginDate, String resgisterDate);
    public int insertOfLoginDateAndEmail(String loginDate, String email);
    public int insertOfLoginDateAndDesc(String loginDate, String desc);
    public int insertOfUserIdAndBUserIds(String userId, String bUserIds);
    public int insertOfUserIdAndScore(String userId, String score);
    public int insertOfUserIdAndPath(String userId, String path);
    public int insertOfUserIdAndPassword(String userId, String password);
    public int insertOfUserIdAndMoney(String userId, String money);
    public int insertOfUserIdAndPhone(String userId, String phone);
    public int insertOfUserIdAndParam(String userId, String param);
    public int insertOfUserIdAndUserIds(String userId, String userIds);
    public int insertOfUserIdAndName(String userId, String name);
    public int insertOfUserIdAndResgisterDate(String userId, String resgisterDate);
    public int insertOfUserIdAndEmail(String userId, String email);
    public int insertOfUserIdAndDesc(String userId, String desc);
    public int insertOfBUserIdsAndScore(String bUserIds, String score);
    public int insertOfBUserIdsAndPath(String bUserIds, String path);
    public int insertOfBUserIdsAndPassword(String bUserIds, String password);
    public int insertOfBUserIdsAndMoney(String bUserIds, String money);
    public int insertOfBUserIdsAndPhone(String bUserIds, String phone);
    public int insertOfBUserIdsAndParam(String bUserIds, String param);
    public int insertOfBUserIdsAndUserIds(String bUserIds, String userIds);
    public int insertOfBUserIdsAndName(String bUserIds, String name);
    public int insertOfBUserIdsAndResgisterDate(String bUserIds, String resgisterDate);
    public int insertOfBUserIdsAndEmail(String bUserIds, String email);
    public int insertOfBUserIdsAndDesc(String bUserIds, String desc);
    public int insertOfScoreAndPath(String score, String path);
    public int insertOfScoreAndPassword(String score, String password);
    public int insertOfScoreAndMoney(String score, String money);
    public int insertOfScoreAndPhone(String score, String phone);
    public int insertOfScoreAndParam(String score, String param);
    public int insertOfScoreAndUserIds(String score, String userIds);
    public int insertOfScoreAndName(String score, String name);
    public int insertOfScoreAndResgisterDate(String score, String resgisterDate);
    public int insertOfScoreAndEmail(String score, String email);
    public int insertOfScoreAndDesc(String score, String desc);
    public int insertOfPathAndPassword(String path, String password);
    public int insertOfPathAndMoney(String path, String money);
    public int insertOfPathAndPhone(String path, String phone);
    public int insertOfPathAndParam(String path, String param);
    public int insertOfPathAndUserIds(String path, String userIds);
    public int insertOfPathAndName(String path, String name);
    public int insertOfPathAndResgisterDate(String path, String resgisterDate);
    public int insertOfPathAndEmail(String path, String email);
    public int insertOfPathAndDesc(String path, String desc);
    public int insertOfPasswordAndMoney(String password, String money);
    public int insertOfPasswordAndPhone(String password, String phone);
    public int insertOfPasswordAndParam(String password, String param);
    public int insertOfPasswordAndUserIds(String password, String userIds);
    public int insertOfPasswordAndName(String password, String name);
    public int insertOfPasswordAndResgisterDate(String password, String resgisterDate);
    public int insertOfPasswordAndEmail(String password, String email);
    public int insertOfPasswordAndDesc(String password, String desc);
    public int insertOfMoneyAndPhone(String money, String phone);
    public int insertOfMoneyAndParam(String money, String param);
    public int insertOfMoneyAndUserIds(String money, String userIds);
    public int insertOfMoneyAndName(String money, String name);
    public int insertOfMoneyAndResgisterDate(String money, String resgisterDate);
    public int insertOfMoneyAndEmail(String money, String email);
    public int insertOfMoneyAndDesc(String money, String desc);
    public int insertOfPhoneAndParam(String phone, String param);
    public int insertOfPhoneAndUserIds(String phone, String userIds);
    public int insertOfPhoneAndName(String phone, String name);
    public int insertOfPhoneAndResgisterDate(String phone, String resgisterDate);
    public int insertOfPhoneAndEmail(String phone, String email);
    public int insertOfPhoneAndDesc(String phone, String desc);
    public int insertOfParamAndUserIds(String param, String userIds);
    public int insertOfParamAndName(String param, String name);
    public int insertOfParamAndResgisterDate(String param, String resgisterDate);
    public int insertOfParamAndEmail(String param, String email);
    public int insertOfParamAndDesc(String param, String desc);
    public int insertOfUserIdsAndName(String userIds, String name);
    public int insertOfUserIdsAndResgisterDate(String userIds, String resgisterDate);
    public int insertOfUserIdsAndEmail(String userIds, String email);
    public int insertOfUserIdsAndDesc(String userIds, String desc);
    public int insertOfNameAndResgisterDate(String name, String resgisterDate);
    public int insertOfNameAndEmail(String name, String email);
    public int insertOfNameAndDesc(String name, String desc);
    public int insertOfResgisterDateAndEmail(String resgisterDate, String email);
    public int insertOfResgisterDateAndDesc(String resgisterDate, String desc);
    public int insertOfEmailAndDesc(String email, String desc);
    public User getUser(User user);
    public User getUserOfImage(String image);
    public User getUserOfLvl(String lvl);
    public User getUserOfNewIds(String newIds);
    public User getUserOfFamous(String famous);
    public User getUserOfSex(String sex);
    public User getUserOfLoginDate(String loginDate);
    public User getUserOfUserId(String userId);
    public User getUserOfBUserIds(String bUserIds);
    public User getUserOfScore(String score);
    public User getUserOfPath(String path);
    public User getUserOfPassword(String password);
    public User getUserOfMoney(String money);
    public User getUserOfPhone(String phone);
    public User getUserOfParam(String param);
    public User getUserOfUserIds(String userIds);
    public User getUserOfName(String name);
    public User getUserOfResgisterDate(String resgisterDate);
    public User getUserOfEmail(String email);
    public User getUserOfDesc(String desc);
    public User getUserOfImageAndLvl(String image, String lvl);
    public User getUserOfImageAndNewIds(String image, String newIds);
    public User getUserOfImageAndFamous(String image, String famous);
    public User getUserOfImageAndSex(String image, String sex);
    public User getUserOfImageAndLoginDate(String image, String loginDate);
    public User getUserOfImageAndUserId(String image, String userId);
    public User getUserOfImageAndBUserIds(String image, String bUserIds);
    public User getUserOfImageAndScore(String image, String score);
    public User getUserOfImageAndPath(String image, String path);
    public User getUserOfImageAndPassword(String image, String password);
    public User getUserOfImageAndMoney(String image, String money);
    public User getUserOfImageAndPhone(String image, String phone);
    public User getUserOfImageAndParam(String image, String param);
    public User getUserOfImageAndUserIds(String image, String userIds);
    public User getUserOfImageAndName(String image, String name);
    public User getUserOfImageAndResgisterDate(String image, String resgisterDate);
    public User getUserOfImageAndEmail(String image, String email);
    public User getUserOfImageAndDesc(String image, String desc);
    public User getUserOfLvlAndNewIds(String lvl, String newIds);
    public User getUserOfLvlAndFamous(String lvl, String famous);
    public User getUserOfLvlAndSex(String lvl, String sex);
    public User getUserOfLvlAndLoginDate(String lvl, String loginDate);
    public User getUserOfLvlAndUserId(String lvl, String userId);
    public User getUserOfLvlAndBUserIds(String lvl, String bUserIds);
    public User getUserOfLvlAndScore(String lvl, String score);
    public User getUserOfLvlAndPath(String lvl, String path);
    public User getUserOfLvlAndPassword(String lvl, String password);
    public User getUserOfLvlAndMoney(String lvl, String money);
    public User getUserOfLvlAndPhone(String lvl, String phone);
    public User getUserOfLvlAndParam(String lvl, String param);
    public User getUserOfLvlAndUserIds(String lvl, String userIds);
    public User getUserOfLvlAndName(String lvl, String name);
    public User getUserOfLvlAndResgisterDate(String lvl, String resgisterDate);
    public User getUserOfLvlAndEmail(String lvl, String email);
    public User getUserOfLvlAndDesc(String lvl, String desc);
    public User getUserOfNewIdsAndFamous(String newIds, String famous);
    public User getUserOfNewIdsAndSex(String newIds, String sex);
    public User getUserOfNewIdsAndLoginDate(String newIds, String loginDate);
    public User getUserOfNewIdsAndUserId(String newIds, String userId);
    public User getUserOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public User getUserOfNewIdsAndScore(String newIds, String score);
    public User getUserOfNewIdsAndPath(String newIds, String path);
    public User getUserOfNewIdsAndPassword(String newIds, String password);
    public User getUserOfNewIdsAndMoney(String newIds, String money);
    public User getUserOfNewIdsAndPhone(String newIds, String phone);
    public User getUserOfNewIdsAndParam(String newIds, String param);
    public User getUserOfNewIdsAndUserIds(String newIds, String userIds);
    public User getUserOfNewIdsAndName(String newIds, String name);
    public User getUserOfNewIdsAndResgisterDate(String newIds, String resgisterDate);
    public User getUserOfNewIdsAndEmail(String newIds, String email);
    public User getUserOfNewIdsAndDesc(String newIds, String desc);
    public User getUserOfFamousAndSex(String famous, String sex);
    public User getUserOfFamousAndLoginDate(String famous, String loginDate);
    public User getUserOfFamousAndUserId(String famous, String userId);
    public User getUserOfFamousAndBUserIds(String famous, String bUserIds);
    public User getUserOfFamousAndScore(String famous, String score);
    public User getUserOfFamousAndPath(String famous, String path);
    public User getUserOfFamousAndPassword(String famous, String password);
    public User getUserOfFamousAndMoney(String famous, String money);
    public User getUserOfFamousAndPhone(String famous, String phone);
    public User getUserOfFamousAndParam(String famous, String param);
    public User getUserOfFamousAndUserIds(String famous, String userIds);
    public User getUserOfFamousAndName(String famous, String name);
    public User getUserOfFamousAndResgisterDate(String famous, String resgisterDate);
    public User getUserOfFamousAndEmail(String famous, String email);
    public User getUserOfFamousAndDesc(String famous, String desc);
    public User getUserOfSexAndLoginDate(String sex, String loginDate);
    public User getUserOfSexAndUserId(String sex, String userId);
    public User getUserOfSexAndBUserIds(String sex, String bUserIds);
    public User getUserOfSexAndScore(String sex, String score);
    public User getUserOfSexAndPath(String sex, String path);
    public User getUserOfSexAndPassword(String sex, String password);
    public User getUserOfSexAndMoney(String sex, String money);
    public User getUserOfSexAndPhone(String sex, String phone);
    public User getUserOfSexAndParam(String sex, String param);
    public User getUserOfSexAndUserIds(String sex, String userIds);
    public User getUserOfSexAndName(String sex, String name);
    public User getUserOfSexAndResgisterDate(String sex, String resgisterDate);
    public User getUserOfSexAndEmail(String sex, String email);
    public User getUserOfSexAndDesc(String sex, String desc);
    public User getUserOfLoginDateAndUserId(String loginDate, String userId);
    public User getUserOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public User getUserOfLoginDateAndScore(String loginDate, String score);
    public User getUserOfLoginDateAndPath(String loginDate, String path);
    public User getUserOfLoginDateAndPassword(String loginDate, String password);
    public User getUserOfLoginDateAndMoney(String loginDate, String money);
    public User getUserOfLoginDateAndPhone(String loginDate, String phone);
    public User getUserOfLoginDateAndParam(String loginDate, String param);
    public User getUserOfLoginDateAndUserIds(String loginDate, String userIds);
    public User getUserOfLoginDateAndName(String loginDate, String name);
    public User getUserOfLoginDateAndResgisterDate(String loginDate, String resgisterDate);
    public User getUserOfLoginDateAndEmail(String loginDate, String email);
    public User getUserOfLoginDateAndDesc(String loginDate, String desc);
    public User getUserOfUserIdAndBUserIds(String userId, String bUserIds);
    public User getUserOfUserIdAndScore(String userId, String score);
    public User getUserOfUserIdAndPath(String userId, String path);
    public User getUserOfUserIdAndPassword(String userId, String password);
    public User getUserOfUserIdAndMoney(String userId, String money);
    public User getUserOfUserIdAndPhone(String userId, String phone);
    public User getUserOfUserIdAndParam(String userId, String param);
    public User getUserOfUserIdAndUserIds(String userId, String userIds);
    public User getUserOfUserIdAndName(String userId, String name);
    public User getUserOfUserIdAndResgisterDate(String userId, String resgisterDate);
    public User getUserOfUserIdAndEmail(String userId, String email);
    public User getUserOfUserIdAndDesc(String userId, String desc);
    public User getUserOfBUserIdsAndScore(String bUserIds, String score);
    public User getUserOfBUserIdsAndPath(String bUserIds, String path);
    public User getUserOfBUserIdsAndPassword(String bUserIds, String password);
    public User getUserOfBUserIdsAndMoney(String bUserIds, String money);
    public User getUserOfBUserIdsAndPhone(String bUserIds, String phone);
    public User getUserOfBUserIdsAndParam(String bUserIds, String param);
    public User getUserOfBUserIdsAndUserIds(String bUserIds, String userIds);
    public User getUserOfBUserIdsAndName(String bUserIds, String name);
    public User getUserOfBUserIdsAndResgisterDate(String bUserIds, String resgisterDate);
    public User getUserOfBUserIdsAndEmail(String bUserIds, String email);
    public User getUserOfBUserIdsAndDesc(String bUserIds, String desc);
    public User getUserOfScoreAndPath(String score, String path);
    public User getUserOfScoreAndPassword(String score, String password);
    public User getUserOfScoreAndMoney(String score, String money);
    public User getUserOfScoreAndPhone(String score, String phone);
    public User getUserOfScoreAndParam(String score, String param);
    public User getUserOfScoreAndUserIds(String score, String userIds);
    public User getUserOfScoreAndName(String score, String name);
    public User getUserOfScoreAndResgisterDate(String score, String resgisterDate);
    public User getUserOfScoreAndEmail(String score, String email);
    public User getUserOfScoreAndDesc(String score, String desc);
    public User getUserOfPathAndPassword(String path, String password);
    public User getUserOfPathAndMoney(String path, String money);
    public User getUserOfPathAndPhone(String path, String phone);
    public User getUserOfPathAndParam(String path, String param);
    public User getUserOfPathAndUserIds(String path, String userIds);
    public User getUserOfPathAndName(String path, String name);
    public User getUserOfPathAndResgisterDate(String path, String resgisterDate);
    public User getUserOfPathAndEmail(String path, String email);
    public User getUserOfPathAndDesc(String path, String desc);
    public User getUserOfPasswordAndMoney(String password, String money);
    public User getUserOfPasswordAndPhone(String password, String phone);
    public User getUserOfPasswordAndParam(String password, String param);
    public User getUserOfPasswordAndUserIds(String password, String userIds);
    public User getUserOfPasswordAndName(String password, String name);
    public User getUserOfPasswordAndResgisterDate(String password, String resgisterDate);
    public User getUserOfPasswordAndEmail(String password, String email);
    public User getUserOfPasswordAndDesc(String password, String desc);
    public User getUserOfMoneyAndPhone(String money, String phone);
    public User getUserOfMoneyAndParam(String money, String param);
    public User getUserOfMoneyAndUserIds(String money, String userIds);
    public User getUserOfMoneyAndName(String money, String name);
    public User getUserOfMoneyAndResgisterDate(String money, String resgisterDate);
    public User getUserOfMoneyAndEmail(String money, String email);
    public User getUserOfMoneyAndDesc(String money, String desc);
    public User getUserOfPhoneAndParam(String phone, String param);
    public User getUserOfPhoneAndUserIds(String phone, String userIds);
    public User getUserOfPhoneAndName(String phone, String name);
    public User getUserOfPhoneAndResgisterDate(String phone, String resgisterDate);
    public User getUserOfPhoneAndEmail(String phone, String email);
    public User getUserOfPhoneAndDesc(String phone, String desc);
    public User getUserOfParamAndUserIds(String param, String userIds);
    public User getUserOfParamAndName(String param, String name);
    public User getUserOfParamAndResgisterDate(String param, String resgisterDate);
    public User getUserOfParamAndEmail(String param, String email);
    public User getUserOfParamAndDesc(String param, String desc);
    public User getUserOfUserIdsAndName(String userIds, String name);
    public User getUserOfUserIdsAndResgisterDate(String userIds, String resgisterDate);
    public User getUserOfUserIdsAndEmail(String userIds, String email);
    public User getUserOfUserIdsAndDesc(String userIds, String desc);
    public User getUserOfNameAndResgisterDate(String name, String resgisterDate);
    public User getUserOfNameAndEmail(String name, String email);
    public User getUserOfNameAndDesc(String name, String desc);
    public User getUserOfResgisterDateAndEmail(String resgisterDate, String email);
    public User getUserOfResgisterDateAndDesc(String resgisterDate, String desc);
    public User getUserOfEmailAndDesc(String email, String desc);
    public List<User> getUsers(User user);
    public List<User> getUsersOfImage(String image);
    public List<User> getUsersOfLvl(String lvl);
    public List<User> getUsersOfNewIds(String newIds);
    public List<User> getUsersOfFamous(String famous);
    public List<User> getUsersOfSex(String sex);
    public List<User> getUsersOfLoginDate(String loginDate);
    public List<User> getUsersOfUserId(String userId);
    public List<User> getUsersOfBUserIds(String bUserIds);
    public List<User> getUsersOfScore(String score);
    public List<User> getUsersOfPath(String path);
    public List<User> getUsersOfPassword(String password);
    public List<User> getUsersOfMoney(String money);
    public List<User> getUsersOfPhone(String phone);
    public List<User> getUsersOfParam(String param);
    public List<User> getUsersOfUserIds(String userIds);
    public List<User> getUsersOfName(String name);
    public List<User> getUsersOfResgisterDate(String resgisterDate);
    public List<User> getUsersOfEmail(String email);
    public List<User> getUsersOfDesc(String desc);
    public List<User> getUsersOfImageAndLvl(String image, String lvl);
    public List<User> getUsersOfImageAndNewIds(String image, String newIds);
    public List<User> getUsersOfImageAndFamous(String image, String famous);
    public List<User> getUsersOfImageAndSex(String image, String sex);
    public List<User> getUsersOfImageAndLoginDate(String image, String loginDate);
    public List<User> getUsersOfImageAndUserId(String image, String userId);
    public List<User> getUsersOfImageAndBUserIds(String image, String bUserIds);
    public List<User> getUsersOfImageAndScore(String image, String score);
    public List<User> getUsersOfImageAndPath(String image, String path);
    public List<User> getUsersOfImageAndPassword(String image, String password);
    public List<User> getUsersOfImageAndMoney(String image, String money);
    public List<User> getUsersOfImageAndPhone(String image, String phone);
    public List<User> getUsersOfImageAndParam(String image, String param);
    public List<User> getUsersOfImageAndUserIds(String image, String userIds);
    public List<User> getUsersOfImageAndName(String image, String name);
    public List<User> getUsersOfImageAndResgisterDate(String image, String resgisterDate);
    public List<User> getUsersOfImageAndEmail(String image, String email);
    public List<User> getUsersOfImageAndDesc(String image, String desc);
    public List<User> getUsersOfLvlAndNewIds(String lvl, String newIds);
    public List<User> getUsersOfLvlAndFamous(String lvl, String famous);
    public List<User> getUsersOfLvlAndSex(String lvl, String sex);
    public List<User> getUsersOfLvlAndLoginDate(String lvl, String loginDate);
    public List<User> getUsersOfLvlAndUserId(String lvl, String userId);
    public List<User> getUsersOfLvlAndBUserIds(String lvl, String bUserIds);
    public List<User> getUsersOfLvlAndScore(String lvl, String score);
    public List<User> getUsersOfLvlAndPath(String lvl, String path);
    public List<User> getUsersOfLvlAndPassword(String lvl, String password);
    public List<User> getUsersOfLvlAndMoney(String lvl, String money);
    public List<User> getUsersOfLvlAndPhone(String lvl, String phone);
    public List<User> getUsersOfLvlAndParam(String lvl, String param);
    public List<User> getUsersOfLvlAndUserIds(String lvl, String userIds);
    public List<User> getUsersOfLvlAndName(String lvl, String name);
    public List<User> getUsersOfLvlAndResgisterDate(String lvl, String resgisterDate);
    public List<User> getUsersOfLvlAndEmail(String lvl, String email);
    public List<User> getUsersOfLvlAndDesc(String lvl, String desc);
    public List<User> getUsersOfNewIdsAndFamous(String newIds, String famous);
    public List<User> getUsersOfNewIdsAndSex(String newIds, String sex);
    public List<User> getUsersOfNewIdsAndLoginDate(String newIds, String loginDate);
    public List<User> getUsersOfNewIdsAndUserId(String newIds, String userId);
    public List<User> getUsersOfNewIdsAndBUserIds(String newIds, String bUserIds);
    public List<User> getUsersOfNewIdsAndScore(String newIds, String score);
    public List<User> getUsersOfNewIdsAndPath(String newIds, String path);
    public List<User> getUsersOfNewIdsAndPassword(String newIds, String password);
    public List<User> getUsersOfNewIdsAndMoney(String newIds, String money);
    public List<User> getUsersOfNewIdsAndPhone(String newIds, String phone);
    public List<User> getUsersOfNewIdsAndParam(String newIds, String param);
    public List<User> getUsersOfNewIdsAndUserIds(String newIds, String userIds);
    public List<User> getUsersOfNewIdsAndName(String newIds, String name);
    public List<User> getUsersOfNewIdsAndResgisterDate(String newIds, String resgisterDate);
    public List<User> getUsersOfNewIdsAndEmail(String newIds, String email);
    public List<User> getUsersOfNewIdsAndDesc(String newIds, String desc);
    public List<User> getUsersOfFamousAndSex(String famous, String sex);
    public List<User> getUsersOfFamousAndLoginDate(String famous, String loginDate);
    public List<User> getUsersOfFamousAndUserId(String famous, String userId);
    public List<User> getUsersOfFamousAndBUserIds(String famous, String bUserIds);
    public List<User> getUsersOfFamousAndScore(String famous, String score);
    public List<User> getUsersOfFamousAndPath(String famous, String path);
    public List<User> getUsersOfFamousAndPassword(String famous, String password);
    public List<User> getUsersOfFamousAndMoney(String famous, String money);
    public List<User> getUsersOfFamousAndPhone(String famous, String phone);
    public List<User> getUsersOfFamousAndParam(String famous, String param);
    public List<User> getUsersOfFamousAndUserIds(String famous, String userIds);
    public List<User> getUsersOfFamousAndName(String famous, String name);
    public List<User> getUsersOfFamousAndResgisterDate(String famous, String resgisterDate);
    public List<User> getUsersOfFamousAndEmail(String famous, String email);
    public List<User> getUsersOfFamousAndDesc(String famous, String desc);
    public List<User> getUsersOfSexAndLoginDate(String sex, String loginDate);
    public List<User> getUsersOfSexAndUserId(String sex, String userId);
    public List<User> getUsersOfSexAndBUserIds(String sex, String bUserIds);
    public List<User> getUsersOfSexAndScore(String sex, String score);
    public List<User> getUsersOfSexAndPath(String sex, String path);
    public List<User> getUsersOfSexAndPassword(String sex, String password);
    public List<User> getUsersOfSexAndMoney(String sex, String money);
    public List<User> getUsersOfSexAndPhone(String sex, String phone);
    public List<User> getUsersOfSexAndParam(String sex, String param);
    public List<User> getUsersOfSexAndUserIds(String sex, String userIds);
    public List<User> getUsersOfSexAndName(String sex, String name);
    public List<User> getUsersOfSexAndResgisterDate(String sex, String resgisterDate);
    public List<User> getUsersOfSexAndEmail(String sex, String email);
    public List<User> getUsersOfSexAndDesc(String sex, String desc);
    public List<User> getUsersOfLoginDateAndUserId(String loginDate, String userId);
    public List<User> getUsersOfLoginDateAndBUserIds(String loginDate, String bUserIds);
    public List<User> getUsersOfLoginDateAndScore(String loginDate, String score);
    public List<User> getUsersOfLoginDateAndPath(String loginDate, String path);
    public List<User> getUsersOfLoginDateAndPassword(String loginDate, String password);
    public List<User> getUsersOfLoginDateAndMoney(String loginDate, String money);
    public List<User> getUsersOfLoginDateAndPhone(String loginDate, String phone);
    public List<User> getUsersOfLoginDateAndParam(String loginDate, String param);
    public List<User> getUsersOfLoginDateAndUserIds(String loginDate, String userIds);
    public List<User> getUsersOfLoginDateAndName(String loginDate, String name);
    public List<User> getUsersOfLoginDateAndResgisterDate(String loginDate, String resgisterDate);
    public List<User> getUsersOfLoginDateAndEmail(String loginDate, String email);
    public List<User> getUsersOfLoginDateAndDesc(String loginDate, String desc);
    public List<User> getUsersOfUserIdAndBUserIds(String userId, String bUserIds);
    public List<User> getUsersOfUserIdAndScore(String userId, String score);
    public List<User> getUsersOfUserIdAndPath(String userId, String path);
    public List<User> getUsersOfUserIdAndPassword(String userId, String password);
    public List<User> getUsersOfUserIdAndMoney(String userId, String money);
    public List<User> getUsersOfUserIdAndPhone(String userId, String phone);
    public List<User> getUsersOfUserIdAndParam(String userId, String param);
    public List<User> getUsersOfUserIdAndUserIds(String userId, String userIds);
    public List<User> getUsersOfUserIdAndName(String userId, String name);
    public List<User> getUsersOfUserIdAndResgisterDate(String userId, String resgisterDate);
    public List<User> getUsersOfUserIdAndEmail(String userId, String email);
    public List<User> getUsersOfUserIdAndDesc(String userId, String desc);
    public List<User> getUsersOfBUserIdsAndScore(String bUserIds, String score);
    public List<User> getUsersOfBUserIdsAndPath(String bUserIds, String path);
    public List<User> getUsersOfBUserIdsAndPassword(String bUserIds, String password);
    public List<User> getUsersOfBUserIdsAndMoney(String bUserIds, String money);
    public List<User> getUsersOfBUserIdsAndPhone(String bUserIds, String phone);
    public List<User> getUsersOfBUserIdsAndParam(String bUserIds, String param);
    public List<User> getUsersOfBUserIdsAndUserIds(String bUserIds, String userIds);
    public List<User> getUsersOfBUserIdsAndName(String bUserIds, String name);
    public List<User> getUsersOfBUserIdsAndResgisterDate(String bUserIds, String resgisterDate);
    public List<User> getUsersOfBUserIdsAndEmail(String bUserIds, String email);
    public List<User> getUsersOfBUserIdsAndDesc(String bUserIds, String desc);
    public List<User> getUsersOfScoreAndPath(String score, String path);
    public List<User> getUsersOfScoreAndPassword(String score, String password);
    public List<User> getUsersOfScoreAndMoney(String score, String money);
    public List<User> getUsersOfScoreAndPhone(String score, String phone);
    public List<User> getUsersOfScoreAndParam(String score, String param);
    public List<User> getUsersOfScoreAndUserIds(String score, String userIds);
    public List<User> getUsersOfScoreAndName(String score, String name);
    public List<User> getUsersOfScoreAndResgisterDate(String score, String resgisterDate);
    public List<User> getUsersOfScoreAndEmail(String score, String email);
    public List<User> getUsersOfScoreAndDesc(String score, String desc);
    public List<User> getUsersOfPathAndPassword(String path, String password);
    public List<User> getUsersOfPathAndMoney(String path, String money);
    public List<User> getUsersOfPathAndPhone(String path, String phone);
    public List<User> getUsersOfPathAndParam(String path, String param);
    public List<User> getUsersOfPathAndUserIds(String path, String userIds);
    public List<User> getUsersOfPathAndName(String path, String name);
    public List<User> getUsersOfPathAndResgisterDate(String path, String resgisterDate);
    public List<User> getUsersOfPathAndEmail(String path, String email);
    public List<User> getUsersOfPathAndDesc(String path, String desc);
    public List<User> getUsersOfPasswordAndMoney(String password, String money);
    public List<User> getUsersOfPasswordAndPhone(String password, String phone);
    public List<User> getUsersOfPasswordAndParam(String password, String param);
    public List<User> getUsersOfPasswordAndUserIds(String password, String userIds);
    public List<User> getUsersOfPasswordAndName(String password, String name);
    public List<User> getUsersOfPasswordAndResgisterDate(String password, String resgisterDate);
    public List<User> getUsersOfPasswordAndEmail(String password, String email);
    public List<User> getUsersOfPasswordAndDesc(String password, String desc);
    public List<User> getUsersOfMoneyAndPhone(String money, String phone);
    public List<User> getUsersOfMoneyAndParam(String money, String param);
    public List<User> getUsersOfMoneyAndUserIds(String money, String userIds);
    public List<User> getUsersOfMoneyAndName(String money, String name);
    public List<User> getUsersOfMoneyAndResgisterDate(String money, String resgisterDate);
    public List<User> getUsersOfMoneyAndEmail(String money, String email);
    public List<User> getUsersOfMoneyAndDesc(String money, String desc);
    public List<User> getUsersOfPhoneAndParam(String phone, String param);
    public List<User> getUsersOfPhoneAndUserIds(String phone, String userIds);
    public List<User> getUsersOfPhoneAndName(String phone, String name);
    public List<User> getUsersOfPhoneAndResgisterDate(String phone, String resgisterDate);
    public List<User> getUsersOfPhoneAndEmail(String phone, String email);
    public List<User> getUsersOfPhoneAndDesc(String phone, String desc);
    public List<User> getUsersOfParamAndUserIds(String param, String userIds);
    public List<User> getUsersOfParamAndName(String param, String name);
    public List<User> getUsersOfParamAndResgisterDate(String param, String resgisterDate);
    public List<User> getUsersOfParamAndEmail(String param, String email);
    public List<User> getUsersOfParamAndDesc(String param, String desc);
    public List<User> getUsersOfUserIdsAndName(String userIds, String name);
    public List<User> getUsersOfUserIdsAndResgisterDate(String userIds, String resgisterDate);
    public List<User> getUsersOfUserIdsAndEmail(String userIds, String email);
    public List<User> getUsersOfUserIdsAndDesc(String userIds, String desc);
    public List<User> getUsersOfNameAndResgisterDate(String name, String resgisterDate);
    public List<User> getUsersOfNameAndEmail(String name, String email);
    public List<User> getUsersOfNameAndDesc(String name, String desc);
    public List<User> getUsersOfResgisterDateAndEmail(String resgisterDate, String email);
    public List<User> getUsersOfResgisterDateAndDesc(String resgisterDate, String desc);
    public List<User> getUsersOfEmailAndDesc(String email, String desc);
}
