package com.news.linglian.service;

import java.util.List;

import com.news.linglian.entity.User;

public interface IUserService {
    public int update(User user, User keyUser);
    public int updateOfUserId(User user, String userId);
    public int updateOfPassword(User user, String password);
    public int updateOfQid(User user, String qid);
    public int updateOfAnswer(User user, String answer);
    public int updateOfScore(User user, String score);
    public int updateOfUserIdAndPassword(User user, String userId, String password);
    public int updateOfUserIdAndQid(User user, String userId, String qid);
    public int updateOfUserIdAndAnswer(User user, String userId, String answer);
    public int updateOfUserIdAndScore(User user, String userId, String score);
    public int updateOfPasswordAndQid(User user, String password, String qid);
    public int updateOfPasswordAndAnswer(User user, String password, String answer);
    public int updateOfPasswordAndScore(User user, String password, String score);
    public int updateOfQidAndAnswer(User user, String qid, String answer);
    public int updateOfQidAndScore(User user, String qid, String score);
    public int updateOfAnswerAndScore(User user, String answer, String score);
    public int updateOfUserIdAndPasswordAndQid(User user, String userId, String password, String qid);
    public int updateOfUserIdAndPasswordAndAnswer(User user, String userId, String password, String answer);
    public int updateOfUserIdAndPasswordAndScore(User user, String userId, String password, String score);
    public int updateOfUserIdAndQidAndAnswer(User user, String userId, String qid, String answer);
    public int updateOfUserIdAndQidAndScore(User user, String userId, String qid, String score);
    public int updateOfUserIdAndAnswerAndScore(User user, String userId, String answer, String score);
    public int updateOfPasswordAndQidAndAnswer(User user, String password, String qid, String answer);
    public int updateOfPasswordAndQidAndScore(User user, String password, String qid, String score);
    public int updateOfPasswordAndAnswerAndScore(User user, String password, String answer, String score);
    public int updateOfQidAndAnswerAndScore(User user, String qid, String answer, String score);
    public int updateOfUserIdAndPasswordAndQidAndAnswer(User user, String userId, String password, String qid, String answer);
    public int updateOfUserIdAndPasswordAndQidAndScore(User user, String userId, String password, String qid, String score);
    public int updateOfUserIdAndPasswordAndAnswerAndScore(User user, String userId, String password, String answer, String score);
    public int updateOfUserIdAndQidAndAnswerAndScore(User user, String userId, String qid, String answer, String score);
    public int updateOfPasswordAndQidAndAnswerAndScore(User user, String password, String qid, String answer, String score);
    public int updateOfUserIdAndPasswordAndQidAndAnswerAndScore(User user, String userId, String password, String qid, String answer, String score);
    public int remove(User user);
    public int removeOfUserId(String userId);
    public int removeOfPassword(String password);
    public int removeOfQid(String qid);
    public int removeOfAnswer(String answer);
    public int removeOfScore(String score);
    public int removeOfUserIdAndPassword(String userId, String password);
    public int removeOfUserIdAndQid(String userId, String qid);
    public int removeOfUserIdAndAnswer(String userId, String answer);
    public int removeOfUserIdAndScore(String userId, String score);
    public int removeOfPasswordAndQid(String password, String qid);
    public int removeOfPasswordAndAnswer(String password, String answer);
    public int removeOfPasswordAndScore(String password, String score);
    public int removeOfQidAndAnswer(String qid, String answer);
    public int removeOfQidAndScore(String qid, String score);
    public int removeOfAnswerAndScore(String answer, String score);
    public int removeOfUserIdAndPasswordAndQid(String userId, String password, String qid);
    public int removeOfUserIdAndPasswordAndAnswer(String userId, String password, String answer);
    public int removeOfUserIdAndPasswordAndScore(String userId, String password, String score);
    public int removeOfUserIdAndQidAndAnswer(String userId, String qid, String answer);
    public int removeOfUserIdAndQidAndScore(String userId, String qid, String score);
    public int removeOfUserIdAndAnswerAndScore(String userId, String answer, String score);
    public int removeOfPasswordAndQidAndAnswer(String password, String qid, String answer);
    public int removeOfPasswordAndQidAndScore(String password, String qid, String score);
    public int removeOfPasswordAndAnswerAndScore(String password, String answer, String score);
    public int removeOfQidAndAnswerAndScore(String qid, String answer, String score);
    public int removeOfUserIdAndPasswordAndQidAndAnswer(String userId, String password, String qid, String answer);
    public int removeOfUserIdAndPasswordAndQidAndScore(String userId, String password, String qid, String score);
    public int removeOfUserIdAndPasswordAndAnswerAndScore(String userId, String password, String answer, String score);
    public int removeOfUserIdAndQidAndAnswerAndScore(String userId, String qid, String answer, String score);
    public int removeOfPasswordAndQidAndAnswerAndScore(String password, String qid, String answer, String score);
    public int removeOfUserIdAndPasswordAndQidAndAnswerAndScore(String userId, String password, String qid, String answer, String score);
    public int insert(User user);
    public int insertOfUserId(String userId);
    public int insertOfPassword(String password);
    public int insertOfQid(String qid);
    public int insertOfAnswer(String answer);
    public int insertOfScore(String score);
    public int insertOfUserIdAndPassword(String userId, String password);
    public int insertOfUserIdAndQid(String userId, String qid);
    public int insertOfUserIdAndAnswer(String userId, String answer);
    public int insertOfUserIdAndScore(String userId, String score);
    public int insertOfPasswordAndQid(String password, String qid);
    public int insertOfPasswordAndAnswer(String password, String answer);
    public int insertOfPasswordAndScore(String password, String score);
    public int insertOfQidAndAnswer(String qid, String answer);
    public int insertOfQidAndScore(String qid, String score);
    public int insertOfAnswerAndScore(String answer, String score);
    public int insertOfUserIdAndPasswordAndQid(String userId, String password, String qid);
    public int insertOfUserIdAndPasswordAndAnswer(String userId, String password, String answer);
    public int insertOfUserIdAndPasswordAndScore(String userId, String password, String score);
    public int insertOfUserIdAndQidAndAnswer(String userId, String qid, String answer);
    public int insertOfUserIdAndQidAndScore(String userId, String qid, String score);
    public int insertOfUserIdAndAnswerAndScore(String userId, String answer, String score);
    public int insertOfPasswordAndQidAndAnswer(String password, String qid, String answer);
    public int insertOfPasswordAndQidAndScore(String password, String qid, String score);
    public int insertOfPasswordAndAnswerAndScore(String password, String answer, String score);
    public int insertOfQidAndAnswerAndScore(String qid, String answer, String score);
    public int insertOfUserIdAndPasswordAndQidAndAnswer(String userId, String password, String qid, String answer);
    public int insertOfUserIdAndPasswordAndQidAndScore(String userId, String password, String qid, String score);
    public int insertOfUserIdAndPasswordAndAnswerAndScore(String userId, String password, String answer, String score);
    public int insertOfUserIdAndQidAndAnswerAndScore(String userId, String qid, String answer, String score);
    public int insertOfPasswordAndQidAndAnswerAndScore(String password, String qid, String answer, String score);
    public int insertOfUserIdAndPasswordAndQidAndAnswerAndScore(String userId, String password, String qid, String answer, String score);
    public User getUser(User user);
    public User getUserOfUserId(String userId);
    public User getUserOfPassword(String password);
    public User getUserOfQid(String qid);
    public User getUserOfAnswer(String answer);
    public User getUserOfScore(String score);
    public User getUserOfUserIdAndPassword(String userId, String password);
    public User getUserOfUserIdAndQid(String userId, String qid);
    public User getUserOfUserIdAndAnswer(String userId, String answer);
    public User getUserOfUserIdAndScore(String userId, String score);
    public User getUserOfPasswordAndQid(String password, String qid);
    public User getUserOfPasswordAndAnswer(String password, String answer);
    public User getUserOfPasswordAndScore(String password, String score);
    public User getUserOfQidAndAnswer(String qid, String answer);
    public User getUserOfQidAndScore(String qid, String score);
    public User getUserOfAnswerAndScore(String answer, String score);
    public User getUserOfUserIdAndPasswordAndQid(String userId, String password, String qid);
    public User getUserOfUserIdAndPasswordAndAnswer(String userId, String password, String answer);
    public User getUserOfUserIdAndPasswordAndScore(String userId, String password, String score);
    public User getUserOfUserIdAndQidAndAnswer(String userId, String qid, String answer);
    public User getUserOfUserIdAndQidAndScore(String userId, String qid, String score);
    public User getUserOfUserIdAndAnswerAndScore(String userId, String answer, String score);
    public User getUserOfPasswordAndQidAndAnswer(String password, String qid, String answer);
    public User getUserOfPasswordAndQidAndScore(String password, String qid, String score);
    public User getUserOfPasswordAndAnswerAndScore(String password, String answer, String score);
    public User getUserOfQidAndAnswerAndScore(String qid, String answer, String score);
    public User getUserOfUserIdAndPasswordAndQidAndAnswer(String userId, String password, String qid, String answer);
    public User getUserOfUserIdAndPasswordAndQidAndScore(String userId, String password, String qid, String score);
    public User getUserOfUserIdAndPasswordAndAnswerAndScore(String userId, String password, String answer, String score);
    public User getUserOfUserIdAndQidAndAnswerAndScore(String userId, String qid, String answer, String score);
    public User getUserOfPasswordAndQidAndAnswerAndScore(String password, String qid, String answer, String score);
    public User getUserOfUserIdAndPasswordAndQidAndAnswerAndScore(String userId, String password, String qid, String answer, String score);
    public List<User> getUsers(User user);
    public List<User> getUsersOfUserId(String userId);
    public List<User> getUsersOfPassword(String password);
    public List<User> getUsersOfQid(String qid);
    public List<User> getUsersOfAnswer(String answer);
    public List<User> getUsersOfScore(String score);
    public List<User> getUsersOfUserIdAndPassword(String userId, String password);
    public List<User> getUsersOfUserIdAndQid(String userId, String qid);
    public List<User> getUsersOfUserIdAndAnswer(String userId, String answer);
    public List<User> getUsersOfUserIdAndScore(String userId, String score);
    public List<User> getUsersOfPasswordAndQid(String password, String qid);
    public List<User> getUsersOfPasswordAndAnswer(String password, String answer);
    public List<User> getUsersOfPasswordAndScore(String password, String score);
    public List<User> getUsersOfQidAndAnswer(String qid, String answer);
    public List<User> getUsersOfQidAndScore(String qid, String score);
    public List<User> getUsersOfAnswerAndScore(String answer, String score);
    public List<User> getUsersOfUserIdAndPasswordAndQid(String userId, String password, String qid);
    public List<User> getUsersOfUserIdAndPasswordAndAnswer(String userId, String password, String answer);
    public List<User> getUsersOfUserIdAndPasswordAndScore(String userId, String password, String score);
    public List<User> getUsersOfUserIdAndQidAndAnswer(String userId, String qid, String answer);
    public List<User> getUsersOfUserIdAndQidAndScore(String userId, String qid, String score);
    public List<User> getUsersOfUserIdAndAnswerAndScore(String userId, String answer, String score);
    public List<User> getUsersOfPasswordAndQidAndAnswer(String password, String qid, String answer);
    public List<User> getUsersOfPasswordAndQidAndScore(String password, String qid, String score);
    public List<User> getUsersOfPasswordAndAnswerAndScore(String password, String answer, String score);
    public List<User> getUsersOfQidAndAnswerAndScore(String qid, String answer, String score);
    public List<User> getUsersOfUserIdAndPasswordAndQidAndAnswer(String userId, String password, String qid, String answer);
    public List<User> getUsersOfUserIdAndPasswordAndQidAndScore(String userId, String password, String qid, String score);
    public List<User> getUsersOfUserIdAndPasswordAndAnswerAndScore(String userId, String password, String answer, String score);
    public List<User> getUsersOfUserIdAndQidAndAnswerAndScore(String userId, String qid, String answer, String score);
    public List<User> getUsersOfPasswordAndQidAndAnswerAndScore(String password, String qid, String answer, String score);
    public List<User> getUsersOfUserIdAndPasswordAndQidAndAnswerAndScore(String userId, String password, String qid, String answer, String score);
}
